### ISSUE TITLE
请问这个web服务的IP地址是自己vps 的IP吗

### ISSUE THREAD

**Issue by ilhsyysyk** [iwestlin/gd-utils#1]
![image](https://user-images.githubusercontent.com/41326182/85917713-217e9780-b88f-11ea-9ac1-d8cc473fc9f5.png)

**Comment by iwestlin** [comment]
你是指your.server.name吗？那个填你解析到vps的域名，如果你打算直接ip访问那就填IP也行。

**Comment by ilhsyysyk** [comment]
> 你是指your.server.name吗？那个填你解析到vps的域名，如果你打算直接ip访问那就填IP​​也行。

我说的是proxy_pass

**Comment by iwestlin** [comment]
哦，那个就是127.0.0.1，意思是nginx把80端口的流量转移到本机的23333端口上。

如果你不想用nignx，可以把 server.js 里的23333直接改成80，这样程序就监听80端口了，不过可能需要root权限
