### ISSUE TITLE
测试 curl 'xxxx/api/gdurl/count?fid=1LggSuwI1n40bcD5tQ13wS0M6wg' 出错

### ISSUE THREAD

**Issue by wh8929** [iwestlin/gd-utils#10]
如题 测试的时候 返回Unexpected end of JSON input。 检查N遍config.js 和 server.js 没改动啥地方 就添加了说明里那些 和换了server 端口去80.

**Comment by wh8929** [comment]
这是log 里面的错误
0|server   |     at JSON.parse (<anonymous>)
0|server   |     at GoogleToken.getCredentials (/root/gd-utils/node_modules/gtoken/build/src/index.js:90:35)
0|server   |     at async GoogleToken.getTokenAsync (/root/gd-utils/node_modules/gtoken/build/src/index.js:128:27)
0|server   | SyntaxError: Unexpected end of JSON input
0|server   |     at JSON.parse (<anonymous>)
0|server   |     at GoogleToken.getCredentials (/root/gd-utils/node_modules/gtoken/build/src/index.js:90:35)
0|server   |     at async GoogleToken.getTokenAsync (/root/gd-utils/node_modules/gtoken/build/src/index.js:128:27)
0|server   | SyntaxError: Unexpected end of JSON input
0|server   |     at JSON.parse (<anonymous>)
0|server   |     at GoogleToken.getCredentials (/root/gd-utils/node_modules/gtoken/build/src/index.js:90:35)
0|server   |     at async GoogleToken.getTokenAsync (/root/gd-utils/node_modules/gtoken/build/src/index.js:128:27)
0|server   | SyntaxError: Unexpected end of JSON input
0|server   |     at JSON.parse (<anonymous>)
0|server   |     at GoogleToken.getCredentials (/root/gd-utils/node_modules/gtoken/build/src/index.js:90:35)
0|server   |     at async GoogleToken.getTokenAsync (/root/gd-utils/node_modules/gtoken/build/src/index.js:128:27)

**Comment by iwestlin** [comment]
你换个公开的链接呢，也是这样吗 https://drive.google.com/drive/folders/124pjM5LggSuwI1n40bcD5tQ13wS0M6wg

**Comment by wh8929** [comment]
root@instance-3:~/gd-utils# curl '127.0.0.1/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg'
Unexpected end of JSON inputroot@instance-3:~/gd-utils#
root@instance-3:~/gd-utils# curl 'xxx.xyz/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg'
Unexpected end of JSON inputroot@instance-3:~/gd-utils#
root@instance-3:~/gd-utils#
这样没错吧

**Comment by iwestlin** [comment]
看样子是你的sa json文件里格式有问题

**Comment by iwestlin** [comment]
<img width="322" alt="截屏2020-06-27 下午7 38 23" src="https://user-images.githubusercontent.com/6235509/85926261-df764580-b8d0-11ea-8acb-baa6a4c6ac81.png">
是这样的吗

**Comment by wh8929** [comment]
我擦 是我sa问题。解压出现问题 没注意到sa是0kb. 谢谢大佬
