### ISSUE TITLE
没有权限的json文件产生的错误

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#100]
这个要怎么解决呢，大神指导
![image](https://user-images.githubusercontent.com/47917048/87266685-70b40180-c4f8-11ea-926b-d1df691488ae.png)

**Comment by iwestlin** [comment]
https://drive.google.com/drive/folders/1iiTAzWF_v9fo_IxrrMYiRGQ7QuPrnxHf
这里有操作示例啊

**Comment by jason8303** [comment]
我用的是colab要咋弄呢

**Comment by iwestlin** [comment]
命令都是一样的吧，`./validate-sa.js 你的目录ID`
colab好像前面要加个 `!!node `
你就照着别的命令改改看？

**Comment by jason8303** [comment]
可以了，感谢大神帮助

**Comment by jason8303** [comment]
还有个问题，你写的程序可以直接在macos上运行么，因为发现colab不稳定，总是断开连接

**Comment by iwestlin** [comment]
当然可以……我就是在mac上开发的。。

**Comment by jason8303** [comment]
明白，虚拟机上的mac可以么

**Comment by iwestlin** [comment]
没在虚拟机上跑过mac，应该都一样的吧，只要命令行挂上代理

**Comment by jason8303** [comment]
好的，回头我试试，谢谢
