### ISSUE TITLE
任务编号如何清除

### ISSUE THREAD

**Issue by luvn1226** [iwestlin/gd-utils#101]
如果想将任务编号归零，应如何操作？

**Comment by iwestlin** [comment]
那个是数据库 `task`这张表的主键，是自动递增的。。
如果要归零，只好用sqlite管理软件手动清空task这张表了，gd-utils没有提供对应的命令

或者可以用GitHub上空的 gdurl.sqlite文件替换掉服务器的这个文件，不过那样的话别的记录也会丢失

**Comment by luvn1226** [comment]
> 那个是数据库 `task`这张表的主键，是自动递增的。。
> 如果要归零，只好用sqlite管理软件手动清空task这张表了，gd-utils没有提供对应的命令
> 
> 或者可以用GitHub上空的 gdurl.sqlite文件替换掉服务器的这个文件，不过那样的话别的记录也会丢失

非常感谢
