### ISSUE TITLE
建议考虑在sm(data)传数据的里面加上消息id

### ISSUE THREAD

**Issue by iouAkira** [iwestlin/gd-utils#103]
建议考虑在sm(data)传数据的里面加上消息id，
![image](https://user-images.githubusercontent.com/6993269/87282328-bdaecc80-c526-11ea-9801-b83635c5405e.png)
统计任务，或者复制可以基于这条消息进行edit，最后点了开始复制的时候建议编辑消息去掉这些按钮，防止后面翻历史消息的时候误点，也可以让翻看自己历史复制的记录更清晰一点

**Comment by iwestlin** [comment]
重口难调啊，有些人就喜欢一份链接复制多份……有时候甚至我也会。。

**Comment by iouAkira** [comment]
哈哈哈，那我还是自己魔改吧

**Comment by iwestlin** [comment]
你可以加个清除按钮的按钮😂

**Comment by iouAkira** [comment]
大佬果然高效率功能已经添加清除按钮
