### ISSUE TITLE
出现“複製失敗，失敗訊息：Request failed with status code 404 目錄名：”的可能原因是？

### ISSUE THREAD

**Issue by kalagxw** [iwestlin/gd-utils#105]
bot已经正常启用，能列目录，但是复制后出现Request failed with status code 404，全部按wiki步骤操作，排查发现sa 验证全部异常。不知什么问题。
是不是买的gsuit的管理员关了什么权限 求解答

**Comment by iwestlin** [comment]
你没有把sa加进团队盘的权限吧？
可以看看这里的两个链接 https://github.com/iwestlin/gd-utils#service-account-%E9%85%8D%E7%BD%AE

**Comment by kalagxw** [comment]
意思是买gsuit的管理员没开是吗

**Comment by iwestlin** [comment]
不是。。「你没有把sa加进团队盘的权限吧？」的意思是你没有把sa帐号加进团队盘的成员里

你可以打开任意一个sa文件，里面会有个email，然后你把email手动加到团队盘的成员里（设置成内容管理员），然后这个sa就可以往这个盘复制文件了。

我给的那两个链接里有批量加成员的方法

**Comment by kalagxw** [comment]
> 不是。。「你没有把sa加进团队盘的权限吧？」的意思是你没有把sa帐号加进团队盘的成员里
> 
> 你可以打开任意一个sa文件，里面会有个email，然后你把email手动加到团队盘的成员里（设置成内容管理员），然后这个sa就可以往这个盘复制文件了。
> 
> 我给的那两个链接里有批量加成员的方法

了解，看到那个是可选就跳过了。。去试下

**Comment by kalagxw** [comment]
> 不是。。「你没有把sa加进团队盘的权限吧？」的意思是你没有把sa帐号加进团队盘的成员里
> 
> 你可以打开任意一个sa文件，里面会有个email，然后你把email手动加到团队盘的成员里（设置成内容管理员），然后这个sa就可以往这个盘复制文件了。
> 
> 我给的那两个链接里有批量加成员的方法

gsuit管理员关闭了域外共享，如何自己拷贝到自己的盘里

**Comment by iwestlin** [comment]
每个sa拷贝到个人盘会有15G的存储空间限制（是sa本身的限制，不是个人盘的空间限制）

**Comment by iwestlin** [comment]
可以用个人帐号授权，不过会有每天750G流量限制。

**Comment by iwestlin** [comment]
feel free to reopen
