### ISSUE TITLE
userRateLimitExceeded,死机

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#107]
用colab，出现userRateLimitExceeded卡死，又用了ubuntu，也出现userRateLimitExceeded，卡死，重启ubuntu也是卡死状态

**Comment by jason8303** [comment]
> 用colab，出现userRateLimitExceeded卡死，又用了ubuntu，也出现userRateLimitExceeded，卡死，重启ubuntu也是卡死状态

是不是跟chrome有关系，我SSH 客户端运行在windows下面，windows下面也打开了chrome，会不会chrome在无声无息中吃完了资源，导致ubuntu没内存，cpu。这个chrome各种幺蛾子，大佬你还在用chrome么，我都想弃用了

**Comment by iwestlin** [comment]
sa每天有750G流量限制，应该是用完了
