### ISSUE TITLE
建议给BOT加一个命令，能更换目的盘

### ISSUE THREAD

**Issue by reman-liao** [iwestlin/gd-utils#108]
有些大的分享，很快就能一下塞满一个团队盘，这时候最方便继续使用，就是直接更换一个目的团队盘，如果能用BOT直接更换，就非常方便了，请大神方便的话，加入一下功能，非常感谢

**Comment by Taoisting** [comment]
更换目的盘，需要sa配套的，不是一把枪指哪打哪。

**Comment by reman-liao** [comment]
哦，那可以弄个脚本自动更新到最新功能吗？大神！

**Comment by iwestlin** [comment]
Linux可以给crontab加一条
```bash
0 3 * * * cd path-to-gd-utils && git pull | grep -v Already && pm2 reload server
```
（`path-to-gd-utils`需要替换成真实路径）
表示定时任务每天凌晨3点在gd-utils目录执行一遍 `git pull`
如果有更新就会自动执行 `pm2 reload server`

**Comment by reman-liao** [comment]
非常感谢！
