### ISSUE TITLE
以及给BOT增加一个变更目的团队盘命令功能

### ISSUE THREAD

**Issue by reman-liao** [iwestlin/gd-utils#109]
有些大的分享，很快就能一下塞满一个团队盘，这时候最方便继续使用，就是直接更换一个目的团队盘，如果能用BOT直接更换，就非常方便了，请大神方便的话，加入一下功能，非常感谢

**Comment by iwestlin** [comment]
重复 https://github.com/iwestlin/gd-utils/issues/108
