### ISSUE TITLE
拷贝完成后目标文件夹结构和源文件夹不一致

### ISSUE THREAD

**Issue by cecaa1030** [iwestlin/gd-utils#11]
如题
源文件夹为 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz

**Comment by cecaa1030** [comment]
跑了两遍，同样结果，请测试

**Comment by iwestlin** [comment]
你好，多谢反馈。

测试确实如此，已经更新代码修复了。

可以在项目文件夹下 `git pull` 获取最新代码，然后如果你之前运行了`pm2 start server.js`的话
需要`pm2 reload server`重启下进程

**Comment by cecaa1030** [comment]
已经验证解决了，感谢
