### ISSUE TITLE
bot机器人 里面输入/help 没反应

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#114]
请教下大佬：前面都配置好了，为什么bot里面打/help 没任何反应，config.js里面这么填写的：tg_whitelist:'name'，其中name是telegram app 设置里面设置的那个username

**Comment by iwestlin** [comment]
填 tg_whilelist: ['username'],

必须有英文中括号，改完以后 pm2 reload server 生效

**Comment by jason8303** [comment]
已解决，谢谢。
