### ISSUE TITLE
最新版输出日志不会自动换行，不利于实时查看拷贝进度，希望修复一下

### ISSUE THREAD

**Issue by wnbh** [iwestlin/gd-utils#115]
const message = `${now} | 已获取对象 ${result.length} | 网络请求 进行中${limit.activeCount}/排队中${limit.pendingCount}`
少了一个换行符号

**Comment by iwestlin** [comment]
?它会实时变动的啊

之前是会换行的，有人提意见说日志太多会埋没报错信息，就改成了实时变动的

**Comment by wnbh** [comment]
我用colab没有实时移动 如果能实时移动也行

**Comment by iwestlin** [comment]
你去colab版的仓库提issue吧
https://github.com/iwestlin/gd-utils/blob/faf7e7cb49b42a65bd60ec48b4e7005323d7e14e/src/gd.js#L844
只需要这样改成 `if (false) {`
