### ISSUE TITLE
关于检测sa的脚本validate-sa.js的一些问题

### ISSUE THREAD

**Issue by CruiseTian** [iwestlin/gd-utils#116]
最近添加了一些sa，有一些是还没有权限的，所以想要检测一下，可是今天运行脚本却根本检测不出来无效的sa，运行截图如下
![](https://user-images.githubusercontent.com/50127078/87846000-33d47a00-c8ff-11ea-9f9e-f70d42e1652d.jpg)

**Comment by iwestlin** [comment]
你的脚本还没跑完吧？

**Comment by CruiseTian** [comment]
跑完过，也是这个结果，异常一直是0，最后也不会移动到invalid

**Comment by iwestlin** [comment]
你可以保留一个有效的一个无效的，其他sa临时移到别的地方，然后再试试？

要确保检查的是自己的目录ID啊，不是公开分享的

**Comment by iwestlin** [comment]
公开分享的目录任何sa都可以读的

**Comment by CruiseTian** [comment]
是我的目录id，你看它有效的数目也是正确的，就是无效不显示（正常+异常 != 已检测）

**Comment by iwestlin** [comment]
你可以在个人盘新建一个文件夹，然后选两个sa，把其中一个sa的client_email加入这个文件夹的共享中，然后检测这两个sa对这个目录的权限看看？

**Comment by CruiseTian** [comment]
好的，我试试

**Comment by iwestlin** [comment]
还有一种可能是你的请求没有发到Google服务器。。你的命令行能正常访问Google服务吗？

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/commit/44cceceac2dad9e9ed032384b67e2638461e23ac
我给失败的请求加了个输出，可以git pull更新下

**Comment by CruiseTian** [comment]
测试了4次，只有一次可以移动到invalid，总共有两个未授权的，也只移动了一个，下面是结果图
![](https://user-images.githubusercontent.com/50127078/87846323-a34b6900-c901-11ea-9785-7a97063ef88f.jpg)

**Comment by CruiseTian** [comment]
好的，我更新下，而且正常异常也不显示，不太懂到底是哪里出问题

**Comment by CruiseTian** [comment]
更新之后运行的结果，每个sa都报了您刚加的那个错
![](https://user-images.githubusercontent.com/50127078/87846360-e60d4100-c901-11ea-8010-86bf45af20ff.jpg)

**Comment by iwestlin** [comment]
> 正常异常也不显示

大概率是你的请求没发到Google。。

**Comment by iwestlin** [comment]
不对。。403说明到了啊

**Comment by iwestlin** [comment]
@CruiseTian 我又加了更详细点的报错信息，你能不能再更新下。。

**Comment by CruiseTian** [comment]
可以的，我试一试

**Comment by CruiseTian** [comment]
详细的报错信息，请您查看
![](https://user-images.githubusercontent.com/50127078/87846490-de01d100-c902-11ea-9aef-bb0b32da7260.jpg)

**Comment by CruiseTian** [comment]
好像明白了，没开api看起来

**Comment by iwestlin** [comment]
报错的意思好像是创建sa的project不存在……

validate-sa目前的逻辑是
- 成功读取到目录信息，判定为正常
- 读取目录时失败状态为400或者code为404，判定为异常

而403两者都不属于，所以正常/异常都是0

我再更新下代码，把403也判定为异常好了

**Comment by CruiseTian** [comment]
好的，感谢，我刚刚开了一个项目的API，那个项目就检测成功了，估计就是只用脚本生成并下载了sa，但是项目api没有开

**Comment by CruiseTian** [comment]
我觉得403应该就是项目没开Google drive api的问题，所以如果报403的话可以给个提示让看看api开没开？（只是个小建议）

**Comment by iwestlin** [comment]
403有很多可能的……
https://developers.google.com/drive/api/v3/handle-errors#resolve_a_403_error_usage_limit_exceeded
这里就列出里9种。。

**Comment by CruiseTian** [comment]
好吧，感谢大佬，我把这个issue关了啊
