### ISSUE TITLE
Colab 兼容问题  "检测到上次的复制记录，是否继续" 

### ISSUE THREAD

**Issue by cxumol** [iwestlin/gd-utils#118]
Colab 环境, 当出现以下消息时, 无法按照提示进行选择
```
? 检测到上次的复制记录，是否继续？ › - Use arrow-keys. Return to submit.
❯   Continue
    从上次中断的地方继续
    Restart
    Exit
```

Colab 可以手动输入, 所以, 建议增加手动输入选择项, 比如, 手动输入 `R` 或 `Restart` 以进入相应流程

**Comment by iwestlin** [comment]
这里有讨论，给出了解决方案：
https://github.com/iwestlin/gd-utils/issues/90#issuecomment-657540420

**Comment by cxumol** [comment]
建了个 Colab 兼容的分支 https://github.com/cxu-fork/gd-utils/tree/colab-prompt

根据 https://github.com/iwestlin/gd-utils/issues/90#issuecomment-657540420 https://github.com/iwestlin/gd-utils/issues/90#issuecomment-657532784
