### ISSUE TITLE
复制失败，失败消息：没有可用的SA帐号

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#119]
我800个有效SA，应该一天能拷贝585t，昨天只是拷贝了350t的文件，今天拷贝200多t的文件就出现了标题的提示。想请问下，这个是什么原因呢，另外SA账号每天拷贝限额750G的时间循环是怎么算的。是太平洋时间00点到24点，还是平移的方式，比如1号SA是23点用的，要到第二天23点以后再次生效，还是到当天00点以后（也就是一个小时以后）再次生效。
      另外一个问题请教下大佬：config.js里面 设置的 client_ID 和client_secret是什么作用？是谷歌的接口么？它与SA的关系可否用以下的比喻来解释：API接口相当于院子A的大门钥匙，SA相当于院子里面各个房间的钥匙。如果是这样的话，我config.js里面填写的是院子A的大门钥匙，而800个sa是不同API账户里面的不同项目生成的，相当于院子A、院子B。。。里面的房间钥匙，为什么这些钥匙对应的不同院子（院子A、B...）都能通过院子A的钥匙打开。
     第三个问题，config.js里面的refresh_token是通过rclone里面新建remote产生的，是否必填，这个东西是干什么的？有什么作用。
     本人小白一个，还望大佬扫盲，谢了。

**Comment by iwestlin** [comment]
流量不一定刚好用完的，比如一个sa用了740G的流量，它再复制一个11G的文件就失败了，然后会被剔除。

还有可能sa越来越少时，容易触发频率限制，也会被剔除。

client_id 是个人帐户的授权，refresh_token要和client_id配套的，具体可以看 https://github.com/iwestlin/gd-utils#%E4%B8%AA%E4%BA%BA%E5%B8%90%E5%8F%B7%E9%85%8D%E7%BD%AE
如果只用机器人可以不用管个人授权。

**Comment by iwestlin** [comment]
每个sa文件里有个client_email，如果你把这个email添加到团队盘的成员或群组里，sa就有了这个团队盘的权限

**Comment by jason8303** [comment]
明白 非常感谢

发自我的iPhone

**Comment by jason8303** [comment]
> 明白 非常感谢 发自我的iPhone
> […](#)
> 在 2020年7月18日，下午5:02，issue哥 ***@***.***> 写道： ﻿ 每个sa文件里有个client_email，如果你把这个email添加到团队盘的成员或群组里，sa就有了这个团队盘的权限 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

看了rclone的文档基本上清楚了。另外大神建议增加实时查询当前可用SA的数量和拷贝大小

**Comment by jason8303** [comment]
> > 明白 非常感谢 发自我的iPhone
> > […](#)
> > 在 2020年7月18日，下午5:02，issue哥 _**@**_.***> 写道： ﻿ 每个sa文件里有个client_email，如果你把这个email添加到团队盘的成员或群组里，sa就有了这个团队盘的权限 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 看了rclone的文档基本上清楚了。另外大神建议增加实时查询当前可用SA的数量和拷贝大小

这样可以做到心中有数
