### ISSUE TITLE
装nginx，端口23333，到文件统计就404页面

### ISSUE THREAD

**Issue by iYIJUN** [iwestlin/gd-utils#12]
![image](https://user-images.githubusercontent.com/63563377/85933195-ef108100-b906-11ea-85b9-5f744717c304.png)

**Comment by iwestlin** [comment]
nginx没有把流量转发到23333端口

看下这里的讨论：https://github.com/iwestlin/gd-utils/issues/9#issuecomment-650575507

**Comment by iYIJUN** [comment]
跟着大佬视频做下来还是会遇到各种，譬如nginx文件缺失等等，需要彻底卸载重装之类的，最后"Webhook is already set"的话新建个机器人试试吧
