### ISSUE TITLE
/bm 可以手动编辑么

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#120]
/bm 是否可以找到文件手动输入编辑
另外 大佬能否加入该功能，显示收藏夹内目录的文件数和大小。这样的话就方便的知道哪个盘剩多少空间。

**Comment by jason8303** [comment]
> /bm 是否可以找到文件手动输入编辑
> 另外 大佬能否加入该功能，显示收藏夹内目录的文件数和大小。这样的话就方便的知道哪个盘剩多少空间。
还有，这里面能不能加入一键备份的功能，比如A1 主盘，A2 A3.。。备份盘，A1内容一键备份到A2、A3...

**Comment by iwestlin** [comment]
bookmark可以手动编辑，它是gdurl.sqlite里的bookmark这张表，可以用很多开源的sqlite管理软件打开编辑

或者也可以用我提供的工具 `bookmark.js`，可以 `node bookmark.js -h`看使用说明。

> 显示收藏夹内目录的文件数和大小

这个很难做到实时的，只能每隔一段时间刷新统计一次，会比较消耗性能，也容易触发频率限制

> 能不能加入一键备份的功能

`./copy 团队盘1 团队盘2 -u -S -D` 这算不算一键备份。。

**Comment by jason8303** [comment]
第一个问题明白。谢谢
第二个问题 ./copy 可以实现，但是稍微麻烦一些。我的意思是能不能集成在机器人/bm里面，设置好后一键备份，比如A1到B1，A1到C1，...这样的话就方便一些，因为用的都是团队盘，不稳定，我这里备份盘就有4个。一个一个去输入代码备份还是比较繁琐。

**Comment by jason8303** [comment]
> 第一个问题明白。谢谢
> 第二个问题 ./copy 可以实现，但是稍微麻烦一些。我的意思是能不能集成在机器人/bm里面，设置好后一键备份，比如A1到B1，A1到C1，...这样的话就方便一些，因为用的都是团队盘，不稳定，我这里备份盘就有4个。一个一个去输入代码备份还是比较繁琐。

比如我点击A1备份按键后，就会自动备份B1、C1、D1...,点击A2备份，就会自动同步到B2、C2、D2...

**Comment by jason8303** [comment]
> > 第一个问题明白。谢谢
> > 第二个问题 ./copy 可以实现，但是稍微麻烦一些。我的意思是能不能集成在机器人/bm里面，设置好后一键备份，比如A1到B1，A1到C1，...这样的话就方便一些，因为用的都是团队盘，不稳定，我这里备份盘就有4个。一个一个去输入代码备份还是比较繁琐。
> 
> 比如我点击A1备份按键后，就会自动同步到B1、C1、D1...,点击A2备份，就会自动同步到B2、C2、D2...
由于几个盘大部分内容基本一样，只是同步新增的内容，所以一次同步到几个盘 SA应该也够用

**Comment by iwestlin** [comment]
我觉得你更适合搞一个定时任务，每天凌晨定时备份这种……

我刚给 ./copy 加了个 `-y` 选项，表示如果检测到之前的复制记录，不询问直接继续上次的进度。

所以可以这么写定时任务的脚本：
```bash
cd path-to-gd-utils
./copy 团队盘A1 团队盘B1 -S -u -D -y
./copy 团队盘A1 团队盘C1 -S -D -y
```
`-u`只需要第一条加上，后续的会用到前面的缓存

**Comment by jason8303** [comment]
> 我觉得你更适合搞一个定时任务，每天凌晨定时备份这种……
> 
> 我刚给 ./copy 加了个 `-y` 选项，表示如果检测到之前的复制记录，不询问直接继续上次的进度。
> 
> 所以可以这么写定时任务的脚本：
> 
> ```shell
> cd path-to-gd-utils
> ./copy 团队盘A1 团队盘B1 -S -u -D -y
> ./copy 团队盘A1 团队盘C1 -S -D -y
> ```
> 
> `-u`只需要第一条加上，后续的会用到前面的缓存

大神，这个应该可以完美解决。定时任务使用crontab弄吧？

**Comment by iwestlin** [comment]
是的，你可以把脚本保存到一个.sh文件里，然后crontab -e设置定时运行这个脚本

**Comment by jason8303** [comment]
> 是的，你可以把脚本保存到一个.sh文件里，然后crontab -e设置定时运行这个脚本
明白，谢谢

**Comment by jason8303** [comment]
> bookmark可以手动编辑，它是gdurl.sqlite里的bookmark这张表，可以用很多开源的sqlite管理软件打开编辑
> 
> 或者也可以用我提供的工具 `bookmark.js`，可以 `node bookmark.js -h`看使用说明。
> 
> > 显示收藏夹内目录的文件数和大小
> 
> 这个很难做到实时的，只能每隔一段时间刷新统计一次，会比较消耗性能，也容易触发频率限制
> 
> > 能不能加入一键备份的功能
> 
> `./copy 团队盘1 团队盘2 -u -S -D` 这算不算一键备份。。

我手动编辑了bm.json,又导入进去，reload server，但是还是在bot里面/bm 收藏夹还是没有变化哦

**Comment by jason8303** [comment]
> > bookmark可以手动编辑，它是gdurl.sqlite里的bookmark这张表，可以用很多开源的sqlite管理软件打开编辑
> > 或者也可以用我提供的工具 `bookmark.js`，可以 `node bookmark.js -h`看使用说明。
> > > 显示收藏夹内目录的文件数和大小
> > 
> > 
> > 这个很难做到实时的，只能每隔一段时间刷新统计一次，会比较消耗性能，也容易触发频率限制
> > > 能不能加入一键备份的功能
> > 
> > 
> > `./copy 团队盘1 团队盘2 -u -S -D` 这算不算一键备份。。
> 
> 我手动编辑了bm.json,又导入进去，reload server，但是还是在bot里面/bm 收藏夹还是没有变化哦

编辑后，导入数据库，删掉bm.json,再导出，又变成原来的样子。

**Comment by iwestlin** [comment]
@jason8303 你是不是直接修改的alias啊？
bookmark.js本来是设计成用来将收藏记录导入空数据库中的，它的逻辑是这样的：

根据alias搜索bookmark这张表，如果找到记录，那么更新target值；
如果没找到相同的alias，就会新建一条记录，插入你设置的alias和target。

所以如果你是修改了别名的话，它会新建一条记录，而不是修改之前的。
如果要修改别名，建议用机器人 unset 原来的记录，再set新的

**Comment by jason8303** [comment]
> @jason8303 你是不是直接修改的alias啊？
> bookmark.js本来是设计成用来将收藏记录导入空数据库中的，它的逻辑是这样的：
> 
> 根据alias搜索bookmark这张表，如果找到记录，那么更新target值；
> 如果没找到相同的alias，就会新建一条记录，插入你设置的alias和target。
> 
> 所以如果你是修改了别名的话，它会新建一条记录，而不是修改之前的。
> 如果要修改别名，建议用机器人 unset 原来的记录，再set新的
crotab e 我是设置的这样：*/1 * * * * /root/gd-utils/filebackup.sh 进行测试，每隔一分钟执行一次，没有成功

**Comment by iwestlin** [comment]
你的 `filebackup.sh` 有没有
```bash
chmod +x filebackup.sh
```
？

**Comment by jason8303** [comment]
> 你的 `filebackup.sh` 有没有
> 
> ```shell
> chmod +x filebackup.sh
> ```
> 
> ？

cd /root/gd-utils
./copy 1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf 0AKO3jSVEENnjUk9P4A -S -u -D -y
./copy 1wyXHGkA3wORqoeB2FpPr4M62Jfn8Yjzf 0AE00lR6cMl71Uk9P4A -S -D -y

**Comment by jason8303** [comment]
> 你的 `filebackup.sh` 有没有
> 
> ```shell
> chmod +x filebackup.sh
> ```
> 
> ？

没有，我试试看

**Comment by iwestlin** [comment]
chmod +x 是赋予文件执行权限的，如果不加是不能直接 ./filename.sh 运行的。。

还有1分钟一次肯定不行的，如果是全盘复制的话，程序需要很长时间才能获取到所有文件的信息，然后如果有新增的还会开始拷贝，1分钟肯定完成不了的

然后上个任务还没完成，下一分钟又开始，没几分钟服务器就不行了……

**Comment by jason8303** [comment]
> chmod +x 是赋予文件执行权限的，如果不加是不能直接 ./filename.sh 运行的。。
> 
> 还有1分钟一次肯定不行的，如果是全盘复制的话，程序需要很长时间才能获取到所有文件的信息，然后如果有新增的还会开始拷贝，1分钟肯定完成不了的
> 
> 然后上个任务还没完成，下一分钟又开始，没几分钟服务器就不行了……

我是测试文件，里面没有文件，只有一个test文件夹，我在命令行执行没问题，但是自动执行不行。我刚加了权限./filename.sh

**Comment by jason8303** [comment]
> chmod +x 是赋予文件执行权限的，如果不加是不能直接 ./filename.sh 运行的。。
> 
> 还有1分钟一次肯定不行的，如果是全盘复制的话，程序需要很长时间才能获取到所有文件的信息，然后如果有新增的还会开始拷贝，1分钟肯定完成不了的
> 
> 然后上个任务还没完成，下一分钟又开始，没几分钟服务器就不行了……

在命令行执行./filename.sh 没问题，自动执行没反应

**Comment by iwestlin** [comment]
> 自动执行没反应

没反应是指命令行没有输出？
crontab默认是不会输出到命令行的啊，你可以在文件夹里新建一个文件，看会不会复制过去

**Comment by jason8303** [comment]
> > 自动执行没反应
> 
> 没反应是指命令行没有输出？
> crontab默认是不会输出到命令行的啊，你可以在文件夹里新建一个文件，看会不会复制过去

我在文件夹看的，没有。我的crontab e是:*/1 * * * * /root/gd-utils/filebackup.sh

**Comment by iwestlin** [comment]
```
*/1 * * * * sh /root/gd-utils/filebackup.sh
```
这样呢？

**Comment by jason8303** [comment]
> ```
> */1 * * * * sh /root/gd-utils/filebackup.sh
> ```
> 
> 这样呢？

还是不行

**Comment by iwestlin** [comment]
改成
```
node ./copy 团队盘A1 团队盘B1 -S -u -D -y
node ./copy 团队盘A1 团队盘C1 -S -D -y
```
这样呢。。

**Comment by iwestlin** [comment]
我估计是crontab找不到`node`的路径，如果上面还不行，先`which node`看看，然后把`node`换成它的绝对路径

**Comment by jason8303** [comment]
root@ubuntu:~/gd-utils# which node
/www/server/nvm/versions/node/v12.18.2/bin/node

怎么换呢 是换到filename.sh里面么

**Comment by iwestlin** [comment]
是啊
```bash
cd /root/gd-utils
/www/server/nvm/versions/node/v12.18.2/bin/node ./copy 1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf 0AKO3jSVEENnjUk9P4A -S -u -D -y
```

**Comment by jason8303** [comment]
> 是啊
> 
> ```shell
> cd /root/gd-utils
> /www/server/nvm/versions/node/v12.18.2/bin/node ./copy 1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf 0AKO3jSVEENnjUk9P4A -S -u -D -y
> ```

finally!!! 可以了，感谢大神

**Comment by jason8303** [comment]
> > 是啊
> > ```shell
> > cd /root/gd-utils
> > /www/server/nvm/versions/node/v12.18.2/bin/node ./copy 1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf 0AKO3jSVEENnjUk9P4A -S -u -D -y
> > ```
> 
> finally!!! 可以了，感谢大神

但是很奇怪，只拷贝了文件夹，文件没有拷贝，命令行也一样

**Comment by iwestlin** [comment]
`-D`这个参数的意思是
>   do not create new root, 不在目的地创建同名文件夹，直接将源文件夹中的文件原样复制到目的文件夹中'
所以上面那行命令会把`1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf`中的文件直接拷贝到` 0AKO3jSVEENnjUk9P4A`下，你检查下是不是这样？

**Comment by jason8303** [comment]
> `-D`这个参数的意思是
> 
> > do not create new root, 不在目的地创建同名文件夹，直接将源文件夹中的文件原样复制到目的文件夹中
> 
> 所以上面那行命令会把`1wyXH3kA3wORq3eBuFpPr4M65Jfn8Yjzf`中的文件直接拷贝到` 0AKO3jSVEENnjUk9P4A`下，你检查下是不是这样？

试了一下，好像不行
还有个问题。我在源文件夹下 删除一个子文件夹，目标文件夹里面没有删除；我在目标文件夹删除一个文件夹，再次同步的时候也不会从源文件夹备份过去

**Comment by iwestlin** [comment]
本来就是这样的……这是个转存工具，**不是同步工具**。
gd-utils把拷贝记录都存在本地了，这样就可以不用向Google服务器查询某文件是否拷贝过。

所以它不会删除目标文件夹里的文件，也不会再次拷贝被手动删除的文件

**Comment by jason8303** [comment]
> 本来就是这样的……这是个转存工具，**不是同步工具**。
> gd-utils把拷贝记录都存在本地了，这样就可以不用向Google服务器查询某文件是否拷贝过。
> 
> 所以它不会删除目标文件夹里的文件，也不会再次拷贝被手动删除的文件

明白，但是我在源文件夹新建一个文件夹放入一个文件，在拷贝的时候，文件夹拷贝过去了，但是里面的文件没有拷贝过去。源文件夹根目录放一个文件就拷贝过去了

**Comment by iwestlin** [comment]
可能是Google服务器没有更新过来，新建的文件夹有时会出现这种问题

**Comment by jason8303** [comment]
> 可能是Google服务器没有更新过来，新建的文件夹有时会出现这种问题

大神，你觉得拷贝用gd-utils，同步用rclone是不是好一些

**Comment by iwestlin** [comment]
我只用过rclone的转存功能，不确定它的同步功能能不能满足你的需求，你可以都试试啊，还有几个fork版本的，gclone什么的，比原版快不少

**Comment by jason8303** [comment]
> 我只用过rclone的转存功能，不确定它的同步功能能不能满足你的需求，你可以都试试啊，还有几个fork版本的，gclone什么的，比原版快不少

我之前用的gclone，速度慢，所以才用大神的gd-utils。gclone会扫描所有的文件。估计可以实现同步的功能，我试试看行不。

**Comment by iwestlin** [comment]
还有个更快的fclone，不过好像要很多sa

**Comment by jason8303** [comment]
> 还有个更快的fclone，不过好像要很多sa
哦，我有800个SA,不知道够不够
