### ISSUE TITLE
数据库问题

### ISSUE THREAD

**Issue by horryruo** [iwestlin/gd-utils#121]
数据库文件太大，删除替换了之后，文件检查都提示‘统计失败：no such table: gd’，强制刷新也没反应，复制也没反应，/task也没反应

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/gdurl.sqlite
你用的是这个文件吗？
是手动下载替换的还是直接 `wget https://github.com/iwestlin/gd-utils/blob/master/gdurl.sqlite`？
直接wget的话好像会下载到网页

**Comment by iwestlin** [comment]
替换数据库的时候，最好先 pm2 stop server停掉进程，替换完成后再 pm2 reload server重启进程

**Comment by horryruo** [comment]
是的，先停止了删除了再上传的，也是先电脑下载的文件再ftp上传的，今天只能重新删除了项目再clone部署了一次，才正常，希望后续有个数据库超过100m自动删除的功能

**Comment by iwestlin** [comment]
清空gd表的数据其实只要两行：
```js
const { db } = require('./db')
db.prepare('delete from gd').run()
```
但是我试了下删掉了一千多条数据，数据库文件大小却没有变化……不知道是不是依赖的问题

**Comment by iwestlin** [comment]
找到原因了：https://stackoverflow.com/questions/2143800/change-sqlite-file-size-after-delete-from-table

刚新加了一个脚本：https://github.com/iwestlin/gd-utils/blob/master/clear-db.js

只要运行 `node clear-db.js` 就可以删除所有获取的文件信息（但会保留拷贝记录和bookmark）同时减小数据库文件大小了

**Comment by horryruo** [comment]
好的，感谢大大
