### ISSUE TITLE
建议 升级「识别转发google drive链接 」功能

### ISSUE THREAD

**Issue by YuanHsing** [iwestlin/gd-utils#122]
[2020-07-01]
支持识别转发的 @gdurl 频道消息中的google drive链接

###

建议 升级成「可以 识别"所有"转发的google drive链接」
这样子我的 telegram_gcloner bot就可以解除安装了！

**Comment by iwestlin** [comment]
刚更新了代码，我试了下几种类型的转发消息，都可以识别了

**Comment by YuanHsing** [comment]
感谢大佬
试了几个常用的频道
完全可以正常运作

telegram_gcloner 仓库确定！
