### ISSUE TITLE
复制过程中不时会报错 是请求并发数调太高的问题么？

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gd-utils#126]
`{"error":{"errors":[{"domain":"
usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceede
d. Rate of requests for user exceed configured project quota. You may consider r
e-evaluating expected per-user traffic to the API and adjust project quota limit
s accordingly. You may monitor aggregate quota usage and adjust limits in the AP
I Console: https://console.developers.google.com/apis/api/drive.googleapis.com/q
uotas?project=365835729405","extendedHelp":"https://console.developers.google.co
m/apis/api/drive.googleapis.com/quotas?project=365835729405"}],"code":403,"messa
ge":"User Rate Limit Exceeded. Rate of requests for user exceed configured proje
ct quota. You may consider re-evaluating expected per-user traffic to the API an
d adjust project quota limits accordingly. You may monitor aggregate quota usage
 and adjust limits in the API Console: https://console.developers.google.com/api
s/api/drive.googleapis.com/quotas?project=365835729405"}}
`

**Comment by iwestlin** [comment]
`userRateLimitExceeded` 一般是当日转存流量超过750G触发的

你是用sa操作的吗？如果命令行最后加了个参数 `-S`，程序会使用sa授权进行操作，如果某个sa流量超了，会自动剔除掉此sa并重试请求

**Comment by kingofotaku** [comment]
> `userRateLimitExceeded` 一般是当日转存流量超过750G触发的
> 
> 你是用sa操作的吗？如果命令行最后加了个参数 `-S`，程序会使用sa授权进行操作，如果某个sa流量超了，会自动剔除掉此sa并重试请求

是的 正如你所说 可是他出现的频率高得看起来不像是切换账号才有的

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-02-%E5%85%B3%E4%BA%8E%E6%B2%A1%E6%9C%89%E5%8F%AF%E7%94%A8%E7%9A%84sa%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF

**Comment by kingofotaku** [comment]
> https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-02-%E5%85%B3%E4%BA%8E%E6%B2%A1%E6%9C%89%E5%8F%AF%E7%94%A8%E7%9A%84sa%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF

之前看到了 已pull最新代码 感谢作者持续改进
