### ISSUE TITLE
关于refresh_token

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#127]
大佬，一个问题请教
rclone下挂载不同团队盘会产生不同的refresh_token,
在config.js中要填写哪一个，还是随便填哪个都可以呢?或者也可以不填呢？
这个refresh_token是对应某一个团队盘么？
另外在rclone里面它还一天后失效。
client_id client_secret 我大概明白，就是谷歌账号的一个API接口，但是这个refresh_token到底有什么用？到底是个什么东西，想不明白。

还望大神赐教

**Comment by jason8303** [comment]
> 大佬，一个问题请教
> rclone下挂载不同团队盘会产生不同的refresh_token,
> 在config.js中要填写哪一个，还是随便填哪个都可以呢?或者也可以不填呢？
> 这个refresh_token是对应某一个团队盘么？
> 另外在rclone里面它还一天后失效。
> client_id client_secret 我大概明白，就是谷歌账号的一个API接口，但是这个refresh_token到底有什么用？到底是个什么东西，想不明白。
> 
> 还望大神赐教

client_id和client_secret是开放API接口KEY，这个refresh_token应该是刷新账户的access_token的，这样的话config.js里面是不是不用填refresh_token了，因为用的是sa。

**Comment by iwestlin** [comment]
refresh_token是个人账户的授权，如果有sa的话可以不填。

tg机器人所有操作默认都使用sa授权，命令行操作需要在命令后加一个 `-S` 表示指定使用sa授权。

如果有操作个人盘文件的需求，有两种方法，一是手动将个人盘的目录分享给sa所在的群组，另一种是配置个人授权。
配置个人授权时最好用自己的client_id和client_secret，readme里有提到过获取的具体方法

**Comment by jason8303** [comment]
那client_id和client_secret是团队账号的授权么？
关于pm2 l出现这么个问题，如下图，里面name space、watching等几项，我把sites-available下面的文件都删掉了。
![image](https://user-images.githubusercontent.com/47917048/88258269-4f21f980-ccf2-11ea-99aa-f030e64d0b44.png)

**Comment by jason8303** [comment]
nginx里面的sites-available和sites-enabled怎么用，只要将web配置文件放在sites-enabled下面应该就可以了吧。

**Comment by jason8303** [comment]
![image](https://user-images.githubusercontent.com/47917048/88258469-d1122280-ccf2-11ea-856e-7b787ffa7e09.png)
按照你的视频教程应该是这样的

**Comment by jason8303** [comment]
server {
    listen 80;
    listen [::]:80;
    server_name bot2.ljhcsu.cf;
    return 302 https://$server_name$request_uri;
}


server {

    # SSL configuration
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl on;
    ssl_certificate /etc/ssl/certs/cert.pem;
    ssl_certificate_key /etc/ssl/private/key.pem;
    server_name bot2.ljhcsu.cf;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:23333/;
  }
}
大神，你看我的nginx配置文件对不对，有没有啥问题

**Comment by jason8303** [comment]
![image](https://user-images.githubusercontent.com/47917048/88259931-ec326180-ccf5-11ea-98f6-a87ea5d0430b.png)
23333 23334都出现这个错误

**Comment by jason8303** [comment]
> refresh_token是个人账户的授权，如果有sa的话可以不填。
> 
> tg机器人所有操作默认都使用sa授权，命令行操作需要在命令后加一个 `-S` 表示指定使用sa授权。
> 
> 如果有操作个人盘文件的需求，有两种方法，一是手动将个人盘的目录分享给sa所在的群组，另一种是配置个人授权。
> 配置个人授权时最好用自己的client_id和client_secret，readme里有提到过获取的具体方法

👌谢谢
