### ISSUE TITLE
能否在windows 10 PowerShell下运行

### ISSUE THREAD

**Issue by wangts** [iwestlin/gd-utils#13]
大佬你好，请问这个程序只能在服务器环境下运行吗？ 我在windows 10 PowerShell下输入copy -h 命令，显示
Copy-Item : A parameter cannot be found that matches parameter name 'h'.
At line:1 char:6
+ copy -h
+      ~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by iwestlin** [comment]
命令前面需要加个 `./` 告诉命令行要执行的是当前目录下的文件

比如 `./copy -h` 意思是执行当前目录下的 `copy` 文件

如果不加，那命令行就以为你在调用系统自带的 copy 命令了

**Comment by wangts** [comment]
感谢您的回复。上边那个命令我试了。显示下边的错误信息。
Program 'copy' failed to run: No application is associated with the specified file for this operationAt line:1 char:1
+ ./copy -h
+ ~~~~~~~~~.
At line:1 char:1
+ ./copy -h
+ ~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by iwestlin** [comment]
你安装好nodejs了吗 

`node -v` 命令返回什么？

**Comment by wangts** [comment]
我按顺序安装了所有文件。显示版本v12.18.1。我的文件目录如下。

![gd-utils](https://user-images.githubusercontent.com/15067156/85935181-d5961780-b8bb-11ea-9bd7-3cd097e5fce9.jpg)

**Comment by wangts** [comment]
sa 拷贝了一百个。
![sa](https://user-images.githubusercontent.com/15067156/85935208-463d3400-b8bc-11ea-9246-63633d5569e2.jpg)

**Comment by iwestlin** [comment]
> sa 拷贝了一百个。
> ![sa](https://user-images.githubusercontent.com/15067156/85935208-463d3400-b8bc-11ea-9246-63633d5569e2.jpg)

那输入 `node count -h` 也报错吗

**Comment by wangts** [comment]
这个命令没问题。显示如下：
用法: ./count <目录ID> [options]

Options:
  --version              Show version number                           [boolean]
  -u, --update           强制从线上获取信息(无视是否存在本地缓存)
  -N, --not_teamdrive    如果不是团队盘链接，可以加上此参数以提高接口查询效率，
                         降低延迟。如果要统计的是个人盘且./sa目录下的service
                         account没有相关权限，请确保加上此参数以使用个人的auth信
                         息进行查询
  -S, --service_account  指定使用service
                         account进行统计，前提是必须在sa目录下放置SA json文件
  -s, --sort             统计结果排序方法，可选值 name 或
                         size，不填则默认根据文件数量逆序排列
  -t, --type             统计结果输出类型，可选值
                         html/json/all，all表示输出所有文件json数据，最好搭配 -o
                         使用。不填则默认输出命令行表格
  -o, --output           统计结果输出文件，适合搭配 -t 使用
  -h, --help             Show help                                     [boolean]

Examples:
  ./count                                   获取
  1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75         https://drive.google.com/drive/folde
                                            rs/1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75
                                            内包含的的所有文件的统计信息
  ./count root -s size -t html -o out.html  获取个人盘根目录统计信息，结果以HTML
                                            表格输出，根据总大小逆序排列，保存到
                                            本目录下的out.html文件中（不存在则新
                                            建，存在则覆盖）
  ./count root -s name -t json -o out.json  获取个人盘根目录统计信息，结果以JSON
                                            格式输出，根据文件扩展名排序，保存到
                                            本目录下的out.json文件中
  ./count root -t all -o all.json           获取个人盘根目录统计信息，将所有文件
                                            信息（包括文件夹）以JSON格式输出，保
                                            存到本目录下的all.json文件中

**Comment by wangts** [comment]
node copy -h 也没问题。显示如下：
用法: ./copy <source id> <target id> [options]
target id可选，不填则使用config.js里的DEFAULT_TARGET

Options:
  --version              Show version number                           [boolean]
  -u, --update           不使用本地缓存，强制从线上获取源文件夹信息
  -f, --file             复制单个文件
  -n, --name             给目标文件夹重命名，不填则保留原始目录名
  -N, --not_teamdrive    如果不是团队盘链接，可以加上此参数以提高接口查询效率，
                         降低延迟
  -s, --size             不填默认拷贝全部文件，如果设置了这个值，则过滤掉小于这
                         个size的文件，必须以b结尾，比如10mb
  -S, --service_account  指定使用service account进行操作，前提是必须在 ./sa
                         目录下放置json授权文件，请确保sa帐号拥有操作权限。
  -h, --help             Show help                                     [boolean]

**Comment by iwestlin** [comment]
> 这个命令没问题。显示如下：
> 用法: ./count <目录ID> [options]
> 
> Options:
> --version Show version number [boolean]
> -u, --update 强制从线上获取信息(无视是否存在本地缓存)
> -N, --not_teamdrive 如果不是团队盘链接，可以加上此参数以提高接口查询效率，
> 降低延迟。如果要统计的是个人盘且./sa目录下的service
> account没有相关权限，请确保加上此参数以使用个人的auth信
> 息进行查询
> -S, --service_account 指定使用service
> account进行统计，前提是必须在sa目录下放置SA json文件
> -s, --sort 统计结果排序方法，可选值 name 或
> size，不填则默认根据文件数量逆序排列
> -t, --type 统计结果输出类型，可选值
> html/json/all，all表示输出所有文件json数据，最好搭配 -o
> 使用。不填则默认输出命令行表格
> -o, --output 统计结果输出文件，适合搭配 -t 使用
> -h, --help Show help [boolean]
> 
> Examples:
> ./count 获取
> 1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75 https://drive.google.com/drive/folde
> rs/1ULY8ISgWSOVc0UrzejykVgXfVL_I4r75
> 内包含的的所有文件的统计信息
> ./count root -s size -t html -o out.html 获取个人盘根目录统计信息，结果以HTML
> 表格输出，根据总大小逆序排列，保存到
> 本目录下的out.html文件中（不存在则新
> 建，存在则覆盖）
> ./count root -s name -t json -o out.json 获取个人盘根目录统计信息，结果以JSON
> 格式输出，根据文件扩展名排序，保存到
> 本目录下的out.json文件中
> ./count root -t all -o all.json 获取个人盘根目录统计信息，将所有文件
> 信息（包括文件夹）以JSON格式输出，保
> 存到本目录下的all.json文件中

那就是系统兼容问题了。

你可以把所有类似 `./count ...` 的命令都换成 `node count ...`，效果是一样都

**Comment by wangts** [comment]
看来我得在命令前边加 node。我试着考一个文件夹。谢谢。

**Comment by iwestlin** [comment]
> 看来我得在命令前边加 node。我试着考一个文件夹。谢谢。

好的，还要注意下命令行需要配置代理地址

**Comment by wangts** [comment]
十分感谢大佬。这次命令正常执行了。大佬太厉害了。还有个问题，可以把PARALLEL_LIMIT = 20增加到100吗？我一组里有100个service accounts。

**Comment by iwestlin** [comment]
> 十分感谢大佬。这次命令正常执行了。大佬太厉害了。还有个问题，可以把PARALLEL_LIMIT = 20增加到100吗？我一组里有100个service accounts。

瓶颈不在sa的数量上，而在于网络环境，建议你一点点增加试试……

我自己的使用情况，20在本地挂代理稍微有点多，在服务器就没压力了
