### ISSUE TITLE
aria2问题

### ISSUE THREAD

**Issue by wnbh** [iwestlin/gd-utils#133]
大佬aria2.js 命令
运行了一下得到了很多链接，随意打开一个链接出现了以下问题
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

**Comment by iwestlin** [comment]
链接需要特定的headers才能下载的

生成的文件里第一行是这样的
```
# aria2c -c -s10 -k1M --enable-rpc=false --header "Authorization: Bearer ...
```
你把它复制到命令行就能直接运行了
（前提是命令行能正常访问Google代理且安装了 `aria2c`）

还有个问题是这个 header 一个小时后就会过期，如果下载时间超过了一个小时，需要中断后再重复一遍操作（会跳过已下载的文件）

**Comment by wnbh** [comment]
那如果是用本地AriaNg下载怎么弄

**Comment by iwestlin** [comment]
那个是gui吧，不太好批量操作
不过应该可以通过json-rpc批量添加任务
没研究过

命令行已经很方便了啊，一行命令下载整个目录，还能保留目录结构

**Comment by wnbh** [comment]
Windows命令行好像不行

**Comment by iwestlin** [comment]
https://drive.google.com/file/d/1lzN7R9Klw66C5UttUUDN3_EsN3pNs62q/view

我做了份录屏

**Comment by wnbh** [comment]
感谢 明白了
