### ISSUE TITLE
机器人报错:没有可用的sa账号

### ISSUE THREAD

**Issue by wangzhijie0602** [iwestlin/gd-utils#137]
复制一个20万文件的文件夹，中间机器人报错：没有可用的sa账号，重启pm2后就正常了
pm2错误日志：
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
复制失败 1roGTt7T4_6GfRuYArVp-Too_JObB_esL --> 0AL3BdkRGJT8dUk9PVA
Error: 没有可用的SA帐号
    at get_sa_token (/root/gd-utils/src/gd.js:349:9)
    at copy_file (/root/gd-utils/src/gd.js:626:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}

**Comment by iwestlin** [comment]
` 1roGTt7T4_6GfRuYArVp-Too_JObB_esL`这个资源有毒。。

参考：https://github.com/iwestlin/gd-utils/issues/134#issuecomment-666115966

**Comment by wangzhijie0602** [comment]
谢谢
