### ISSUE TITLE
统计问题

### ISSUE THREAD

**Issue by wnbh** [iwestlin/gd-utils#139]
07:02:59 | 已获取对象 42973 | 网络请求 进行中16/排队中0
 07:03:00 | 已获取对象 43007 | 网络请求 进行中15/排队中0
 07:03:01 | 已获取对象 43104 | 网络请求 进行中11/排队中0
 07:03:02 | 已获取对象 43205 | 网络请求 进行中8/排队中0
 07:03:03 | 已获取对象 43206 | 网络请求 进行中7/排队中0
 07:03:04 | 已获取对象 43206 | 网络请求 进行中7/排队中0
 07:03:05 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:06 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:07 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:08 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:09 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:10 | 已获取对象 43383 | 网络请求 进行中2/排队中0
 07:03:11 | 已获取对象 43430 | 网络请求 进行中1/排队中0
 07:03:12 | 已获取对象 43430 | 网络请求 进行中1/排队中0
最后一点怎么还用了这么久，记得先前的版本一下就完了，并行数100，SA1100个，总用时有一半都花在了最后这一点，并行数调低了，最后这一点用的时间就更多了

**Comment by iwestlin** [comment]
程序在成功读取某个目录所有文件后才会更新获取对象数。如果某个目录文件特别多，那么每次最多获取1000个文件数，如果没读取完，google会返回一个nextpagetoken，用这个token再次请求才能拿到下一页的数据，所以无法用并行请求加快速度。

根据我的经验，如果某个目录下文件数特别多，往往需要20秒以上才能获取一页也就是1000个文件。

所以如果遇到这种文件数特别多的目录，建议config.js里增大超时时间

wnbh <notifications@github.com> 于 2020年7月30日周四 15:24写道：

**Comment by wnbh** [comment]
还是不行，最后一点还是慢，前面4秒统计了3万文件，后面30秒才统计15000文件

**Comment by wnbh** [comment]
试了几个链接，每次都是在排队中为0的时候就慢下来了

**Comment by wnbh** [comment]
经过不断测试，发现是文件夹的问题，把文件移入到新的文件夹就不会出现这种情况，有一个问题就是，这么多文件夹，自己并不知道哪些文件夹会获取超时，所以建议在统计的时候增加一个检测文件夹获取超时，将这些文件夹的ID记录下来，自己重新将这些文件夹拷贝一次替换掉原来的就可以了，这个文件夹获取超时应该是谷歌自己的问题，因为我尝试着调低PAGE_SIZE这个参数，发现依旧获取超时，目前我也就只能想到把这些文件夹重拷一遍替换掉原来的

**Comment by iwestlin** [comment]
是有这个机制的：https://github.com/iwestlin/gd-utils/blob/a3b967a710a3255e44bc34877185200d97b5cf5a/src/gd.js#L238

如果有没读取完毕的目录，程序会打印它们的对应ID
命令行运行的时候会输出
机器人的话pm2 logs里也能看到

对于每个请求，默认都会有7次重试的机会，只有成功读取的文件夹其数据才会被记录到数据库中，如果没读取完毕是不会记录的。
所以如果你担心有目录没读取完，可以直接再重复一遍命令（都**不**需要加`-u`参数），程序会找到上次未读取完毕的目录进行请求

**Comment by wnbh** [comment]
哦 那理论上是不是可以调整最大超时时间来找出那些读取慢的文件夹，然后重新拷贝替换，下一次统计的时候就很快了
