### ISSUE TITLE
拷贝完文件夹后使用count对比，文件夹数量相差1

### ISSUE THREAD

**Issue by cecaa1030** [iwestlin/gd-utils#14]
源文件夹 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz 统计文件夹241
拷贝完之后使用count统计文件夹242

**Comment by iwestlin** [comment]
> 源文件夹 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz 统计文件夹241
> 拷贝完之后使用count统计文件夹242

出现多余的文件夹可能是某次创建文件夹的请求超时了，然后自动重试，但是超时的请求实际上被Google服务器收到并执行了，所以会多创建一个

可以利用 `./dedupe` 去重试试，`./dedupe -h`看使用说明

**Comment by cecaa1030** [comment]
我使用dedupe对目标文件夹去重，确实提示有一个文件夹重复，但是去重过程中提示权限不足，我使用的同一套SA进行的操作，命令行都带-S，SA肯定有目标文件夹的权限的

**Comment by iwestlin** [comment]
> 我使用dedupe对目标文件夹去重，确实提示有一个文件夹重复，但是去重过程中提示权限不足，我使用的同一套SA进行的操作，命令行都带-S，SA肯定有目标文件夹的权限的

你的sa是贡献者吧，需要是 内容管理者以上才能删除文件的

<img width="357" alt="截屏2020-06-28 下午2 18 13" src="https://user-images.githubusercontent.com/6235509/85939711-61568500-b94a-11ea-8d64-833e4de76a2b.png">

**Comment by iwestlin** [comment]
> > 我使用dedupe对目标文件夹去重，确实提示有一个文件夹重复，但是去重过程中提示权限不足，我使用的同一套SA进行的操作，命令行都带-S，SA肯定有目标文件夹的权限的
> 
> 你的sa是贡献者吧，需要是 内容管理者以上才能删除文件的
> 
> <img alt="截屏2020-06-28 下午2 18 13" width="357" src="https://user-images.githubusercontent.com/6235509/85939711-61568500-b94a-11ea-8d64-833e4de76a2b.png">

可能是必须为 manager，我不太确定如果sa是内容管理者有没有权限删除别的sa上传的文件

**Comment by cecaa1030** [comment]
我的SA加到了一个Group中，这个Group对我的Team Drive有Content Manager的权限，理论上是可以删除文件的

**Comment by iwestlin** [comment]
> 我的SA加到了一个Group中，这个Group对我的Team Drive有Content Manager的权限，理论上是可以删除文件的

你试试不要加 -S 参数呢

**Comment by cecaa1030** [comment]
我没有配置本地账户Token，全部都是用SA操作的

**Comment by iwestlin** [comment]
那试试改成manager呢？

**Comment by cecaa1030** [comment]
改成Manager确实可以删除了，但是Content Manager权限应该也是够的呀？是不是要查一下？我一般不给SA到Manager权限

**Comment by iwestlin** [comment]
> 改成Manager确实可以删除了，但是Content Manager权限应该也是够的呀？是不是要查一下？我一般不给SA到Manager权限

可能是因为普通权限的sa只能删除自己copy的文件，而调用dedupe的时候，使用的sa要删除的文件不一定是自己创建的。。

**Comment by cecaa1030** [comment]
https://support.google.com/drive/answer/7286514?visit_id=637042405228053249-956633332&p=team_drives&rd=1&authuser=1
这里写着：
Content manager: By default, can upload, edit, move, or delete all files.
应该是对所有文件都有删除权限的，这个真奇怪

**Comment by cecaa1030** [comment]
Manager和Content Manager的差别应该只是在前者可以管理member，对于文件的权限应该是一样的，这样一个能删除，一个不能就很奇怪了

**Comment by cecaa1030** [comment]
我查了API文档，因为你用的是delete请求，这个请求权限要求比较高，不进回收箱，所以确实需要Manager，rclone用的是update请求，把trashed属性改成了true，这样进回收箱，就不需要Manager权限，这个就看你的取舍了
建议：可以两个都实现，在config中可配置就完美了

**Comment by iwestlin** [comment]
> 我查了API文档，因为你用的是delete请求，这个请求权限要求比较高，不进回收箱，所以确实需要Manager，rclone用的是update请求，把trashed属性改成了true，这样进回收箱，就不需要Manager权限，这个就看你的取舍了
> 建议：可以两个都实现，在config中可配置就完美了

多谢啊，太感动了，终于有人帮我解答问题而不是生产问题了。。

**Comment by cecaa1030** [comment]
客气了，都期待着你的工具更加稳定成熟呢

**Comment by iwestlin** [comment]
> 我查了API文档，因为你用的是delete请求，这个请求权限要求比较高，不进回收箱，所以确实需要Manager，rclone用的是update请求，把trashed属性改成了true，这样进回收箱，就不需要Manager权限，这个就看你的取舍了
> 建议：可以两个都实现，在config中可配置就完美了

现在改成了 移动到回收站，只需要 content manager权限了
