### ISSUE TITLE
还是gd-utils最好用

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#140]
先后折腾过rclone gclone gd-utils 后来又转回gclone去实现备份功能，发现速度太太太慢了，根本不实用。还是gd-utils稳定，速度最快。顶一个。
小小的建议下，gd-utils如果可以加入真正的备份功能那就完美了。用crontab也行，但是就是备份源修改删除的部分不会在备份目标同样删除移动修改。大佬不知道gd-utils有没有可能实现这样的功能。

因为拷贝到团队盘的文件会比较乱，会做一定的整理，整理之后备份就会很麻烦。

**Comment by iwestlin** [comment]
有不少人提过这个需求 https://github.com/iwestlin/gd-utils/issues/117#issuecomment-660440132

这个其实就是sync功能，实现起来有点麻烦，而且我本人对这个没什么需求，所以一直没有动手。。

我提供下一种粗暴的实现思路，看有没有人愿意尝试实现，欢迎PR：
第一步，读取源文件夹(S)所有文件信息
第二步，根据源文件结构在目的地创建相同的文件夹(N)，保存目录ID映射关系
第三步，读取目标文件夹(D)所有文件信息
（这几步并不消耗sa的流量，比较适合目录不多的任务）
第四步，遍历保存下来的源文件夹所有文件，寻找目标文件夹中md5相同的文件，如果找到，将其移动（也不消耗sa流量）到对应的目录内（根据目录映射关系找对应的目录），同时比较名称是否相同，如果不同则重命名；如果没找到，则复制源文件到对应的目录
第五步，遍历操作完源文件夹所有文件后，删除原本存在的目标文件夹D

最终得到的文件夹N就和源文件夹S结构和内容完全一致了

**Comment by jason8303** [comment]
> 有不少人提过这个需求 https://github.com/iwestlin/gd-utils/issues/117#issuecomment-660440132
> 
> 
> 
> 这个其实就是sync功能，实现起来有点麻烦，而且我本人对这个没什么需求，所以一直没有动手。。
> 
> 
> 
> 我这里提供一种粗暴的实现思路，看有没有人愿意尝试实现，欢迎PR：
> 
> - 第一步，读取源文件夹(S)所有文件信息
> 
> - 第二步，根据源文件结构在目的地创建相同的文件夹(N)，保存目录ID映射关系
> 
> - 第三步，读取目标文件夹(D)所有文件信息
> 
> （这几步并不消耗sa的流量，比较适合目录不多的任务）
> 
> - 第四步，遍历保存下来的源文件夹所有文件，寻找目标文件夹D中md5相同的文件，如果找到，将其移动（也不消耗sa流量）到N中对应的目录内（根据目录映射关系找对应的目录），同时比较名称是否相同，如果不同则重命名；如果没找到，则复制源文件到对应的目录
> 
> - 第五步，遍历操作完源文件夹所有文件后，删除原本存在的目标文件夹D
> 
> 
> 
> 最终得到的文件夹N就和源文件夹S结构和内容完全一致了

大佬请问你的盘是正版G-suit么？如果不是的话，就不怕哪天挂了？我是白嫖的几个团盘，怕被删除了。所以急于做备份。想问的是大佬用的什么盘

**Comment by iwestlin** [comment]
是12刀的那个官方gsuite

**Comment by jason8303** [comment]
> 是12刀的那个官方gsuite

明白了，那个确实不需要备份。大佬土豪

**Comment by okaygh** [comment]
还在用gclone,什么时候更新后缀过滤就可以完全转过来了,话说你要快的话fclone和icopy更狠...

**Comment by jason8303** [comment]
> 是12刀的那个官方gsuite

大佬，你的gsuite是一个用户还是几个，如果一个用户的话官方网站说只能用1t的空间。

**Comment by iwestlin** [comment]
> > 是12刀的那个官方gsuite
> 
> 大佬，你的gsuite是一个用户还是几个，如果一个用户的话官方网站说只能用1t的空间。

1个用户啊，虽然官网确实是那么写的，但是很多人（包括我）亲测其实都有无限空间的……

**Comment by jason8303** [comment]
> > > 是12刀的那个官方gsuite
> > 
> > 
> > 大佬，你的gsuite是一个用户还是几个，如果一个用户的话官方网站说只能用1t的空间。
> 
> 1个用户啊，虽然官网确实是那么写的，但是很多人（包括我）亲测其实都有无限空间的……

哦，了解，这个有40w个文件限制么

**Comment by iwestlin** [comment]
> 这个有40w个文件限制么

个人盘没有，团队盘有，但是好像可以新建无数个团队盘

**Comment by jason8303** [comment]
> 还在用gclone,什么时候更新后缀过滤就可以完全转过来了,话说你要快的话fclone和icopy更狠...

我用gclone sync不同团队盘之间同步，为什么速度巨慢，要2万天，是什么情况哦
![image](https://user-images.githubusercontent.com/47917048/89012057-131b1400-d344-11ea-9202-727435e7c9ad.png)

**Comment by iwestlin** [comment]
...2w是2 weeks的意思，不是两万天。。

**Comment by jason8303** [comment]
> > 这个有40w个文件限制么
> 
> 个人盘没有，团队盘有，但是好像可以新建无数个团队盘

哦，明白

**Comment by jason8303** [comment]
> ...2w是2 weeks的意思，不是两万天。。

哈哈哈哈，好吧。但是2周也是不太可能的情况，也没多大。这个速度也不正常把？gclone慢是慢，但是也不至于这么慢把

**Comment by jason8303** [comment]
> > ...2w是2 weeks的意思，不是两万天。。
> 
> 哈哈哈哈，好吧。但是2周也是不太可能的情况，也没多大。这个速度也不正常把？gclone慢是慢，但是也不至于这么慢把

感觉好像是实体盘间对拷的速度，不是拷贝链接。
