### ISSUE TITLE
关于-u -y同时用

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#142]
例如： copy  A B -u-y
-u 是从线上获取新的文件信息
-y 是不询问继续上次进度
那么，如果第二次运行的时候 线上的文件更新了，利用-y继续上次进度会把A中更新的文件拷贝到B么

**Comment by iwestlin** [comment]
会的

**Comment by jason8303** [comment]
> 会的

谢谢

**Comment by jason8303** [comment]
大佬，关于同步下面这个思路不知道好不好实现：比如A1 同步到B1
每次重新获取A1的目录信息，重新获取B1的目录信息，利用比对功能筛选出与A1目录树不相符的B1中的目录；将筛选出来的B1中的目录执行删除命令；然后开始正式拷贝工作。这样就可以实现同步的功能。
