### ISSUE TITLE
低并发，也经常被限制到sa用尽

### ISSUE THREAD

**Issue by lovitus** [iwestlin/gd-utils#144]
![Screenshot_20200801-175509](https://user-images.githubusercontent.com/14361541/89099307-dbce6500-d420-11ea-84b8-08aa4a71d3a6.png)
作者你好，感谢提供这个程序给大家使用，一直以来使用都相当满意和稳定。
但是最近几天，经常复制几千个小文件都会用尽sa，
我删除sa，倒入新的未使用sa，也一下就耗尽了。
并发是默认的20，sa平均保持3000个以上。
（使用fclone可以完成复制）
请问这个是配置不合理么？比如并发请求数，或单sa请求的pacer值？
谢谢作者

**Comment by iwestlin** [comment]
最近Google的API是经常抽风，我也遇到过：https://github.com/iwestlin/gd-utils/issues/134#issuecomment-666115966
在拷贝刚发出来的图片资源时容易出现

暂时的解决办法：https://github.com/iwestlin/gd-utils/issues/138#issuecomment-666156273

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-02-%E5%85%B3%E4%BA%8E%E6%B2%A1%E6%9C%89%E5%8F%AF%E7%94%A8%E7%9A%84sa%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF

**Comment by lovitus** [comment]
> https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-02-%E5%85%B3%E4%BA%8E%E6%B2%A1%E6%9C%89%E5%8F%AF%E7%94%A8%E7%9A%84sa%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF

更新后已经解决,100并发无报错, 谢谢作者.
