### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by wangzhijie0602** [iwestlin/gd-utils#145]
把if (use_sa && message && message.toLowerCase().includes('rate limit')) { 改为if (false) {后，会出现文件复制完成后不完整的情况，应该是触发了这个：const RETRY LIMIT=7，能不能在任务复制完成后加一个if语句判断文件是否全部被复制，如果没有，就再重新执行这个任务，直到文件全部被复制为止。

任务编号：262
源文件夹：年代记
目的位置：5
新文件夹：17aUgIQyqh1_w4zVqr63qEEu5L5ihtQa7
任务状态：finished
创建时间：2020-08-02 13:12:27
完成时间：2020-08-02 13:31:53
目录进度：714/714
文件进度：2630/3629
总百分比：77.00%
合计大小：404.38 GB

**Comment by iwestlin** [comment]
每个copy请求有7次重试的机会，这种情况下都没完全复制，说明你的大多数sa都触发限制了，或者是sa无效，有没有./validate-sa.js检查过sa的有效性？
你可以 pm2 logs看看具体的报错原因是什么。

> 能不能在任务复制完成后加一个if语句判断文件是否全部被复制，如果没有，就再重新执行这个任务

这个我确实考虑过，但是没这么简单：
首先源文件夹有时会出现分享后又取消分享或触发审核的情况，这样有些资源虽然一开始统计到了，但是后来却无法被转存，这样的话用你的逻辑会造成死循环。
其次有时候用户会根据大小过滤拷贝的文件，这种情况不好判断文件是否被全部复制。

在Google API正常接受请求的条件下，7次重试的机制完全能够cover绝大多数的复制任务，我最多拷贝过两百多万文件数的目录，中间还手动中断了几次，最后一个都没漏。
如果最后有文件没有成功复制，那么一定是要么这个资源出问题了，要么是触发了什么限制，要么甚至是Google的API出问题了。。
可以在服务器上执行 `pm2 logs`看看具体的报错信息，也可以贴到issue进行反馈

**Comment by wangzhijie0602** [comment]
> 每个copy请求有7次重试的机会，这种情况下都没完全复制，说明你的大多数sa都触发限制了，或者是sa无效，有没有./validate-sa.js检查过sa的有效性？
> 你可以 pm2 logs看看具体的报错原因是什么。
> 
> > 能不能在任务复制完成后加一个if语句判断文件是否全部被复制，如果没有，就再重新执行这个任务
> 
> 这个我确实考虑过，但是没这么简单：
> 首先源文件夹有时会出现分享后又取消分享或触发审核的情况，这样有些资源虽然一开始统计到了，但是后来却无法被转存，这样的话用你的逻辑会造成死循环。
> 其次有时候用户会根据大小过滤拷贝的文件，这种情况不好判断文件是否被全部复制。
> 
> 在Google API正常接受请求的条件下，7次重试的机制完全能够cover绝大多数的复制任务，我最多拷贝过两百多万文件数的目录，中间还手动中断了几次，最后一个都没漏。
> 如果最后有文件没有成功复制，那么一定是要么这个资源出问题了，要么是触发了什么限制，要么甚至是Google的API出问题了。。
> 可以在服务器上执行 `pm2 logs`看看具体的报错信息，也可以贴到issue进行反馈

这是当时的log：
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExcee

**Comment by wangzhijie0602** [comment]
这是当时的log：
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | 复制文件失败，文件id: 11REQYJ6-0h9hXR1Sggv0IaINA0SQoIjg
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | 复制文件失败，文件id: 1ShKioW9hy6AHuMaa49-cfux6YV6A0CpG
0|server   | {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}
0|server   | 复制文件失败，文件id: 1ctb-klgq9SFesNeWKK4dHHqzuSlLSQ-z
应该是大量sa被限制了，因为今天复制了不少文件，现在只有200sa，正在扩容sa，这样的做法有效果吗？

**Comment by iwestlin** [comment]
如果是新分享的资源，就算是新加的sa也可能随机触发userratelimit，所以我特意修改了一下剔除sa的逻辑，具体可以看看最新的changelog.md

wangzhijie0602 <notifications@github.com> 于 2020年8月2日周日 16:59写道：

**Comment by wangzhijie0602** [comment]
好的，谢谢，那我关闭了
