### ISSUE TITLE
请问gd-utils的dedupe和rclone的相比，在实现方式上有差异么？

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gd-utils#146]
rclone的dedupe在运行过程中会merge文件和目录，请问gd-utils的这个功能也会有同样的操作么？还是只有去重？（因为rclone dedupe在巨量文件数的目录里运行十分缓慢，所以想试试用gd-utils来查重）

**Comment by iwestlin** [comment]
不清楚rclone的dedupe机制，gd-utils的dedupe是针对复制过程中产生的重复文件（容易在手动中断后继续复制中产生）进行去重的。

https://github.com/iwestlin/gd-utils/issues/90#issuecomment-656725376

./dedupe 会将两类对象移入回收站：

- 相同目录下相同md5的文件 (会保留一个)
- 相同目录下同名的空文件夹(会都删除)

具体的逻辑在 https://github.com/iwestlin/gd-utils/blob/088a9a8b8aac864d6475ffa8109e41e6b48622aa/src/gd.js#L728

**Comment by kingofotaku** [comment]
> 不清楚rclone的dedupe机制，gd-utils的dedupe是针对复制过程中产生的重复文件（容易在手动中断后继续复制中产生）进行去重的。
> 
> [#90 (comment)](https://github.com/iwestlin/gd-utils/issues/90#issuecomment-656725376)
> 
> ./dedupe 会将两类对象移入回收站：
> 
> * 相同目录下相同md5的文件 (会保留一个)
> * 相同目录下同名的空文件夹(会都删除)
> 
> 具体的逻辑在
> 
> https://github.com/iwestlin/gd-utils/blob/088a9a8b8aac864d6475ffa8109e41e6b48622aa/src/gd.js#L728

感谢解释，针对的场景正是我所需要的，不过如果遇到两个包含不一致文件的同名目录，会如何进行操作呢？

**Comment by iwestlin** [comment]
> 如果遇到两个包含不一致文件的同名目录

不会处理
