### ISSUE TITLE
一直提示团队盘已满无法复制

### ISSUE THREAD

**Issue by teolinkiat** [iwestlin/gd-utils#147]
一直提示团队盘已满无法复制，可是我已经移走文件了，要怎么清除继续复制？

**Comment by iwestlin** [comment]
google的团队盘文件数统计应该不是实时的，你可以把新生成的文件夹直接移到另一个没满的团队盘里（需要sa同样有权限），然后在执行一遍复制命令，程序会自动接上上次的进度。
