### ISSUE TITLE
tg 百宝箱交流群 https://t.me/gdutils

### ISSUE THREAD

**Issue by teolinkiat** [iwestlin/gd-utils#148]
大佬最近都没上tg吗？

**Comment by lovitus** [comment]
这你都能开个issue    /斜眼笑

**Comment by teolinkiat** [comment]
找不到大佬啊

**Comment by lovitus** [comment]
> 找不到大佬啊

![image](https://user-images.githubusercontent.com/14361541/89159046-8b324580-d5a1-11ea-8f46-0cf913c30d0c.png)

**Comment by iwestlin** [comment]
tg我故意不上的。。https://github.com/iwestlin/gd-utils/issues/90#issuecomment-661547370

**Comment by teolinkiat** [comment]
为啥呢？

**Comment by lovitus** [comment]
> 为啥呢？

太多因基础能力的求助，和因为时间安排，讲的很明白了。
就像issue也应该像作品一样有参考，查阅，讨论的价值。
我要取消该issue订阅了

**Comment by teolinkiat** [comment]
好吧，预祝大佬前程似锦也谢谢大佬之前耐心的解答，百宝箱帮助了好多人。
