### ISSUE TITLE
无法移除无效的sa

### ISSUE THREAD

**Issue by asd5205651** [iwestlin/gd-utils#149]
我用./validate.js 这个命令允许后 检测出100个无效sa 但是选择yes之后就出错了![Screenshot_2020-08-03-20-09-14-98_3d419158bad5872c40592a6c9956e692.jpg](https://user-images.githubusercontent.com/49519456/89208619-5cc66180-d5c5-11ea-9a16-f7173ae8d1a5.jpg)

**Comment by wnbh** [comment]
这是什么软件？怎么在手机上安装gd-utils?求解

**Comment by asd5205651** [comment]
> 这是什么软件？怎么在手机上安装gd-utils?求解

Juicessh 远程服务器上面安装

**Comment by wnbh** [comment]
> > 这是什么软件？怎么在手机上安装gd-utils？替换
> 
> Juicessh远程服务器上面安装

感谢

**Comment by iwestlin** [comment]
报错意思是程序没有找到对应的路径

你在检测过程中有变动过sa目录下的内容吗，或者是sa目录下不存在`invalid`这个文件夹？
如果是后者，只需要在sa下新建`invalid`即可

**Comment by asd5205651** [comment]
> 报错意思是程序没有找到对应的路径
> 
> 你在检测过程中有变动过sa目录下的内容吗，或者是sa目录下不存在`invalid`这个文件夹？
> 如果是后者，只需要在sa下新建`invalid`即可

好的。我以为会自动创建invalid文件夹😀
