### ISSUE TITLE
請問 是否能在win下執行?

### ISSUE THREAD

**Issue by greenkero** [iwestlin/gd-utils#152]
您好：
看到gd-utils的速度後，令人驚訝它的速度，但看了一下教學，發現沒有在win上執行的教學？
請教如果在win上執行，把本機當成伺服器，要如何配置？
謝謝您～

敬祝　順安

**Comment by iwestlin** [comment]
可以在windows上运行的，因为node本身是跨平台的。
如果遇到问题可以参考 https://github.com/iwestlin/gd-utils/issues/125  和 https://github.com/iwestlin/gd-utils/issues/13

> 把本機當成伺服器，要如何配置

这个比较麻烦，因为我写的机器人需要和tg绑定域名，如果本地没有公网IP的话需要搞内网穿透之类的。。

不过有人改了个不需要域名的版本：https://github.com/iwestlin/gd-utils#%E6%97%A0%E9%9C%80%E5%9F%9F%E5%90%8D%E5%92%8Cnginx%E7%89%88
你可以试试

**Comment by greenkero** [comment]
謝謝您的解答，我來試試看~
