### ISSUE TITLE
机器人遇到奇怪的问题

### ISSUE THREAD

**Issue by Xiefengshang** [iwestlin/gd-utils#154]
现在出现了两次这种情况，一直卡在目录进度0或卡在文件进度n，reload server也不起效.......机器人也没有提示无有效SA账号
etc.
```
任务编号：75
源文件夹：2020-02~2020-03
目的位置：Others
新文件夹：1G5D_WKwA5QcmI0AgbAJ2mLuKQZykQODS 
任务状态：copying
创建时间：2020-08-06 05:27:35
完成时间：未完成
目录进度：0/17348
文件进度：0/300668
总百分比：0.00%
合计大小：22.38 TB
```

```
任务编号：65
源文件夹：2020-02~2020-03
目的位置：Others 
新文件夹：1ASTfBpLn68BFsnDwWRspBeKLDFZPu1Ks 
任务状态：copying
创建时间：2020-08-04 09:46:56
完成时间：未完成
目录进度：17348/17348
文件进度：72888/300668
总百分比：28.37%
合计大小：22.38 TB
```

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/changelog.md
更新下代码吧，如果还遇到请命令行执行 `pm2 logs`看看日志

另外文件数比较多的时候，程序从数据库读取数据也要一点时间，30多万文件估计要20秒左右

**Comment by Xiefengshang** [comment]
> https://github.com/iwestlin/gd-utils/blob/master/changelog.md
> 更新下代码吧，如果还遇到请命令行执行 `pm2 logs`看看日志
> 
> 另外文件数比较多的时候，程序从数据库读取数据也要一点时间，30多万文件估计要20秒左右

我在你刚更新的时候就跑过git pulls了，正常
pm2 logs:
1|server  | fail to send message to tg: Request failed with status code 400
1|server  | {
1|server  |   ok: false,
1|server  |   error_code: 400,
1|server  |   description: 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message'

而且我看了看目的文件夹，没有文件复制成功

**Comment by iwestlin** [comment]
这个报错是向tg服务器发送的请求产生的，意思是消息没有变化（因为拷贝进度不变），这个不用理会

`tail -200 ~/.pm2/logs/server-error.log`这样可以看最近200行的报错信息

**Comment by Xiefengshang** [comment]
> 这个报错是向tg服务器发送的请求产生的，意思是消息没有变化（因为拷贝进度不变），这个不用理会
> 
> `tail -200 ~/.pm2/logs/server-error.log`这样可以看最近200行的报错信息

emmm最近200行都是这个报错。
我把log下载下来打开之后，在上面那串报错之前的全是`{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User rate limit exceeded."}],"code":403,"message":"User rate limit exceeded."}}`但是照理说如果我1200个SA全部被限制了之后，bot应该也会给我发消息啊。
并且我是复制到一个之前没用过的新盘，也不应该被限制啊.....我之后复制相对较少的文件就很正常。
我之前的一个是开跑了1晚上，依然是目录进度 0

**Comment by iwestlin** [comment]
创建目录应该不会遇到 `userRateLimitExceeded` 的报错，只有拷贝文件的时候会

你不妨试试拷贝个小点的目录到新盘，同时开着 pm2 logs看实时日志

目录进度 0 很大可能是sa权限问题

**Comment by Xiefengshang** [comment]
> 创建目录应该不会遇到 `userRateLimitExceeded` 的报错，只有拷贝文件的时候会
> 
> 你不妨试试拷贝个小点的目录到新盘，同时开着 pm2 logs看实时日志
> 
> 目录进度 0 很大可能是sa权限问题

emmm我刚刚试了复制`BBC 9T`的那个文件到同一个盘，毫无问题.....
