### ISSUE TITLE
复制时用了-s参数出现错误20:21:34 | 已复制文件数 0 | 进行中 21 | 排队中文件数 1569 Cannot set property 'exceed_count' of undefined Cannot set property 'exceed_count' of undefined

### ISSUE THREAD

**Issue by greatpp95** [iwestlin/gd-utils#156]
20:21:34 | 已复制文件数 0 | 进行中 21 | 排队中文件数 1569 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined

以前可以，更新完就不行了

**Comment by iwestlin** [comment]
多谢反馈 再更新下吧

注意是 `-S`,大写的

**Comment by greatpp95** [comment]
正常了。👍👍
