### ISSUE TITLE
Tg出现404报错

### ISSUE THREAD

**Issue by jason8303** [iwestlin/gd-utils#158]
1QqsYTAToEj5hWL10eui8juayKWtQ-NUr 统计失败：Request failed with status code 404

今天更新代码后出现的

**Comment by iwestlin** [comment]
https://drive.google.com/drive/folders/1QqsYTAToEj5hWL10eui8juayKWtQ-NUr
这个就是404啊

**Comment by jason8303** [comment]
> https://drive.google.com/drive/folders/1QqsYTAToEj5hWL10eui8juayKWtQ-NUr
> 
> 这个就是404啊

哦 空文件夹就会404是吧？

**Comment by iwestlin** [comment]
sa没有目录的阅读权限或者目录ID不存在会404
