### ISSUE TITLE
git pull 后出现以下错误

### ISSUE THREAD

**Issue by teolinkiat** [iwestlin/gd-utils#159]
SqliteError: database disk image is malformed
0|server  |     at gen_bookmark_choices (/root/gd-utils/src/tg.js:152:56)
0|server  |     at send_choice (/root/gd-utils/src/tg.js:144:16)
0|server  |     at /root/gd-utils/src/router.js:160:12
0|server  |     at dispatch (/root/gd-utils/node_modules/koa-compose/index.js:42:32)
0|server  |     at /root/gd-utils/node_modules/@koa/router/lib/router.js:363:16
0|server  |     at dispatch (/root/gd-utils/node_modules/koa-compose/index.js:42:32)
0|server  |     at /root/gd-utils/node_modules/koa-compose/index.js:34:12
0|server  |     at dispatch (/root/gd-utils/node_modules/@koa/router/lib/router.js:368:31)
0|server  |     at dispatch (/root/gd-utils/node_modules/koa-compose/index.js:42:32)
0|server  |     at bodyParser (/root/gd-utils/node_modules/koa-bodyparser/index.js:95:11)

**Comment by iwestlin** [comment]
看上去像是数据库文件损坏了。。
是不是没有服务器没有空间了，命令行运行下 `node clear-db.js`试试？

如果还不行，那就从https://github.com/iwestlin/gd-utils/blob/master/gdurl.sqlite下载一个空的数据库文件替换掉吧

**Comment by teolinkiat** [comment]
替换了gdurl.sqlite文件还是一样的错误。

**Comment by teolinkiat** [comment]
已经重新安装系统了。

**Comment by iwestlin** [comment]
先在 `gd-utils`目录下执行 `rm gdurl.sqlite*`然后再替换呢？
数据库文件可能有3个

**Comment by iwestlin** [comment]
不能直接`wget https://github.com/iwestlin/gd-utils/blob/master/gdurl.sqlite`啊，那样会下载成网页

**Comment by teolinkiat** [comment]
哈，来不及了，都删完重装系统了，我没有直接下载啊，我先windows下载了文件再ftp上传去服务器的。

**Comment by teolinkiat** [comment]
请问连续触发7次限制的sa要两小时后才能再用吗？

**Comment by iwestlin** [comment]
关于SA的使用机制这里有详细说明：
https://github.com/iwestlin/gd-utils/issues/150#issuecomment-668874408
