### ISSUE TITLE
进度没到100%就完成了是什么情况？

### ISSUE THREAD

**Issue by RouRouX** [iwestlin/gd-utils#161]
重新下载依然是这个进度
![QQ截图20200807165801.jpg](https://i.loli.net/2020/08/07/6xdVhCXM9PmzqWg.jpg)

**Comment by iwestlin** [comment]
任务开始之前
在命令行执行 `pm2 logs` 可以看实时日志

估计是有部分文件触发审核或取消分享导致无法转存

**Comment by RouRouX** [comment]
`
{
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "teamDriveHierarchyTooDeep",
        "message": "The shared drive hierarchy depth will exceed the limit."
      }
    ],
    "code": 403,
    "message": "The shared drive hierarchy depth will exceed the limit."
  }
}
`
报错都是这个，是因为目录结构太深了吗？

**Comment by iwestlin** [comment]
是的，你可以直接把新文件夹移到比较上层的目录然后再执行一遍复制命令，程序会自动接上进度
