### ISSUE TITLE
文件夹目录过深，复制失败

### ISSUE THREAD

**Issue by 04960523** [iwestlin/gd-utils#162]
{"error":{"errors":[{"domain":"global","reason":"teamDriveHierarchyTooDeep","message":"The shared drive hierarchy depth will exceed the limit."}],"code":403,"message":"The shared drive hierarchy depth will exceed the limit."}}

**Comment by iwestlin** [comment]
参考 https://github.com/iwestlin/gd-utils/issues/161#issuecomment-670442919

**Comment by fzsimlu** [comment]
@iwestlin  我看了#161解决办法，但是我复制在团盘的根目录也出现这个情况，是否因为搬运的文件夹本身过深

**Comment by iwestlin** [comment]
有可能
如果目录不多的话你可以用这个[接口](https://gdurl.viegg.com/api/gdrive/count?fid=1A35MT6auEHASo3egpZ3VINMOwvA47cJG&type=tree)
```
https://gdurl.viegg.com/api/gdrive/count?fid=FolderID&type=tree
```
找出最深的目录，然后把它移到比较上层的位置再试试

**Comment by fzsimlu** [comment]
> 有可能
> 如果目录不多的话你可以用这个[接口](https://gdurl.viegg.com/api/gdrive/count?fid=1A35MT6auEHASo3egpZ3VINMOwvA47cJG&type=tree)
> 
> ```
> https://gdurl.viegg.com/api/gdrive/count?fid=FolderID&type=tree
> ```
> 
> 找出最深的目录，然后把它移到比较上层的位置再试试

这样继续复制，会自动复制到转移后的目录吗

**Comment by iwestlin** [comment]
会的，就算移到别的团队盘也会，只要sa有权限
