### ISSUE TITLE
建议机器人增加更多命令行的功能

### ISSUE THREAD

**Issue by RouRouX** [iwestlin/gd-utils#165]
比如 pm2 reload

还有aria2.js的相关功能

今天试用了一下用aria2生成gdshare直链下载链接，超级好用，速度直接拉满！！

**Comment by iwestlin** [comment]
我是有考虑过加入一个 /reload 命令执行 `pm2 reload server`，但这样的话会导致有些搭了不止一个机器人的环境出现问题……据我所知频道里就有两个代搭机器人的。。而且有些人还不是用 pm2 启动的

**Comment by iwestlin** [comment]
给机器人添加了 `/reload` 指令：https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-08

应该支持多个server.js进程共存的情况

**Comment by cy-j** [comment]
重启完成能不能加一个提示呢？

**Comment by iwestlin** [comment]
> 重启完成能不能加一个提示呢？

不太好搞，因为发送tg消息需要一个 chat_id的变量，这个变量是储存在内存中的，进程重启后变量就丢失了。
目前只是在重启前发送一条消息，正常情况下1秒内就能完成重启了。

**Comment by teolinkiat** [comment]
我在统计文件但是在tg机器人发送了/reload命令为什么没有重启进程啊？

**Comment by GaryLz** [comment]
> 我是有考虑过加入一个 /reload 命令执行 `pm2 reload server`，但这样的话会导致有些搭了不止一个机器人的环境出现问题……据我所知频道里就有两个代搭机器人的。。而且有些人还不是用 pm2 启动的

## 输入/reload后，bot没反应，后台查看log发现遭遇「依赖冲突」。

很荣幸在这里向gd-utils的作者提issue，首先很感谢作者继续给我们带来更多的功能更新。 

今天日常爬贴，发现gd-utils机器人添加了/reload功能的新更新，欣喜若狂地更新代码后，晚上就想体验体验，结果刚输入在tg输入此命令，bot就没好几分钟没反应了。结果登陆远程主机，pm2 logs查看日志，

![image](https://user-images.githubusercontent.com/31096335/89714142-3c384600-d9cf-11ea-8e78-a0cbe3f8e5b2.png)

就发现此报错，之后几次再重新pm2 reload server，虽然能运行，但提醒“restart次数最过多”⚠️，bot依旧没反应，但后来在gd-utils/下，尝试直接node server.js，运行后却是正常接受信息，并返回之前的bot命令结果，因此推断——tg后台api没有出现问题，应该是pm2管理下的server进程出了问题，那样说，依赖也应该没问题才对。

但是，后面还是尝试，删除node_module，pm2删除任务进程，重新安装依赖，但pm2重新运行还会中途报错。因此，我还是弄不清哪个环节出错。

原谅我才疏学浅，想问问作者的宝贵的专业分析。

环境配置
- node
![image](https://user-images.githubusercontent.com/31096335/89714602-7f47e880-d9d2-11ea-9e7c-bfe4dcc4a5e1.png)
- npm
![image](https://user-images.githubusercontent.com/31096335/89714639-af8f8700-d9d2-11ea-8a53-3017ca3631bc.png)
- pm2
![image](https://user-images.githubusercontent.com/31096335/89714709-3cd2db80-d9d3-11ea-9dfe-f5bbbf2724f0.png)

PS.
> 最后的解决方案是，重新解压了上一个commit的备份，按照README的流程走，重新安装node_modules，最后npm uninstall pm2，更新pm2到最新版本后，pm2启动server才正常。

但是，正常后的node-log依旧报better-sqlite3依赖错误，不过，bot信息响应却是正常的。
![image](https://user-images.githubusercontent.com/31096335/89714768-b79bf680-d9d3-11ea-82d6-d83a0f242c6d.png)

**玄学问题**

**Comment by iwestlin** [comment]
看报错的意思是之前安装依赖的node版本和现在所用的node版本不一样，导致 better-sqlite（数据库）这个依赖出错。有不少人也遇到过：https://github.com/JoshuaWise/better-sqlite3/search?q=node_module_version&type=Issues
如果 `node server.js`能正常运行说明命令行里的node版本和依赖是对上的，可能是pm2守护的那个进程里的node版本不对，如果是这样的话先`pm2 delete server`然后再 `pm2 start server.js --node-args="--max-old-space-size=1024"`应该就可以了

> 正常后的node-log依旧报better-sqlite3依赖错误

最后的日志截图显示的是之前的报错，能运行就说明依赖安装正常了。

**Comment by RouRouX** [comment]
我这刚刚更新了，reload一切正常。作者大佬辛苦了！

**Comment by teolinkiat** [comment]
是不是可以考虑增加一个上传sa然后解压的功能？
