### ISSUE TITLE
发现一个现象，不确定是不是gd-utils的问题

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gd-utils#167]
我是在本地的git bash上挂代理跑的，今天发现转存过程中会出现一开始正常运行无报错，1-2分钟后频繁出现`[{"domain":"global","reason":"internalError","message":"Internal Error"}],"code"
:500,"message":"Internal Error"}}
` 这一报错的情况。一开始以为是梯子不稳定，后来换了不下十个节点（甚至更换过代理工具）后观察到每个都会出现这样的情况。不知道大佬对此有什么思路？

**Comment by kingofotaku** [comment]
毕竟诡异的是刚一更换节点报错就会消失，过段时间一定又会出现。

**Comment by iwestlin** [comment]
internalError是Google内部错误，对于刚发出来的分享链接经常触发，可能是同一时间太多人转存造成服务器压力太大

**Comment by kingofotaku** [comment]
> internalError是Google内部错误，对于刚发出来的分享链接经常触发，可能是同一时间太多人转存造成服务器压力太大

没错，今天转同一个资源报错就少很多。感谢解惑。
