### ISSUE TITLE
rate limit 超多，还能愉快的玩耍吗？

### ISSUE THREAD

**Issue by christan-duplicate** [iwestlin/gd-utils#168]
![image](https://user-images.githubusercontent.com/769138/89762318-c218d600-db22-11ea-974f-63e80e3868d3.png)

**Comment by iwestlin** [comment]
这是普遍现象，我在更新日志里提到了：https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-06

**Comment by christan-duplicate** [comment]
文件進度：175788/175852 - 99.964%

到了这个进度，就一直显示：
已複製的檔案數 175788 | 排隊中檔案數 0

显示了一个晚上这个了，进度还是在 99.964%

**Comment by iwestlin** [comment]
再执行一遍命令看看pm2 logs呢？

可能有些文件触发审核没复制成功

**Comment by christan-duplicate** [comment]
重新执行一次 /copy xxx 后，还是这样显示信息
![image](https://user-images.githubusercontent.com/769138/89964828-c1488700-dc7d-11ea-9d5e-d3e415a32ec5.png)

**Comment by iwestlin** [comment]
从日志上看繁体版没有更新到最新代码，最新代码会显示进行中的请求

你可以clone下本仓库，然后
命令行执行 `./copy folderid targetid -S --verbose`看看详细日志

**Comment by iwestlin** [comment]
数据库文件可以直接copy过来

**Comment by christan-duplicate** [comment]
好的，我试试

**Comment by christan-duplicate** [comment]
用了最新的简体版后，变成这样了
![image](https://user-images.githubusercontent.com/769138/89967425-040d5d80-dc84-11ea-9222-bedc66aaed64.png)

**Comment by iwestlin** [comment]
这个错误我在这里解释过：https://github.com/iwestlin/gd-utils/issues/170#issuecomment-672411873

看Google的API返回的详细信息需要在
命令行执行 `./copy folderid targetid -S --verbose`

**Comment by christan-duplicate** [comment]
/copy folderid targetid -S --verbose

![image](https://user-images.githubusercontent.com/769138/89970053-8436c180-dc8a-11ea-9d8a-b1ecf8bd8212.png)

![image](https://user-images.githubusercontent.com/769138/89970087-9f093600-dc8a-11ea-9b34-59a6706cac65.png)

加了这些参数，现在又好了，原因是什么呢
传完了。

以后传文件都要加上 -S --verbose 吗

**Comment by iwestlin** [comment]
。。我的意思是在**命令行**执行，不是在tg机器人里

机器人里不需要加 `-S --verbose`，会被忽略掉。
在命令行里加 `--verbose` 表示输出详细日志

> 加了这些参数，现在又好了，原因是什么呢

我也不知道啊，因为我没看到日志，但肯定不是因为你加了那些参数……

**Comment by christan-duplicate** [comment]
那估计是google抽风了，多谢你的解答。
