### ISSUE TITLE
aria2生成直接链接下载几百个G之后就不动了

### ISSUE THREAD

**Issue by carlliuxx** [iwestlin/gd-utils#169]
如题，每次下载300多G左右，就不动了，也不知道在哪能看到进度和状态～

我是在nas里搭了个aria2的docker，进入docker，输入命令执行的，但是在ariang的界面上看不到进度，实际已经开始执行下载，但是下载个几百G就不动了～

**Comment by iwestlin** [comment]
[aria2.js](https://github.com/iwestlin/gd-utils/blob/master/aria2.js) 生成的直链默认有24小时的有效期，这个值也可以手动更改，具体请看 `./aria2.js -h`

也有可能是被cloudflare判定成滥用了，你可以用浏览器打开生成的`uri.txt`中的直链看具体什么返回
