### ISSUE TITLE
关于sa和个人盘

### ISSUE THREAD

**Issue by 666wcy** [iwestlin/gd-utils#17]
![image](https://user-images.githubusercontent.com/40867688/85944818-3e3ccd00-b96c-11ea-84ad-3ca732943a92.png)
这里说可以用sa传到个人盘，但是我执行
./copy 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz -S
到个人盘时会提示错误，
`{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ."}}
创建目录重试中： 物语系列 重试次数： 7
复制文件夹出错 Error: 创建目录失败，请检查您的帐号是否有相应的权限`
如何操作可用sa传递到个人盘

**Comment by Linon419** [comment]
我也是创建目录失败

**Comment by iwestlin** [comment]
> ![image](https://user-images.githubusercontent.com/40867688/85944818-3e3ccd00-b96c-11ea-84ad-3ca732943a92.png)
> 这里说可以用sa传到个人盘，但是我执行
> ./copy 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz -S
> 到个人盘时会提示错误，
> `{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ."}} 创建目录重试中： 物语系列 重试次数： 7 复制文件夹出错 Error: 创建目录失败，请检查您的帐号是否有相应的权限`
> 如何操作可用sa传递到个人盘

尽管每个sa最多传15G文件到个人盘，你还是要继续吗……

你这个问题应该是没给sa个人盘对应文件夹的权限。需要把sa设置成editor

**Comment by 666wcy** [comment]
> > ![image](https://user-images.githubusercontent.com/40867688/85944818-3e3ccd00-b96c-11ea-84ad-3ca732943a92.png)
> > 这里说可以用sa传到个人盘，但是我执行
> > ./copy 1gHLzyYOXo0NRDLqAK75Z_vdslSuL6Bzz -S
> > 到个人盘时会提示错误，
> > `{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 1zinYLW3anjVUe25aPtyrYL1SnYcwXUCQ."}} 创建目录重试中： 物语系列 重试次数： 7 复制文件夹出错 Error: 创建目录失败，请检查您的帐号是否有相应的权限`
> > 如何操作可用sa传递到个人盘
> 
> 尽管每个sa最多传15G文件到个人盘，你还是要继续吗……
> 
> 你这个问题应该是没给sa个人盘对应文件夹的权限。需要把sa设置成editor

文件夹添加权限后成功，老哥牛逼
