### ISSUE TITLE
请问这个错误是什么?

### ISSUE THREAD

**Issue by june601** [iwestlin/gd-utils#170]
![Screenshot_2020-08-11-12-28-02-43](https://user-images.githubusercontent.com/69406603/89857574-0feb1800-dbcf-11ea-80cf-e8269969fb62.jpg)

**Comment by june601** [comment]
我不知道图片有没有上传成功，下面是错误代码


 fail to send message to tg: Request failed with status code 400
{ok: false,
 error_code: 400
 description:
 Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message'}
 fail to send message to tg: Request failed with status code 400
ok: false
 error_code: 400
 description:ms
 'Bad Reauest: essage is not modified specified new messa
 content and reply markup are exactly the same as a current content and reply markup of the message'
 fail to send message to tg: Request failed with status code 400
{ok: false,
 error_code: 400,
 description:.
 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message'}

**Comment by iwestlin** [comment]
图片可以显示

`fail to send message to tg:` 这个错误是发送给tg服务器时发生的，这个请求的目的是更新tg机器人的任务详情进度（就是输入 /task 后返回的内容），任务进行中，每10秒会发送一次更新请求。
报错的意思是要更新的内容没有发生变化，这是由于任务进度没有变化，容易发生在任务只剩最后几个文件时，10秒内这几个文件一直在网络请求中，所以进度就没变化。
所以这类错误可以不用理会。
