### ISSUE TITLE
Request for Tree output as snap2html

### ISSUE THREAD

**Issue by Jankonyex** [iwestlin/gd-utils#171]
The current Tree output is usable but quite laggy for larger directory. In terms of output performance, snap2html by rlvision is suggested:
https://www.rlvision.com/snap2html/about.php

One way of listing is to virtually mount GDrive into local computer and run snap2html. Better way is provided by alx-xlx as:
https://github.com/alx-xlx/gdrive-index

Really need someone to modify and add it to the colab provided by orange2008

**Comment by iwestlin** [comment]
done: https://github.com/iwestlin/gd-utils/blob/master/changelog.md#2020-08-13

you could run command like:
```bash
./count folderID -S -t snap -o example.html
```
