### ISSUE TITLE
rclone config 最后一步配置(输入验证码)总是过不去

### ISSUE THREAD

**Issue by EssTaYi** [iwestlin/gd-utils#172]
2020/08/12 13:31:36 Failed to configure token: failed to get token: Post "https://oauth2.googleapis.com/token": EOF
配置rclone时总是出现这样的问题,最后一步总是不成功,我一直怀疑时Mac终端无法链接国际互联网的问题, 可以解答一下处理方法吗?不胜感激

**Comment by christan-duplicate** [comment]
curl google.com
看看结果

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE

如果你的网络环境无法正常访问谷歌服务，需要先在命令行进行一些配置：（如果可以正常访问则跳过此节）
```
http_proxy="YOUR_PROXY_URL" && https_proxy=$http_proxy && HTTP_PROXY=$http_proxy && HTTPS_PROXY=$http_proxy
```
请把YOUR_PROXY_URL替换成你自己的代理地址
