### ISSUE TITLE
copy或count数量在几万以上的文件夹时，总是卡在最后几百~几十个文件，必须取消重来才行。

### ISSUE THREAD

**Issue by kingofotaku** [iwestlin/gd-utils#173]
首先很抱歉总是发issues来打扰作者。我近期发现了如标题所述之现象，如果是第一次操作的文件夹倒还无所谓，可以继续之前的进度。问题在于第二次带-u参数运行，如果没运行完就结束的话是无法继续刚才的进度的（比如count就是打断后再运行不带-u的命令，结果就是读取第一次已完成的缓存，而不会接着第二次的进度进行）

**Comment by kingofotaku** [comment]
标题的现象几乎会出现在每个超大文件夹上，而且同样已排除代理节点的问题。

**Comment by iwestlin** [comment]
这种现象可能是最后几个请求被分配给了Google压力过大的服务器，不断超时造成响应缓慢，你可以调整下`config.js`里的最大超时时间 https://github.com/iwestlin/gd-utils/blob/53300af550cc9709c8cb202df6683a12da94b7d4/config.js#L4

> count就是打断后再运行不带-u的命令，结果就是读取第一次已完成的缓存，而不会接着第二次的进度进行

如果没统计完成，**命令行**`./count`是可以接上上次的进度的，机器人如果读取到曾经的统计结果会直接返回。
目前是这样的，我改了下代码使得二者行为一致，但还没push到线上测试。

**Comment by kingofotaku** [comment]
> 这种现象可能是最后几个请求被分配给了Google压力过大的服务器，不断超时造成响应缓慢，你可以调整下`config.js`里的最大超时时间
> 
> https://github.com/iwestlin/gd-utils/blob/53300af550cc9709c8cb202df6683a12da94b7d4/config.js#L4
> 
> > count就是打断后再运行不带-u的命令，结果就是读取第一次已完成的缓存，而不会接着第二次的进度进行
> 
> 如果没统计完成，**命令行**`./count`是可以接上上次的进度的，机器人如果读取到曾经的统计结果会直接返回。
> 目前是这样的，我改了下代码使得二者行为一致，但还没push到线上测试。

期待改进 我比较喜欢用-u（因为很多大资源需要时间转码，刚分享的时候获取不全。）

**Comment by iwestlin** [comment]
已经更新了，现在的逻辑是：
如果统计链接时有些目录没有获取完全，则不保存总结信息（summary）到数据库，只有获取完全才会保存。
如果`count`命令加了`-u`参数，或者点击了机器人的「强制刷新」按钮，会先清除掉数据库中之前保存的对应目录的summary信息，这样就算统计中断，下次统计没找到summary信息则会继续统计。

**Comment by kingofotaku** [comment]
> 已经更新了，现在的逻辑是：
> 如果统计链接时有些目录没有获取完全，则不保存总结信息（summary）到数据库，只有获取完全才会保存。
> 如果`count`命令加了`-u`参数，或者点击了机器人的「强制刷新」按钮，会先清除掉数据库中之前保存的对应目录的summary信息，这样就算统计中断，下次统计没找到summary信息则会继续统计。

这个逻辑不错，另外再问一下，如果我copy了一个目录，但这个目录在当时是不完全的，等过一段时间后我再用带-u的命令copy一次，结果会是只copy新增的部分么？

**Comment by iwestlin** [comment]
> 如果我copy了一个目录，但这个目录在当时是不完全的，等过一段时间后我再用带-u的命令copy一次，结果会是只copy新增的部分么？

是的

**Comment by kingofotaku** [comment]
> > 如果我copy了一个目录，但这个目录在当时是不完全的，等过一段时间后我再用带-u的命令copy一次，结果会是只copy新增的部分么？
> 
> 是的

我个人的使用感觉上来说这个机制似乎有抽风的几率？ 有时候明明统计出更多的文件了，但却没有新复制文件，又或者复制了极少数文件。

**Comment by iwestlin** [comment]
有没有具体日志？

对于拷贝过的对象，程序会把它的ID保存到数据库里，然后复制的时候从源文件夹中的所有对象中去除已拷贝的，再开始拷贝剩下。

命令行输出或pm2 logs都会记录待拷贝的文件数

**Comment by kingofotaku** [comment]
> 有没有具体日志？
> 
> 对于拷贝过的对象，程序会把它的ID保存到数据库里，然后复制的时候从源文件夹中的所有对象中去除已拷贝的，再开始拷贝剩下。
> 
> 命令行输出或pm2 logs都会记录待拷贝的文件数

下次遇到的时候贴一个上来吧

**Comment by kingofotaku** [comment]
> > 有没有具体日志？
> > 对于拷贝过的对象，程序会把它的ID保存到数据库里，然后复制的时候从源文件夹中的所有对象中去除已拷贝的，再开始拷贝剩下。
> > 命令行输出或pm2 logs都会记录待拷贝的文件数
> 
> 下次遇到的时候贴一个上来吧 是不是要加什么参数才能输出详细日志？

**Comment by iwestlin** [comment]
命令行加 `--verbose`会额外输出超时和`rate limit`的报错，其他都一样

**Comment by kingofotaku** [comment]
> 命令行加 `--verbose`会额外输出`timeout`和`rate limit`的报错，其他都一样

明白了 那这个问题我先留着

**Comment by kingofotaku** [comment]
> > > 有没有具体日志？
> > > 对于拷贝过的对象，程序会把它的ID保存到数据库里，然后复制的时候从源文件夹中的所有对象中去除已拷贝的，再开始拷贝剩下。
> > > 命令行输出或pm2 logs都会记录待拷贝的文件数
> 
> 下次遇到的时候贴一个上来吧 是不是要加什么参数才能输出详细日志？

今天就碰上这种情况了 贴一下日志
（第一个统计是需要copy的共享文件夹 第二个统计是copy过但不完整的文件夹 第三个是copy后的结果 可以看到剩余一些文件并没有成功复制）


Administrator@Ftago-Note MINGW64 /d/gd-utils (master)
$ node ./count 1qH6Q7vXvYraFNJ6cUxwEf7Ilm5SWqR5N -S -u
使用代理： socks5://127.0.0.1:1478
20:45:40 | 已获取对象 53358 | 网络请求 进行中200/排队中6533 read ECONNRESET
20:45:41 | 已获取对象 53554 | 网络请求 进行中200/排队中6412 read ECONNRESET
20:45:45 | 已获取对象 54186 | 网络请求 进行中200/排队中5820 read ECONNRESET
read ECONNRESET
Client network socket disconnected before secure TLS connection was established
20:45:48 | 已获取对象 54201 | 网络请求 进行中200/排队中5808 read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
write EPROTO 13992:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert proto
col version:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1544:SSL alert
number 70

read ECONNRESET
20:45:49 | 已获取对象 54201 | 网络请求 进行中200/排队中5808 read ECONNRESET
20:45:55 | 已获取对象 55088 | 网络请求 进行中200/排队中4947 read ECONNRESET
20:46:03 | 已获取对象 56478 | 网络请求 进行中200/排队中3646 read ECONNRESET
20:46:09 | 已获取对象 60223 | 网络请求 进行中200/排队中2696 read ECONNRESET
20:46:50 | 已获取对象 108627 | 网络请求 进行中1/排队中0  5
信息获取完毕
所有目录读取完毕
┌────────────┬────────┬───────────┐
│    Type    │ Count  │   Size    │
├────────────┼────────┼───────────┤
│    flac    │ 42228  │  1.22 TB  │
├────────────┼────────┼───────────┤
│    jpg     │ 15820  │ 25.26 GB  │
├────────────┼────────┼───────────┤
│    mp3     │ 14356  │ 135.38 GB │
├────────────┼────────┼───────────┤
│    tta     │  6719  │  1.65 TB  │
├────────────┼────────┼───────────┤
│    png     │  2932  │ 21.64 GB  │
├────────────┼────────┼───────────┤
│    cue     │  1541  │  3.83 MB  │
├────────────┼────────┼───────────┤
│    dff     │  1518  │ 277.39 GB │
├────────────┼────────┼───────────┤
│    htm     │  1470  │  5.68 MB  │
├────────────┼────────┼───────────┤
│    log     │  1400  │ 14.29 MB  │
├────────────┼────────┼───────────┤
│    m3u     │  801   │  1.37 MB  │
├────────────┼────────┼───────────┤
│    txt     │  560   │  4.08 MB  │
├────────────┼────────┼───────────┤
│    bmp     │  435   │ 15.67 GB  │
├────────────┼────────┼───────────┤
│    m4a     │  357   │  1.29 GB  │
├────────────┼────────┼───────────┤
│    dsf     │  328   │ 66.79 GB  │
├────────────┼────────┼───────────┤
│    clpi    │  300   │ 568.02 KB │
├────────────┼────────┼───────────┤
│    wav     │  276   │ 44.29 GB  │
├────────────┼────────┼───────────┤
│    ini     │  264   │ 57.30 KB  │
├────────────┼────────┼───────────┤
│    m3u8    │  219   │ 129.55 KB │
├────────────┼────────┼───────────┤
│    m2ts    │  150   │ 84.79 GB  │
├────────────┼────────┼───────────┤
│    mkv     │  139   │ 225.82 GB │
├────────────┼────────┼───────────┤
│    lrc     │   96   │ 233.92 KB │
├────────────┼────────┼───────────┤
│    mp4     │   88   │ 35.09 GB  │
├────────────┼────────┼───────────┤
│    wma     │   85   │ 546.75 MB │
├────────────┼────────┼───────────┤
│    gif     │   75   │  5.06 MB  │
├────────────┼────────┼───────────┤
│    webp    │   59   │ 183.88 MB │
├────────────┼────────┼───────────┤
│    tif     │   58   │  1.22 GB  │
├────────────┼────────┼───────────┤
│    iso     │   41   │ 164.61 GB │
├────────────┼────────┼───────────┤
│    zip     │   38   │  3.14 GB  │
├────────────┼────────┼───────────┤
│    url     │   37   │ 12.94 KB  │
├────────────┼────────┼───────────┤
│    md5     │   27   │ 16.62 KB  │
├────────────┼────────┼───────────┤
│    tak     │   27   │  2.41 GB  │
├────────────┼────────┼───────────┤
│    html    │   27   │ 33.03 KB  │
├────────────┼────────┼───────────┤
│    vsq     │   22   │  6.87 MB  │
├────────────┼────────┼───────────┤
│    jpeg    │   20   │  2.23 MB  │
├────────────┼────────┼───────────┤
│    pdf     │   19   │ 271.25 MB │
├────────────┼────────┼───────────┤
│    vob     │   19   │  4.33 GB  │
├────────────┼────────┼───────────┤
│    sfv     │   16   │  9.82 KB  │
├────────────┼────────┼───────────┤
│    mds     │   15   │ 63.31 KB  │
├────────────┼────────┼───────────┤
│    rar     │   14   │  5.62 GB  │
├────────────┼────────┼───────────┤
│    jfif    │   12   │  2.16 MB  │
├────────────┼────────┼───────────┤
│    aiff    │   12   │ 785.54 MB │
├────────────┼────────┼───────────┤
│    crt     │   12   │  9.34 KB  │
├────────────┼────────┼───────────┤
│    bdmv    │   12   │  1.29 KB  │
├────────────┼────────┼───────────┤
│ properties │   12   │ 217.84 KB │
├────────────┼────────┼───────────┤
│    jar     │   10   │  3.00 MB  │
├────────────┼────────┼───────────┤
│    nfo     │   8    │ 29.26 KB  │
├────────────┼────────┼───────────┤
│    bdjo    │   8    │  3.46 KB  │
├────────────┼────────┼───────────┤
│    sy1     │   8    │  4.72 KB  │
├────────────┼────────┼───────────┤
│     db     │   7    │  1.70 MB  │
├────────────┼────────┼───────────┤
│    zpl     │   6    │ 15.37 KB  │
├────────────┼────────┼───────────┤
│    mid     │   5    │ 388.31 KB │
├────────────┼────────┼───────────┤
│    mmf     │   5    │ 16.03 KB  │
├────────────┼────────┼───────────┤
│    sha1    │   4    │  3.59 KB  │
├────────────┼────────┼───────────┤
│    sig     │   4    │  1.16 KB  │
├────────────┼────────┼───────────┤
│    crl     │   4    │  8.00 KB  │
├────────────┼────────┼───────────┤
│    avi     │   4    │ 277.82 MB │
├────────────┼────────┼───────────┤
│    mpls    │   4    │ 33.35 KB  │
├────────────┼────────┼───────────┤
│    bin     │   4    │ 377.84 KB │
├────────────┼────────┼───────────┤
│    ddp     │   3    │ 439.00 B  │
├────────────┼────────┼───────────┤
│  accurip   │   3    │  3.94 KB  │
├────────────┼────────┼───────────┤
│    swf     │   3    │ 32.09 MB  │
├────────────┼────────┼───────────┤
│    tmp     │   3    │ 55.61 MB  │
├────────────┼────────┼───────────┤
│    psd     │   3    │ 51.23 MB  │
├────────────┼────────┼───────────┤
│     pk     │   2    │  3.47 MB  │
├────────────┼────────┼───────────┤
│    part    │   2    │ 130.43 MB │
├────────────┼────────┼───────────┤
│    csv     │   2    │  1.50 KB  │
├────────────┼────────┼───────────┤
│    dvd     │   2    │  60.00 B  │
├────────────┼────────┼───────────┤
│    doc     │   2    │ 35.50 KB  │
├────────────┼────────┼───────────┤
│    inf     │   2    │  94.00 B  │
├────────────┼────────┼───────────┤
│    ifo     │   2    │ 32.00 KB  │
├────────────┼────────┼───────────┤
│    bup     │   2    │ 32.00 KB  │
├────────────┼────────┼───────────┤
│    css     │   2    │ 472.00 B  │
├────────────┼────────┼───────────┤
│ fontindex  │   2    │ 624.00 B  │
├────────────┼────────┼───────────┤
│    otf     │   2    │  5.51 MB  │
├────────────┼────────┼───────────┤
│    grn     │   2    │ 119.17 KB │
├────────────┼────────┼───────────┤
│    xml     │   2    │  3.77 KB  │
├────────────┼────────┼───────────┤
│     js     │   2    │ 16.25 KB  │
├────────────┼────────┼───────────┤
│      1     │   1    │ 221.20 KB │
├────────────┼────────┼───────────┤
│    pkf     │   1    │ 616.81 KB │
├────────────┼────────┼───────────┤
│  torrent   │   1    │ 32.48 KB  │
├────────────┼────────┼───────────┤
│    maff    │   1    │ 701.40 KB │
├────────────┼────────┼───────────┤
│    mpg     │   1    │ 80.49 MB  │
├────────────┼────────┼───────────┤
│    exe     │   1    │ 252.00 KB │
├────────────┼────────┼───────────┤
│    mht     │   1    │ 469.08 KB │
├────────────┼────────┼───────────┤
│    00t     │   1    │ 48.28 KB  │
├────────────┼────────┼───────────┤
│    00s     │   1    │ 140.15 KB │
├────────────┼────────┼───────────┤
│    00n     │   1    │ 18.42 KB  │
├────────────┼────────┼───────────┤
│    00j     │   1    │ 125.97 KB │
├────────────┼────────┼───────────┤
│     ja     │   1    │ 660.00 B  │
├────────────┼────────┼───────────┤
│    cdp     │   1    │  2.00 KB  │
├────────────┼────────┼───────────┤
│    flv     │   1    │ 55.08 MB  │
├────────────┼────────┼───────────┤
│  无扩展名  │   10   │ 32.34 MB  │
├────────────┼────────┼───────────┤
│   文件夹   │ 15830  │     0     │
├────────────┼────────┼───────────┤
│    总计    │ 108634 │  3.97 TB  │
└────────────┴────────┴───────────┘


Administrator@Ftago-Note MINGW64 /d/gd-utils (master)
$ node ./count 19bvWuzYpZdymtpZLejD6SuBiWz9a3ZsI -S -u
使用代理： socks5://127.0.0.1:1478
20:48:28 | 已获取对象 35699 | 网络请求 进行中200/排队中7965 read ECONNRESET
20:49:00 | 已获取对象 47832 | 网络请求 进行中200/排队中3821 read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
20:49:45 | 已获取对象 108564 | 网络请求 进行中1/排队中0   4
信息获取完毕
所有目录读取完毕
┌────────────┬────────┬───────────┐
│    Type    │ Count  │   Size    │
├────────────┼────────┼───────────┤
│    flac    │ 42183  │  1.22 TB  │
├────────────┼────────┼───────────┤
│    jpg     │ 15814  │ 25.26 GB  │
├────────────┼────────┼───────────┤
│    mp3     │ 14356  │ 135.38 GB │
├────────────┼────────┼───────────┤
│    tta     │  6719  │  1.65 TB  │
├────────────┼────────┼───────────┤
│    png     │  2932  │ 21.64 GB  │
├────────────┼────────┼───────────┤
│    cue     │  1541  │  3.83 MB  │
├────────────┼────────┼───────────┤
│    dff     │  1518  │ 277.39 GB │
├────────────┼────────┼───────────┤
│    htm     │  1470  │  5.68 MB  │
├────────────┼────────┼───────────┤
│    log     │  1400  │ 14.29 MB  │
├────────────┼────────┼───────────┤
│    m3u     │  801   │  1.37 MB  │
├────────────┼────────┼───────────┤
│    txt     │  560   │  4.08 MB  │
├────────────┼────────┼───────────┤
│    bmp     │  435   │ 15.67 GB  │
├────────────┼────────┼───────────┤
│    m4a     │  357   │  1.29 GB  │
├────────────┼────────┼───────────┤
│    dsf     │  328   │ 66.79 GB  │
├────────────┼────────┼───────────┤
│    clpi    │  300   │ 568.02 KB │
├────────────┼────────┼───────────┤
│    wav     │  276   │ 44.29 GB  │
├────────────┼────────┼───────────┤
│    ini     │  259   │ 56.60 KB  │
├────────────┼────────┼───────────┤
│    m3u8    │  219   │ 129.55 KB │
├────────────┼────────┼───────────┤
│    m2ts    │  150   │ 84.79 GB  │
├────────────┼────────┼───────────┤
│    mkv     │  139   │ 225.82 GB │
├────────────┼────────┼───────────┤
│    lrc     │   96   │ 233.92 KB │
├────────────┼────────┼───────────┤
│    mp4     │   88   │ 35.09 GB  │
├────────────┼────────┼───────────┤
│    wma     │   85   │ 546.75 MB │
├────────────┼────────┼───────────┤
│    gif     │   75   │  5.06 MB  │
├────────────┼────────┼───────────┤
│    webp    │   59   │ 183.88 MB │
├────────────┼────────┼───────────┤
│    tif     │   58   │  1.22 GB  │
├────────────┼────────┼───────────┤
│    iso     │   41   │ 164.61 GB │
├────────────┼────────┼───────────┤
│    zip     │   38   │  3.14 GB  │
├────────────┼────────┼───────────┤
│    url     │   37   │ 12.94 KB  │
├────────────┼────────┼───────────┤
│    md5     │   27   │ 16.62 KB  │
├────────────┼────────┼───────────┤
│    tak     │   27   │  2.41 GB  │
├────────────┼────────┼───────────┤
│    html    │   27   │ 33.03 KB  │
├────────────┼────────┼───────────┤
│    vsq     │   22   │  6.87 MB  │
├────────────┼────────┼───────────┤
│    jpeg    │   20   │  2.23 MB  │
├────────────┼────────┼───────────┤
│    pdf     │   19   │ 271.25 MB │
├────────────┼────────┼───────────┤
│    vob     │   19   │  4.33 GB  │
├────────────┼────────┼───────────┤
│    sfv     │   16   │  9.82 KB  │
├────────────┼────────┼───────────┤
│    mds     │   15   │ 63.31 KB  │
├────────────┼────────┼───────────┤
│    rar     │   14   │  5.62 GB  │
├────────────┼────────┼───────────┤
│    aiff    │   12   │ 785.54 MB │
├────────────┼────────┼───────────┤
│    jfif    │   12   │  2.16 MB  │
├────────────┼────────┼───────────┤
│    bdmv    │   12   │  1.29 KB  │
├────────────┼────────┼───────────┤
│    crt     │   12   │  9.34 KB  │
├────────────┼────────┼───────────┤
│ properties │   12   │ 217.84 KB │
├────────────┼────────┼───────────┤
│    jar     │   10   │  3.00 MB  │
├────────────┼────────┼───────────┤
│    nfo     │   8    │ 29.26 KB  │
├────────────┼────────┼───────────┤
│    bdjo    │   8    │  3.46 KB  │
├────────────┼────────┼───────────┤
│    sy1     │   8    │  4.72 KB  │
├────────────┼────────┼───────────┤
│     db     │   7    │  1.70 MB  │
├────────────┼────────┼───────────┤
│    zpl     │   6    │ 15.37 KB  │
├────────────┼────────┼───────────┤
│    mid     │   5    │ 388.31 KB │
├────────────┼────────┼───────────┤
│    mmf     │   5    │ 16.03 KB  │
├────────────┼────────┼───────────┤
│    sha1    │   4    │  3.59 KB  │
├────────────┼────────┼───────────┤
│    sig     │   4    │  1.16 KB  │
├────────────┼────────┼───────────┤
│    crl     │   4    │  8.00 KB  │
├────────────┼────────┼───────────┤
│    avi     │   4    │ 277.82 MB │
├────────────┼────────┼───────────┤
│    mpls    │   4    │ 33.35 KB  │
├────────────┼────────┼───────────┤
│    bin     │   4    │ 377.84 KB │
├────────────┼────────┼───────────┤
│    ddp     │   3    │ 439.00 B  │
├────────────┼────────┼───────────┤
│  accurip   │   3    │  3.94 KB  │
├────────────┼────────┼───────────┤
│    swf     │   3    │ 32.09 MB  │
├────────────┼────────┼───────────┤
│    tmp     │   3    │ 55.61 MB  │
├────────────┼────────┼───────────┤
│    psd     │   3    │ 51.23 MB  │
├────────────┼────────┼───────────┤
│     pk     │   2    │  3.47 MB  │
├────────────┼────────┼───────────┤
│    part    │   2    │ 130.43 MB │
├────────────┼────────┼───────────┤
│    csv     │   2    │  1.50 KB  │
├────────────┼────────┼───────────┤
│    dvd     │   2    │  60.00 B  │
├────────────┼────────┼───────────┤
│    doc     │   2    │ 35.50 KB  │
├────────────┼────────┼───────────┤
│    inf     │   2    │  94.00 B  │
├────────────┼────────┼───────────┤
│    ifo     │   2    │ 32.00 KB  │
├────────────┼────────┼───────────┤
│    bup     │   2    │ 32.00 KB  │
├────────────┼────────┼───────────┤
│ fontindex  │   2    │ 624.00 B  │
├────────────┼────────┼───────────┤
│    otf     │   2    │  5.51 MB  │
├────────────┼────────┼───────────┤
│    css     │   2    │ 472.00 B  │
├────────────┼────────┼───────────┤
│    grn     │   2    │ 119.17 KB │
├────────────┼────────┼───────────┤
│    xml     │   2    │  3.77 KB  │
├────────────┼────────┼───────────┤
│      1     │   1    │ 221.20 KB │
├────────────┼────────┼───────────┤
│    pkf     │   1    │ 616.81 KB │
├────────────┼────────┼───────────┤
│  torrent   │   1    │ 32.48 KB  │
├────────────┼────────┼───────────┤
│    maff    │   1    │ 701.40 KB │
├────────────┼────────┼───────────┤
│    mpg     │   1    │ 80.49 MB  │
├────────────┼────────┼───────────┤
│    exe     │   1    │ 252.00 KB │
├────────────┼────────┼───────────┤
│    mht     │   1    │ 469.08 KB │
├────────────┼────────┼───────────┤
│    00t     │   1    │ 48.28 KB  │
├────────────┼────────┼───────────┤
│    00s     │   1    │ 140.15 KB │
├────────────┼────────┼───────────┤
│    00n     │   1    │ 18.42 KB  │
├────────────┼────────┼───────────┤
│    00j     │   1    │ 125.97 KB │
├────────────┼────────┼───────────┤
│     ja     │   1    │ 660.00 B  │
├────────────┼────────┼───────────┤
│    cdp     │   1    │  2.00 KB  │
├────────────┼────────┼───────────┤
│    flv     │   1    │ 55.08 MB  │
├────────────┼────────┼───────────┤
│     js     │   1    │  8.13 KB  │
├────────────┼────────┼───────────┤
│  无扩展名  │   10   │ 32.34 MB  │
├────────────┼────────┼───────────┤
│   文件夹   │ 15819  │     0     │
├────────────┼────────┼───────────┤
│    总计    │ 108566 │  3.96 TB  │
└────────────┴────────┴───────────┘


Administrator@Ftago-Note MINGW64 /d/gd-utils (master)
$ node ./copy 1qH6Q7vXvYraFNJ6cUxwEf7Ilm5SWqR5N  0ACqlwHAPTaqiUk9PVA -S
使用代理： socks5://127.0.0.1:1478
√ 检测到上次的复制记录，是否继续？ » Exit
退出程序

Administrator@Ftago-Note MINGW64 /d/gd-utils (master)
$ node ./copy 1qH6Q7vXvYraFNJ6cUxwEf7Ilm5SWqR5N  0ACqlwHAPTaqiUk9PVA -S -u
使用代理： socks5://127.0.0.1:1478
√ 检测到上次的复制记录，是否继续？ » Continue
20:50:38 | 已获取对象 16998 | 网络请求 进行中200/排队中3656 read ECONNRESET
20:50:39 | 已获取对象 17770 | 网络请求 进行中200/排队中4232 read ECONNRESET
20:50:42 | 已获取对象 20384 | 网络请求 进行中200/排队中6265 read ECONNRESET
SA获取access_token失败： request to https://www.googleapis.com/oauth2/v4/token f
ailed, reason: read ECONNRESET
20:50:45 | 已获取对象 22352 | 网络请求 进行中200/排队中7725 read ECONNRESET
20:50:48 | 已获取对象 27773 | 网络请求 进行中200/排队中8416 read ECONNRESET
20:50:54 | 已获取对象 45453 | 网络请求 进行中200/排队中9150 read ECONNRESET
20:50:59 | 已获取对象 52432 | 网络请求 进行中200/排队中8696 read ECONNRESET
20:51:31 | 已获取对象 60080 | 网络请求 进行中200/排队中2948 Client network socke
t disconnected before secure TLS connection was established
20:51:53 | 已获取对象 98350 | 网络请求 进行中200/排队中387 read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
read ECONNRESET
20:51:59 | 已获取对象 108456 | 网络请求 进行中13/排队中0
信息获取完毕
所有目录读取完毕
开始复制文件夹，总数： 0

任务完成，新文件夹链接：
 https://drive.google.com/drive/folders/19bvWuzYpZdymtpZLejD6SuBiWz9a3ZsI

**Comment by iwestlin** [comment]
对于新生成的数量庞大的文件夹，就算过几天再统计也是有可能未显示完全的，这是Google接口的问题，就像有些发出来的分享链接，几天后都没有完全显示。

所以实际上任务是复制完成了，只不过你统计看文件数少了。

最靠谱的确认办法是查询数据库里的拷贝记录，因为只有Google接口明确返回某文件或目录拷贝完成的信息时，它的ID才会被记录到数据库中标记为已拷贝。
查询方法可以在拷贝时，对tg机器人输入 `/task`，它就会返回正在进行的任务了（就算任务是在命令行进行的也会返回）

或者如果你不想再拷贝一次，可以输入 `/task all`，然后从返回的最新列表里找到这次记录的task_ID，再输入`/task task_ID`

机器人返回的任务详细信息，里面的目录进度和文件进度就反映了已记录的拷贝成功的对象数量

**Comment by kingofotaku** [comment]
> 对于新生成的数量庞大的文件夹，就算过几天再统计也是有可能未显示完全的，这是Google接口的问题，就像有些发出来的分享链接，几天后都没有完全显示。
> 
> 所以实际上任务是复制完成了，只不过你统计看文件数少了。
> 
> 最靠谱的确认办法是查询数据库里的拷贝记录，因为只有Google接口明确返回某文件或目录拷贝完成的信息时，它的ID才会被记录到数据库中标记为已拷贝。
> 查询方法可以在拷贝时，对tg机器人输入 `/task`，它就会返回正在进行的任务了（就算任务是在命令行进行的也会返回）
> 
> 或者如果你不想再拷贝一次，可以输入 `/task all`，然后从返回的最新列表里找到这次记录的task_ID，再输入`/task task_ID`
> 
> 机器人返回的任务详细信息，里面的目录进度和文件进度就反映了已记录的拷贝成功的对象数量

本地命令行是否有对应命令？

**Comment by iwestlin** [comment]
还没有，后续可能加

**Comment by kingofotaku** [comment]
> 还没有，后续可能加

静候佳音
