### ISSUE TITLE
404 错误

### ISSUE THREAD

**Issue by hrzhao76** [iwestlin/gd-utils#174]
您好！ 
请问这个错误如何解决hmmm

机器人启动了，并且可以统计Source文件的信息，但是copy的时候报错

/root/.pm2/logs/server-error.log last 15 lines:
0|server   | 复制失败 1UQhI4iqe52onbZiEEljTWOL_vB50Z2w6 --> 0AGWwtNdJa6PJUk9PVA
0|server   | Error: Request failed with status code 404 目录名：高晓松合集
0|server   |     at create_folder (/root/gd-utils/src/gd.js:415:9)
0|server   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|server   | {"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 0AGWwtNdJa6PJUk9PVA.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 0AGWwtNdJa6PJUk9PVA."}}

我确定源文件和目标ID都是有的，似乎是没有权限创建目录？

补充 node check.js 也能正常返回 hmmm
谢谢您的工作！

**Comment by Domonlee** [comment]
这个[issue-163](https://github.com/iwestlin/gd-utils/issues/163)和你的问题很像，应该会有帮助哈。

**Comment by hrzhao76** [comment]
Ok 解决了 

要确保service account 都有在 team drive里面 这些service有权限读写 - -  hmmm

可以通过建立群组加
或者在 AutoRClone 里面 运行 
python3 add_to_team_drive.py -d SharedTeamDriveSrcID
