### ISSUE TITLE
用主用帐户（非sa）复制时报的错误

### ISSUE THREAD

**Issue by sztuxp** [iwestlin/gd-utils#175]
开始复制文件，总数： 21
06:09:54 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:09:55 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:09:56 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:09:57 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:09:58 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:09:59 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:01 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:02 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:03 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:04 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:05 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:08 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:09 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:10 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:11 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:12 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:13 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:14 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:16 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:18 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:20 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:21 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:22 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:23 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:26 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:27 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
06:10:28 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:30 | 已复制文件数 0 | 进行中 8 | 排队中文件数 13 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 14CviC092bVa7lHzrGx1C5-7EXfvWV7tq
06:10:31 | 已复制文件数 0 | 进行中 8 | 排队中文件数 12 Cannot set property 'exceed_count' of undefined
06:10:34 | 已复制文件数 0 | 进行中 8 | 排队中文件数 12 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:35 | 已复制文件数 0 | 进行中 8 | 排队中文件数 12 Cannot set property 'exceed_count' of undefined
06:10:36 | 已复制文件数 0 | 进行中 8 | 排队中文件数 12 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1wUPNrSn8oiVNRd89j_gU-FiWvJgw3c_j
06:10:38 | 已复制文件数 0 | 进行中 8 | 排队中文件数 11 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:40 | 已复制文件数 0 | 进行中 8 | 排队中文件数 11 Cannot set property 'exceed_count' of undefined
06:10:41 | 已复制文件数 0 | 进行中 8 | 排队中文件数 11 Cannot set property 'exceed_count' of undefined
06:10:42 | 已复制文件数 0 | 进行中 8 | 排队中文件数 11 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1Yaudoh0yv4g8TZShNPUaXQKpIfyXzzXD
06:10:43 | 已复制文件数 0 | 进行中 7 | 排队中文件数 11 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1VLDo2P4diIlTBtdepuUAuqqtXySR0UyM
06:10:46 | 已复制文件数 0 | 进行中 8 | 排队中文件数 9 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1IMa4o0ydosG1QhDDrzxDj2nznngWSXlp
06:10:47 | 已复制文件数 0 | 进行中 8 | 排队中文件数 8 Cannot set property 'exceed_count' of undefined
06:10:48 | 已复制文件数 0 | 进行中 8 | 排队中文件数 8 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1zqc4N6at3Xmrlwi4AupidCXDFSWc-kj6
06:10:51 | 已复制文件数 0 | 进行中 8 | 排队中文件数 7 Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1QUwc-qy_x-gduUL3PqccinaIs5rAZU1L
06:10:53 | 已复制文件数 0 | 进行中 8 | 排队中文件数 6 Cannot set property 'exceed_count' of undefined
06:10:54 | 已复制文件数 0 | 进行中 8 | 排队中文件数 6 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:10:56 | 已复制文件数 0 | 进行中 8 | 排队中文件数 6 Cannot set property 'exceed_count' of undefined
06:10:57 | 已复制文件数 0 | 进行中 8 | 排队中文件数 6 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
复制文件失败，文件id: 1aBPXlrDNMaQi9Lte3efKGnuWQtGDsUxr
06:10:59 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:11:00 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:11:02 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
Cannot set property 'exceed_count' of undefined
06:11:03 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
06:11:04 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
06:11:05 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined
06:11:06 | 已复制文件数 0 | 进行中 8 | 排队中文件数 5 Cannot set property 'exceed_count' of undefined

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/issues/156
更新下代码吧，你刚好clone了之前有问题的一次提交

**Comment by sztuxp** [comment]
谢谢！更新后，就没问题了，之前的问题代码是每个文件会重复复制几次，更新后，也解决了
