### ISSUE TITLE
会支持群晖或者N1盒子（openwrt)吗

### ISSUE THREAD

**Issue by wang001200** [iwestlin/gd-utils#176]
vps可用内存太小（因为装了emby),电脑又不方便一直开着。。。。

**Comment by iwestlin** [comment]
node是跨平台的，各种Linux发行版基本都支持。
不过better-sqlite3这个依赖安装时可能需要构建环境（make/gcc这些）

**Comment by wang001200** [comment]
> node是跨平台的，各种Linux发行版基本都支持。
> 不过better-sqlite3这个依赖安装时可能需要构建环境（make/gcc这些）
哦哦，大佬真是起得早。。。
还想问下：1、使用命令行copy的时候一般只要加-S参数把？有没有更详细的参数说明文档呀
                   2、怎么可以让命令在关闭远程ssh后继续运行？是copy XX XX -S &吗（即最后加&参数）？
此2点搜索引擎都没找到答案。忘赐教

**Comment by wang001200** [comment]
什么鬼，我这个回复引用，怎么自己的内容看起来也是引用的。。。。。。

**Comment by iwestlin** [comment]
1. 命令行执行 `./copy -h` 就可以看说明了

2. 可以用 nohup 之类的命令， `nohup ... &` 这样
