### ISSUE TITLE
请问教育账号无限空间的，用生成的sa复制，为啥会出现这个问题呢？

### ISSUE THREAD

**Issue by antisouler** [iwestlin/gd-utils#179]
![image](https://user-images.githubusercontent.com/22548670/90459925-5099e280-e135-11ea-9605-4b788bec9e88.png)

![image](https://user-images.githubusercontent.com/22548670/90459994-80e18100-e135-11ea-87fd-823033692d02.png)

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/issues/105#issuecomment-657541325

**Comment by iwestlin** [comment]
解决办法先拷贝到团队盘再手动移到个人盘

**Comment by antisouler** [comment]
> 解决办法先拷贝到团队盘再手动移到个人盘

OK，我先试试
