### ISSUE TITLE
文件复制如何保证文件相对位置不变

### ISSUE THREAD

**Issue by fcki1984** [iwestlin/gd-utils#18]
## 问题1
- 前提
共享文件夹有多个子文件夹
- 命令
./copy 共享文件id
- 问题
复制到团队盘，发现子文件夹全部不见，所有文件都在根文件夹内
## 问题2
>config.js中的默认盘
- 前提
将一个团队盘文件夹复制到其他团队盘
-命令
bot：/copy 默认盘ID 2盘ID
ssh：./copy 默认盘ID 2盘ID
- 问题
bot命令复制会在2盘产生空文件夹`Drive`
然后在ssh中复制成功盘根目录有个`云端硬盘`的文件夹，但同样有问题1，文件全部在根文件内。
ssh复制成功后，2盘复制到3盘，会在默认盘产生`Drive`文件夹。
2盘复制到4盘显示`有相同源ID和目的ID的任务已复制完成，如需重新复制请更换目的地`

**Comment by iwestlin** [comment]
你可能刚好git clone了我有问题的一次代码提交，最新代码应该解决了文件结构打乱的问题。
可以在项目文件夹`git pull`更新下代码再试试。

这个问题的原因应该是跳过了创建文件夹，直接开始复制文件，文件找不到parent会复制到根目录。

bot命令默认使用的是sa授权，可能它没有读取团队盘根目录的权限？我自己的sa是manager，是可以读取的。

如果遇到相同任务的消息，用命令行操作吧，它可以选择restart
