### ISSUE TITLE
为何复制的这么慢，是被限制频率了吗

### ISSUE THREAD

**Issue by antisouler** [iwestlin/gd-utils#180]
如图，为何复制的这么慢，是被限制频率了吗，限制的是账号，还是IP？还是目的盘，怎么解决呢

![image](https://user-images.githubusercontent.com/22548670/90720594-7536bb80-e2e9-11ea-8506-9f05572abee0.png)

**Comment by iwestlin** [comment]
估计是google api又抽风了，之前为了用户体验隐藏了一些报错，可以命令行执行的时候加上 --verbose 显示报错信息

antisoul <notifications@github.com> 于 2020年8月20日周四 15:37写道：
