### ISSUE TITLE
the oauth client was not found

### ISSUE THREAD

**Issue by hyzcyxzy1** [iwestlin/gd-utils#181]
大佬，我用脚本搭建不用域名的那个分支，然后在转存时报错误，the oauth client was not found，这是什么原因呢

**Comment by hyzcyxzy1** [comment]
复制文件夹错误，error401

**Comment by iwestlin** [comment]
你是用命令行操作的吗？是不是没有加 `-S` 参数？不加的话会用到个人授权。
个人授权需要在 `config.js` 里填 client_id 这些，不填的话就会报错the oauth client was not found

**Comment by hyzcyxzy1** [comment]
好的，我看看，我开始是直接用机器人的，但是机器人没有创建任务我就用命令行

**Comment by hyzcyxzy1** [comment]
大佬，我现在填了client id和secret，转存时报SyntaxError: Invalid or unexpected token
请问这是没填 refresh_token的原因吗，这个 refresh_token怎么获取呢

**Comment by iwestlin** [comment]
SyntaxError 是语法错误，你应该是填的内容不符合JavaScript的语法。。

注意要用英文标点，结尾要加 `,`

**Comment by hyzcyxzy1** [comment]
folderclone里面有吗，因为我这个账号只配置了folderclone

**Comment by iwestlin** [comment]
```
mm> quick-setup 2 0ABCdeyz_ZaMsxxxLGA
This will automatically:
create 2 projects
enable the required services
create Service Accounts
add them to the Shared Drive
and download their credentials into a new folder accounts
You are now ready to go to the next step.
```
我看它的readme里写的会自动配置service account啊，你找找有没有 `accounts` 这个目录

**Comment by hyzcyxzy1** [comment]
服务账户里面有，我移上去了😂，是我用的命令是个人盘的，没有用的sa的原因，我等下就去试试，感谢大佬
