### ISSUE TITLE
建议: 加入自动清理数据库功能

### ISSUE THREAD

**Issue by lovitus** [iwestlin/gd-utils#189]
希望在bot命令中, 加入清理数据库功能. 
当磁盘空间小于指定值时. 在用户下一次指令时提示空间需要清理. 

目前系统只有一个/, 爆盘以后问题很多.

**Comment by iwestlin** [comment]
> [2020-07-21]
> 添加数据库clear脚本，只需在gd-utils目录下执行`node clear-db.js`就可以删除所有获取的文件信息（但会保留拷贝记录和bookmark）同时减小数据库文件大小了

目前只能在命令行操作，不打算给机器人添加命令行执行功能
