### ISSUE TITLE
默认文件夹问题

### ISSUE THREAD

**Issue by njgdl1995** [iwestlin/gd-utils#19]
![微信截图_20200629011755](https://user-images.githubusercontent.com/24458979/85953932-7b25b580-b9a6-11ea-93c9-b47000bca404.png)
![微信截图_20200629011829](https://user-images.githubusercontent.com/24458979/85953934-7cef7900-b9a6-11ea-8a54-d58cafff94a3.png)
用默认指定的目标文件夹会提示没有权限，手动的话可以。都是同一个文件夹

**Comment by iwestlin** [comment]
你的 default_target是不是后来才修改的啊，修改后要 `pm2 reload server`才能生效。。

**Comment by iwestlin** [comment]
另外，在机器人里不用加 `-S`的，命令行才要加，机器人默认都是sa授权

**Comment by njgdl1995** [comment]
> 你的 default_target是不是后来才修改的啊，修改后要 `pm2 reload server`才能生效。。

重启了一下可以进行任务了，但是就创建了个文件夹然后提示任务完成。

**Comment by iwestlin** [comment]
你用的是最新代码吗？

项目文件夹内`git pull`拉一下最新代码，然后再reload下试试呢。

还出问题发下 pm2 logs 的日志吧

**Comment by njgdl1995** [comment]
> 你用的是最新代码吗？
> 
> 项目文件夹内`git pull`拉一下最新代码，然后再reload下试试呢。
> 
> 还出问题发下 pm2 logs 的日志吧

![168B589B-9FDA-430A-A941-97298AA1586A](https://user-images.githubusercontent.com/24458979/85955492-83cfb900-b9b1-11ea-97f1-f665f918d592.png)

**Comment by iwestlin** [comment]
要刚好是你发送拷贝任务时候的日志……

`tail -200 ~/.pm2/logs/server-error.log`

**Comment by iwestlin** [comment]
我知道了，原因是程序把你输入的 `-S` 当成目标地址了。。

我刚加上了检查目标地址是否合法的逻辑，你可以再更新下试试。。

<img width="737" alt="截屏2020-06-29 上午10 46 45" src="https://user-images.githubusercontent.com/6235509/85967787-d92db980-b9f5-11ea-9d36-391c0078447b.png">

**Comment by husion** [comment]
顺便问一下，sourceID部分好像可以从链接提取ID，但是targetID部分如果直接使用链接，会出现同样的权限报错

**Comment by njgdl1995** [comment]
> 我知道了，原因是程序把你输入的 `-S` 当成目标地址了。。
> 
> 我刚加上了检查目标地址是否合法的逻辑，你可以再更新下试试。。
> 
> <img alt="截屏2020-06-29 上午10 46 45" width="737" src="https://user-images.githubusercontent.com/6235509/85967787-d92db980-b9f5-11ea-9d36-391c0078447b.png">

好了 辛苦您了

**Comment by iwestlin** [comment]
> 顺便问一下，sourceID部分好像可以从链接提取ID，但是targetID部分如果直接使用链接，会出现同样的权限报错，如果换成ID可以顺利转存

是的，目前没对targetid做进一步提取
