### ISSUE TITLE
作者你好，centos8搭建gd-utils完成后，bot总是重启，用的是无域名版本的。

### ISSUE THREAD

**Issue by EAlyce** [iwestlin/gd-utils#190]

**Comment by iwestlin** [comment]
你用的是 https://github.com/dissipator/gd-utils 这个吗？

是不是你输入 `/restart` 后机器人一直回复你 `restarting!` ？

如果是，我想问题出在它依赖的`telebot`这个包上，它使用的是长轮询获取用户发送给机器人的tg消息，然后每个消息会有一个 update_id (https://core.telegram.org/bots/api#update)

当处理完某个消息时，这个包会记录下这个 update_id，并在下次请求时携带一个 `offset` 参数，表明获取比上面这个 update_id 更新的消息。
然而问题在于telebot把这个offset存储在了内存里，也就是说进程重启之后，这个值就丢失了，那么它再次获取更新时又会拿到你之前发送的 `/restart` 命令，进而再次重启，如此周而复始……

解决办法：
1、修改一下 telebot 这个依赖，让它把offset这个值持久化存储在本地文件中，然后启动的时候从文件里读取这个值。
2、换成别的依赖比如 https://github.com/telegraf/telegraf

@dissipator 来看看？

**Comment by iwestlin** [comment]
当然还有更简单点的方法就是自己记录下 `/restart` 消息的 `message_id`，存储到本地数据库或文件中，执行进程重启前先把它标记成已处理，下次收到 `/restart` 时比对下是否处理过了。

**Comment by xax19** [comment]
好的，谢谢作者

**Comment by dissipator** [comment]
我没遇到过类似情况。确实没有存储到本地数据库或文件中。
