### ISSUE TITLE
机器人使用权限

### ISSUE THREAD

**Issue by teolinkiat** [iwestlin/gd-utils#191]
你好，如果想把链接了百宝箱的TG机器人给任何人都能使用的公交车有办法实现吗？安装说明是写要添加用户名才可以。

**Comment by iwestlin** [comment]
如果你确定要这么做，可以把这一行
https://github.com/iwestlin/gd-utils/blob/e38352a8d392ebe063cd96a44268089ff6e861a1/src/router.js#L103
改成 `return true`

**Comment by teolinkiat** [comment]
好的，谢谢你。
