### ISSUE TITLE
我的目的地盘，已经删除了所有的东西，为啥还会报这个错？

### ISSUE THREAD

**Issue by antisouler** [iwestlin/gd-utils#194]
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}

**Comment by xax19** [comment]
有延迟

**Comment by invoker-kael** [comment]
回收站清空
