### ISSUE TITLE
在数据库已有所有文件夹和文件的情况下，能否添加挂载功能？

### ISSUE THREAD

**Issue by czahoi** [iwestlin/gd-utils#2]
一直在用rclone的mount功能，但效率较低。gd-utils将文件列入数据库中，多sa并发，能否提高挂载效率

**Comment by iwestlin** [comment]
没太看懂。。这个项目是直接调用谷歌api的，不依赖于rclone，也没有挂载网络硬盘的功能。
而且只专注于server side copy功能，后续应该也不会加上挂载功能了
