### ISSUE TITLE
telegram bot 没有反应以及关于refresh_token

### ISSUE THREAD

**Issue by CyshallChan** [iwestlin/gd-utils#200]
<img width="929" alt="09-04 at 20 45 12@2x" src="https://user-images.githubusercontent.com/22564041/92240664-8c7fc680-eeef-11ea-9c4e-b23e64bcf831.png">
<img width="176" alt="09-04 at 20 45 05@2x" src="https://user-images.githubusercontent.com/22564041/92240666-8d185d00-eeef-11ea-8646-4ddefac65e4e.png">

检测都没有问题，但telegram bot就是没有反应。

后面使用node check.js检查401：
![09-04 at 20 46 41@2x](https://user-images.githubusercontent.com/22564041/92240847-d4065280-eeef-11ea-9f00-d1fafe569beb.png)
对于图中的refresh_token我真的很迷惑，因为在Google api界面我只看到client_id和client_secret并没有这个refresh_token，

搜之前的issue看见你说如果使用了sa就不需要这个，我sa目录下面有sa的json文件，也用了validate-sa.js对sa进行了检查，我已经完全不知道该怎么解决这个问题了，还请作者抽空帮忙解决一下～

**Comment by iwestlin** [comment]
机器人不响应最可能的原因是nginx没有把443端口的请求转发到23333，或者是tg白名单配置有误。
可以参照这个issue https://github.com/iwestlin/gd-utils/issues/141 一步步排查。

命令行 pm2 logs 可以看到日志，如果gd-utils接收到了tg的请求会打印出来。

refresh_token 不会在google页面显示出来，需要你用 rclone配置一个remote才会有，具体这里有说明：
https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E4%B8%AA%E4%BA%BA%E5%B8%90%E5%8F%B7%E9%85%8D%E7%BD%AE

机器人一切操作默认使用sa授权，所以也可以不用配置`refresh_token`

执行 `node check.js` 检测的是个人授权，使用sa可以跳过

**Comment by CyshallChan** [comment]
@iwestlin 
折腾许久还是无果，最后使用了“无需域名和nginx版”

但是我还是好奇这个refresh_token，配置rclone的过程中没有出现refresh_token，我后面另外加一个remote也还是没有出现refresh_token。
<img width="705" alt="09-05 at 10 46 48@2x" src="https://user-images.githubusercontent.com/22564041/92296238-1cac2300-ef65-11ea-97e3-f9fb3d9689de.png">

**Comment by iwestlin** [comment]
你用的是gclone吧，原版rclone好像是不支持sa授权的，refresh_token是给个人帐户授权用的。

**Comment by CyshallChan** [comment]
好的，了解了，感谢解答🙏
