### ISSUE TITLE
请问下为啥已复制文件数 一直为0

### ISSUE THREAD

**Issue by antisouler** [iwestlin/gd-utils#204]
09:59:59 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:02 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:05 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:08 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:11 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:14 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:17 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:20 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:23 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:26 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:29 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:32 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:35 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
10:00:38 | 已复制文件数 0 | 进行中 21 | 排队中文件数 54
![image](https://user-images.githubusercontent.com/22548670/92672939-76896000-f34c-11ea-8825-2accb6d625b7.png)

这是什么原因呢

**Comment by kingofotaku** [comment]
我今天也遇到了，看起来是Google那边的机制有变化？

**Comment by trancanh1102** [comment]
![image](https://user-images.githubusercontent.com/40576239/92693150-6b93f700-f36f-11ea-80ed-371fb68a9a7a.png)
![image](https://user-images.githubusercontent.com/40576239/92693203-7ea6c700-f36f-11ea-9b6f-7c7d9e5b8536.png)
我也收到此错误，目录已创建，但似乎文件没有被复制

**Comment by Xiefengshang** [comment]
SA暂时用不了

**Comment by LeeeMooo** [comment]
今天SA好像炸了，十几G的文件都复制不了。不知道是不是Google那边有限制了

**Comment by fzfile** [comment]
google 貌似开始限制文件复制了。
