### ISSUE TITLE
团队盘 to 团队盘

### ISSUE THREAD

**Issue by yurk29** [iwestlin/gd-utils#21]
想问下是否支持从团队盘到另一个团队盘
ps. 两个团队盘里都有相同的sa

**Comment by iwestlin** [comment]
我没有试过整盘拷贝，文件夹拷贝是没问题的。

我去试下整盘的再来回复你

**Comment by iwestlin** [comment]
我刚试了下整盘拷贝是没问题的

sa的权限应该是两个盘的 内容管理者 及以上

**Comment by yurk29** [comment]
已经把sa作为内容管理员添加到两个团队盘

![TIM图片20200629110921](https://user-images.githubusercontent.com/51869450/85969209-98d03a80-b9f9-11ea-9f6b-6fb6ebf88bc7.png)
![TIM图片20200629111026](https://user-images.githubusercontent.com/51869450/85969211-9bcb2b00-b9f9-11ea-9a54-f0ae1fb016c3.png)

尝试过把团队盘A中的一个文件夹复制到团队盘B中, task结果如下:

![TIM图片20200629110759](https://user-images.githubusercontent.com/51869450/85969273-bd2c1700-b9f9-11ea-91e4-6c4b560098ab.png)

尝试把团队盘A整盘复制到团队盘B, task结果如下:

![TIM图片20200629111134](https://user-images.githubusercontent.com/51869450/85969339-ecdb1f00-b9f9-11ea-84c6-b20b647499a8.png)

两种尝试实际上均只在团队盘B中各生成了一个空文件夹

此外, 我没有进行  **个人账号配置**  这一步(因为用不到个人盘)

不知道问题出在哪一步

**Comment by iwestlin** [comment]
你用命令行操作一下看看？
`./copy source targer -S -u`

因为tg机器人是会缓存源ID的文件信息的，如果是新创建的文件夹，可能它里面的内容还没有完全被google更新，这时候去读取它的话内容会不完全。
然后用机器人去复制这个源文件夹的话，它默认会使用数据库里缓存的信息，所以后续复制的都是不完整的内容。

命令行的话加个 `-u`参数就告诉程序强制更新源ID的文件信息。

我没想到大家都偏爱用机器人……其实它的能力比命令行少很多的，我一开始把它独立出去就好了。。

**Comment by yurk29** [comment]
> 你用命令行操作一下看看？
> `./copy source targer -S -u`
> 
> 因为tg机器人是会缓存源ID的文件信息的，如果是新创建的文件夹，可能它里面的内容还没有完全被google更新，这时候去读取它的话内容会不完全。
> 然后用机器人去复制这个源文件夹的话，它默认会使用数据库里缓存的信息，所以后续复制的都是不完整的内容。
> 
> 命令行的话加个 `-u`参数就告诉程序强制更新源ID的文件信息。
> 
> 我没想到大家都偏爱用机器人……其实它的能力比命令行少很多的，我一开始把它独立出去就好了。。

是的, 直接使用命令行没问题

如果在bot里面先/count sourceID, 再用/copy sourceID targetID 就没问题了
