### ISSUE TITLE
进度为0

### ISSUE THREAD

**Issue by eamon-zhang** [iwestlin/gd-utils#22]
任务一直卡在0   很久很久 
完成时间：未完成
目录进度：0/未知数量
文件进度：0/未知数量
总大小：未知大小

**Comment by iwestlin** [comment]
目测是sa没有权限的原因，命令行执行下相同命令看看输出什么？

**Comment by eamon-zhang** [comment]
权限有的 所有者  拷贝的也是公开分享的

**Comment by eamon-zhang** [comment]
刚刚卡死了  bot没反应 后端任务也没了

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/issues/20#issuecomment-650868765

如果是统计上百万文件数造成的内存爆炸，可以看看readme的最后一段

**Comment by eamon-zhang** [comment]
这个 900个服务号  就复制了一个文件 就提示复制失败，失败消息：所有SA帐号流量已用完

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0

看下这个

**Comment by iwestlin** [comment]
readme 更新了下说明
> 如果你使用tg操作时，发送拷贝命令以后，/task 进度始终未开始（在复制文件数超多的文件夹时常会发生），是正常现象。 这是因为程序正在获取源文件夹的所有文件信息。它的运行机制严格按照以下顺序：

1、获取源文件夹所有文件信息 
2、根据源文件夹的目录结构，在目标文件夹创建目录 
3、所有目录创建完成后，开始复制文件
