### ISSUE TITLE
tg机器人怎么使用个人账户copy

### ISSUE THREAD

**Issue by HEYANG1995** [iwestlin/gd-utils#226]
有些团队盘只能加个人账户，怎么复制？

**Comment by HEYANG1995** [comment]
我想另开一个机器人，修改哪里可以不让机器人执行使用SA复制的命令?

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/issues/225#issuecomment-759514428

**Comment by HEYANG1995** [comment]
感谢
