### ISSUE TITLE
关于去重逻辑的建议

### ISSUE THREAD

**Issue by main-nnko** [iwestlin/gd-utils#229]
百宝箱去重是是根据MD5相同来去重的，但实际上有些本来就是名称不同的同MD5文件也被错误去重了。
例如VCB-Stdio的龙与虎扫图中的小册子1和2的封面 Toradora_Book1-000.jpg Toradora_Book2-000.jpg本来就是相同的文件但其存在仍有意义却被删除了。
建议判断MD5的同时检查文件名是否相同进行去重，或者将去重逻辑开放给用户编辑（比如115下载的确实有名称不同的冗余文件要删除）

**Comment by main-nnko** [comment]
这个问题在搬运vcb的时候遇到了不少次，去重检测到了35个重复文件，但是由复制产生的冗余文件只有5个。其中主要是图片和字幕的复用导致的

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/blob/f99a9c0845b06874239eb28a5093d38a17457c16/src/gd.js#L842

如果你想加上文件名这个因素，只需要把上面这行改成

```js
const key = parent + '|' + md5Checksum + '|' + name
```

这样就只会删除相同位置下的md5相同的同名文件了

**Comment by main-nnko** [comment]
谢
