### ISSUE TITLE
使用copy团队盘复制到团队盘出现问题

### ISSUE THREAD

**Issue by Manx98** [iwestlin/gd-utils#23]
使用  ./copy 团队盘ID 团队盘ID -S 
整体复制团队盘出现任务卡死，打开pm2 log查看日志 日志不断重复显示相同的任务执行状态，但是文件夹，文件数值没有发生任何变化 ，打开团队盘，发现只有文件夹被创建，但是文件没有被复制，同样的操作使用gclone可以正常执行复制操作。

**Comment by iwestlin** [comment]
> 使用 ./copy 团队盘ID 团队盘ID -S
> 整体复制团队盘出现任务卡死，打开pm2 log查看日志 日志不断重复显示相同的任务执行状态，但是文件夹，文件数值没有发生任何变化 ，打开团队盘，发现只有文件夹被创建，但是文件没有被复制，同样的操作使用gclone可以正常执行复制操作。

https://github.com/iwestlin/gd-utils/issues/20#issuecomment-650868765

看下是不是同样的问题

**Comment by Manx98** [comment]
> > 使用 ./copy 团队盘ID 团队盘ID -S
> > 整体复制团队盘出现任务卡死，打开pm2 log查看日志 日志不断重复显示相同的任务执行状态，但是文件夹，文件数值没有发生任何变化 ，打开团队盘，发现只有文件夹被创建，但是文件没有被复制，同样的操作使用gclone可以正常执行复制操作。
> 
> [#20 (comment)](https://github.com/iwestlin/gd-utils/issues/20#issuecomment-650868765)
> 
> 看下是不是同样的问题

我在重新安装一遍

**Comment by Manx98** [comment]
> > > 使用 ./copy 团队盘ID 团队盘ID -S
> > > 整体复制团队盘出现任务卡死，打开pm2 log查看日志 日志不断重复显示相同的任务执行状态，但是文件夹，文件数值没有发生任何变化 ，打开团队盘，发现只有文件夹被创建，但是文件没有被复制，同样的操作使用gclone可以正常执行复制操作。
> > 
> > 
> > [#20 (comment)](https://github.com/iwestlin/gd-utils/issues/20#issuecomment-650868765)
> > 看下是不是同样的问题
> 
> 我在重新安装一遍

以下是报错信息

<--- Last few GCs --->

[14208:0x3cea2f0]   673194 ms: Mark-sweep 256.4 (257.9) -> 256.3 (257.9) MB, 1138.9 / 0.0 ms  (average mu = 0.184, current mu = 0.005) allocation failure scavenge might not succeed


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
 1: 0xa08900 node::Abort() [node]
 2: 0xa08d0c node::OnFatalError(char const*, char const*) [node]
 3: 0xb7ef5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb7f2d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2ba45  [node]
 6: 0xd5ad5a v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xd62210 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [node]
 8: 0xd71618 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 9: 0xd5405e v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
10: 0xd54324 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
11: 0xd49605 v8::internal::ItemParallelJob::Task::RunInternal() [node]
12: 0xd49a14 v8::internal::ItemParallelJob::Run() [node]
13: 0xd636c7 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
14: 0xd73bf4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
15: 0xd7480a  [node]
16: 0xd79a87 v8::internal::MarkCompactCollector::CollectGarbage() [node]
17: 0xd37fb9 v8::internal::Heap::MarkCompact() [node]
 5: 0xd2ba45  [node]
 6: 0xd5ad5a v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xd62210 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [node]
 8: 0xd71618 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 9: 0xd5405e v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
10: 0xd54324 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
11: 0xd49605 v8::internal::ItemParallelJob::Task::RunInternal() [node]
12: 0xd49a14 v8::internal::ItemParallelJob::Run() [node]
13: 0xd636c7 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
14: 0xd73bf4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
15: 0xd7480a  [node]
16: 0xd79a87 v8::internal::MarkCompactCollector::CollectGarbage() [node]
17: 0xd37fb9 v8::internal::Heap::MarkCompact() [node]
18: 0xd38cd3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
19: 0xd39805 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
20: 0xd3c2bc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
21: 0xd02e8b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
22: 0x104474e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
23: 0x13c9819  [node]
[1]    14208 abort      ./copy 0AD8eJqMxC7ZeUk9PVA 0ABnxTE-CZc3tUk9PVA -S

**Comment by Manx98** [comment]
> > > > 使用 ./copy 团队盘ID 团队盘ID -S
> > > > 整体复制团队盘出现任务卡死，打开pm2 log查看日志 日志不断重复显示相同的任务执行状态，但是文件夹，文件数值没有发生任何变化 ，打开团队盘，发现只有文件夹被创建，但是文件没有被复制，同样的操作使用gclone可以正常执行复制操作。
> > > 
> > > 
> > > [#20 (comment)](https://github.com/iwestlin/gd-utils/issues/20#issuecomment-650868765)
> > > 看下是不是同样的问题
> > 
> > 
> > 我在重新安装一遍
> 
> 以下是报错信息
> 
> <--- Last few GCs --->
> 
> [14208:0x3cea2f0] 673194 ms: Mark-sweep 256.4 (257.9) -> 256.3 (257.9) MB, 1138.9 / 0.0 ms (average mu = 0.184, current mu = 0.005) allocation failure scavenge might not succeed
> 
> <--- JS stacktrace --->
> Cannot get stack trace in GC.
> FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
> 1: 0xa08900 node::Abort() [node]
> 2: 0xa08d0c node::OnFatalError(char const*, char const*) [node]
> 3: 0xb7ef5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
> 4: 0xb7f2d9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
> 5: 0xd2ba45 [node]
> 6: 0xd5ad5a v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
> 7: 0xd62210 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [node]
> 8: 0xd71618 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
> 9: 0xd5405e v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
> 10: 0xd54324 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
> 11: 0xd49605 v8::internal::ItemParallelJob::Task::RunInternal() [node]
> 12: 0xd49a14 v8::internal::ItemParallelJob::Run() [node]
> 13: 0xd636c7 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
> 14: 0xd73bf4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
> 15: 0xd7480a [node]
> 16: 0xd79a87 v8::internal::MarkCompactCollector::CollectGarbage() [node]
> 17: 0xd37fb9 v8::internal::Heap::MarkCompact() [node]
> 5: 0xd2ba45 [node]
> 6: 0xd5ad5a v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
> 7: 0xd62210 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [node]
> 8: 0xd71618 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
> 9: 0xd5405e v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
> 10: 0xd54324 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
> 11: 0xd49605 v8::internal::ItemParallelJob::Task::RunInternal() [node]
> 12: 0xd49a14 v8::internal::ItemParallelJob::Run() [node]
> 13: 0xd636c7 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
> 14: 0xd73bf4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
> 15: 0xd7480a [node]
> 16: 0xd79a87 v8::internal::MarkCompactCollector::CollectGarbage() [node]
> 17: 0xd37fb9 v8::internal::Heap::MarkCompact() [node]
> 18: 0xd38cd3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
> 19: 0xd39805 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
> 20: 0xd3c2bc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
> 21: 0xd02e8b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
> 22: 0x104474e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
> 23: 0x13c9819 [node]
> [1] 14208 abort ./copy 0AD8eJqMxC7ZeUk9PVA 0ABnxTE-CZc3tUk9PVA -S

任务编号：1
源ID：0AD8eJqMxC7ZeUk9PVA (https://drive.google.com/drive/folders/0AD8eJqMxC7ZeUk9PVA)
目的ID：0ABnxTE-CZc3tUk9PVA (https://drive.google.com/drive/folders/0ABnxTE-CZc3tUk9PVA)
任务状态：copying
创建时间：2020-06-29 08:26:14
完成时间：未完成
目录进度：4246/4246
文件进度：0/217258
总大小：41.81 TB

**Comment by iwestlin** [comment]
@Manx98 是内存占用太大被强行退出了
解决办法看下readme

> 如果源文件夹的文件数非常多（一百万以上），请一定在命令行进行操作，因为程序运行的时候会把文件信息保存在内存中，文件数太多的话容易内存占用太多被nodejs干掉。可以像这样执行命令：

>  node --max-old-space-size=4096 count folder-id -S
这样进程就能最大占用4G内存了。
