### ISSUE TITLE
经常需要重复多次才能完整的复制完

### ISSUE THREAD

**Issue by TomatoFryEggs** [iwestlin/gd-utils#25]
是否可以配置成自动重试，直到所有文件复制成功。

**Comment by iwestlin** [comment]
你是怎么发现没复制完的呢？
如果是通过统计新文件夹的链接，那需要等一段时间，Google的数据库才会更新完毕，统计结果才比较完全。

如果确实少了文件，可以看下我刚刚更新的说明：
https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0

**Comment by TomatoFryEggs** [comment]
> 你是怎么发现没复制完的呢？
> 如果是通过统计新文件夹的链接，那需要等一段时间，Google的数据库才会更新完毕，统计结果才比较完全。
> 
> 如果确实少了文件，可以看下我刚刚更新的说明：
> https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0

新的说明解决了问题，谢谢。

但我还有两个问题：

1.对于之前未完成的任务，今天更新后，我选择继续任务还是有问题，但是新任务就没有问题了，如果我对旧的任务选择reload会造成文件重复吗？
2. 这个是什么原因造成的呢？如何避免这个无效的sa？

**Comment by iwestlin** [comment]
> > 你是怎么发现没复制完的呢？
> > 如果是通过统计新文件夹的链接，那需要等一段时间，Google的数据库才会更新完毕，统计结果才比较完全。
> > 如果确实少了文件，可以看下我刚刚更新的说明：
> > https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E9%87%8D%E8%A6%81%E6%9B%B4%E6%96%B0
> 
> 新的说明解决了问题，谢谢。
> 
> 但我还有两个问题：
> 
> 1.对于之前未完成的任务，今天更新后，我选择继续任务还是有问题，但是新任务就没有问题了，如果我对旧的任务选择restrart会造成文件重复吗？
> 2. 这个是什么原因造成的呢？如何避免这个无效的sa？

这下和sa没关系了。
是因为拷贝的时候会默认用到数据库中之前拷贝时收集的源文件夹信息，如果信息不全，那它就会拷贝不全的文件了。

可以在命令行 ./copy 命令后加一个 `-u` 参数，告诉程序无视数据库中的记录，强制从线上更新源文件夹的信息。

**Comment by iwestlin** [comment]
如果对旧任务restart，会重新创建一个文件夹进行拷贝任务，不会和之前创建的合在一起

**Comment by okaygh** [comment]
bot复制同一个链接的资源,即便有增减,也是直接显示已存在,如果有漏文件,难道要全部再跑一遍?

**Comment by iwestlin** [comment]
> bot复制同一个链接的资源,即便有增减,也是直接显示已存在,如果有漏文件,难道要全部再跑一遍?

可以在命令行 ./copy 命令后加一个 -u 参数，告诉程序无视数据库中的记录，强制从线上更新源文件夹的信息。
然后程序会提示你continue还是restart，选continue就是只拷贝未拷贝的文件了

**Comment by okaygh** [comment]
> > bot复制同一个链接的资源,即便有增减,也是直接显示已存在,如果有漏文件,难道要全部再跑一遍?
> 
> 可以在命令行 ./copy 命令后加一个 -u 参数，告诉程序无视数据库中的记录，强制从线上更新源文件夹的信息。
> 然后程序会提示你continue还是restart，选continue就是只拷贝未拷贝的文件了

bot无法做到是吗

**Comment by iwestlin** [comment]
是的，目前bot功能相比命令行少了很多

**Comment by iwestlin** [comment]
最新代码机器人已经支持 -u 参数

**Comment by vcan** [comment]
> 最新代码机器人已经支持 -u 参数

请问bot调用的时候应该怎么加这-u参数 复制链接以后 后面加-u吗？

**Comment by iwestlin** [comment]
不是的，输入链接后返回的两个按钮默认没有加参数。

要输入 `/copy folderID -u`

可以看看机器人的 /help

**Comment by vcan** [comment]
> 不是的，输入链接后返回的两个按钮默认没有加参数。
> 
> 要输入 `/copy folderID -u`
> 
> 可以看看机器人的 /help

之前的代码不是最新的，刚才更新了下代码 输入/help看到提示了，谢谢大佬！
