### ISSUE TITLE
增加shell 接口和api授权密码

### ISSUE THREAD

**Issue by dissipator** [iwestlin/gd-utils#26]
增加shell 接口
api授权密码，是不是所有人都可以API直接调用？

**Comment by iwestlin** [comment]
/api/gdurl/tgbot 这接口会有个用户名白名单的校验，但确实也有伪造请求的可能

/api/gdurl/count 是可以直接调用的，所以自己的网址注意要保密

后续可能在 config里加个参数

**Comment by iwestlin** [comment]
刚更新了下代码，增加了api授权密码，可以看看这里 https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E4%B8%93%E5%AE%B6%E8%AE%BE%E7%BD%AE

**Comment by dissipator** [comment]
给作者点赞
