### ISSUE TITLE
copy问题

### ISSUE THREAD

**Issue by psychopasss** [iwestlin/gd-utils#27]
copy 不会覆盖原来已经存在的同名文件夹吗？必须全量copy吗？

**Comment by iwestlin** [comment]
看看 ./copy -h 的说明吧

如果已存在的同名文件夹是这个程序创建的，那么数据库中会有记录，下次在命令行执行之前的拷贝命令，会提示你是否继续或重新开始。

**Comment by psychopasss** [comment]
我试试
