### ISSUE TITLE
关于node check.js报错

### ISSUE THREAD

**Issue by chinadk** [iwestlin/gd-utils#28]
大佬，执行node check.js后报错如下，这是啥原因啊。。。

Error: connect EINVAL 0.0.30.210:80 - Local (0.0.0.0:0)
    at internalConnect (net.js:923:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1063:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8) {
  errno: 'EINVAL',
  code: 'EINVAL',
  syscall: 'connect',
  address: '0.0.30.210',
  port: 80,
  config: {
    url: 'https://www.googleapis.com/oauth2/v4/token',
    method: 'post',
    data: 'client_id=省略&client_secret=省略&refresh_token=省略&grant_type=refresh_token',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/1.0.0',
      'Content-Length': 268
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by iwestlin** [comment]
你命令行代理有问题吧

试试 curl https://ipip.viegg.com 返回你代理的IP吗

**Comment by chinadk** [comment]
代理设置应该没有问题，您帮忙看看。
![image](https://user-images.githubusercontent.com/3849913/86075855-946c5600-babb-11ea-8b56-3b83a4591787.png)

**Comment by iwestlin** [comment]
你是在服务器上执行的还是本地啊，服务器的话不用设置代理的。

如果是本地，你有执行过
`http_proxy="YOUR_PROXY_URL" && https_proxy=$http_proxy && HTTP_PROXY=$http_proxy && HTTPS_PROXY=$http_proxy`
吗，YOUR_PROXY_URL 最好是 http:// 开头的，比如 `http://127.0.0.1:1086`

这里也有人遇到过 https://stackoverflow.com/questions/48939454/error-connect-einval-0-0-xx-xx80-local-0-0-0-00

**Comment by chinadk** [comment]
感谢！！！！果然是代理设置的问题。现在成功了。
