### ISSUE TITLE
复制文件的报错

### ISSUE THREAD

**Issue by Linon419** [iwestlin/gd-utils#29]
检查了有效的sa，但是出现以下错误

`0|server  | {"error":{"errors":[{"domain":"global","reason":"storageQuotaExceeded","message":"The user's Drive storage quota has been exceeded."}],"code":403,"message":"The user's Drive storage quota has been exceeded."}}`

**Comment by iwestlin** [comment]
> 检查了有效的sa，但是出现以下错误
> 
> `0|server | {"error":{"errors":[{"domain":"global","reason":"storageQuotaExceeded","message":"The user's Drive storage quota has been exceeded."}],"code":403,"message":"The user's Drive storage quota has been exceeded."}}`

这是你的团队盘超限额了。。好像一般有40w文件数的限制
