### ISSUE TITLE
重装了一遍以后无法复制

### ISSUE THREAD

**Issue by AAlexDing** [iwestlin/gd-utils#31]
报错：

0|server  | }
0|server  | TypeError: process.stdout.cursorTo is not a function
0|server  |     at print_progress (/root/gd-utils/src/gd.js:705:18)
0|server  |     at Timeout._onTimeout (/root/gd-utils/src/gd.js:158:5)
0|server  |     at listOnTimeout (internal/timers.js:531:17)
0|server  |     at processTimers (internal/timers.js:475:7)

**Comment by iwestlin** [comment]
> 报错：
> 
> 0|server | }
> 0|server | TypeError: process.stdout.cursorTo is not a function
> 0|server | at print_progress (/root/gd-utils/src/gd.js:705:18)
> 0|server | at Timeout._onTimeout (/root/gd-utils/src/gd.js:158:5)
> 0|server | at listOnTimeout (internal/timers.js:531:17)
> 0|server | at processTimers (internal/timers.js:475:7)

我就刚提交了这次bug就被你发现了。。
已经修复了，再更新下试试。

增加了命令行操作不换行更新进度的功能

> 报错：
> 
> 0|server | }
> 0|server | TypeError: process.stdout.cursorTo is not a function
> 0|server | at print_progress (/root/gd-utils/src/gd.js:705:18)
> 0|server | at Timeout._onTimeout (/root/gd-utils/src/gd.js:158:5)
> 0|server | at listOnTimeout (internal/timers.js:531:17)
> 0|server | at processTimers (internal/timers.js:475:7)

**Comment by AAlexDing** [comment]
大佬真6
