### ISSUE TITLE
执行node check.js返回[]

### ISSUE THREAD

**Issue by yukizero7** [iwestlin/gd-utils#32]
执行node check.js的时候返回
[]
执行node check.js -S也一样返回
[]

config.js内的const DEFAULT_TARGET，client_id，client_secret，refresh_token都正确填写的

**Comment by iwestlin** [comment]
是不是你的个人盘没有文件啊？ 
除了 [] 还有别的输出吗？

另外是不是命令行没翻出去？

`-S`参数对 check.js 无效的，它只会使用个人帐号的授权

**Comment by yukizero7** [comment]
> 是不是你的个人盘没有文件啊？
> 除了[]还有别的输出吗？
> 
> 另外是不是命令行没翻出去？
> 
> `-S`参数对check.js无效的，它只会使用个人帐号的授权
