### ISSUE TITLE
下面的错误是什么原因，目的盘超限了？

### ISSUE THREAD

**Issue by sztuxp** [iwestlin/gd-utils#38]
下面的错误是什么原因，目的盘超限了？
源和目的的SA权限都检查通过了
复制文件失败，文件id: 1Q5X6LhLQV8MSaQZJWv-Jd-uq3-Ddzn-f
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
复制文件失败，文件id: 1b5bvb0lt4E33pZFAoZZ7YxQFjU8Irt1-
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared drive has

**Comment by iwestlin** [comment]
是的，好像团队盘有40w文件数的限制
