### ISSUE TITLE
usageLimits

### ISSUE THREAD

**Issue by eamon-zhang** [iwestlin/gd-utils#39]
![TIM截图20200701083448](https://user-images.githubusercontent.com/30527166/86190052-f093b080-bb75-11ea-9af0-d7e0eaa6ee3e.png)
还未复制文件 读取目录就显示限制了  总共900个服务号。 有的只是访问过快并未达到流量限制的服务号也无法使用

**Comment by iwestlin** [comment]
你有剔除过无效的sa吗？

还有，你是机器人操作还是命令行的？如果是机器人，新上传了sa文件以后需要pm2 reload server更新下进程

**Comment by eamon-zhang** [comment]
剔除过  命令行 没有新的上传sa  这些sa我感觉只是单纯的访问评率过快就被办了  可以sa暴力循环几遍

**Comment by iwestlin** [comment]
命令行操作的时候最后加上了 `-S` 参数吗，不加的话默认会用到个人的授权信息进行请求。

另外sa目录下的授权文件是不是以json结尾的啊，程序只会读json。可以 ls sa | grep json | wc -l 看看数量是不是900个

**Comment by iwestlin** [comment]
feel free to reopen
