### ISSUE TITLE
tgbot输入命令无反应

### ISSUE THREAD

**Issue by fcki1984** [iwestlin/gd-utils#4]
- node check.js成功获取文件目录
- 已获取token：123...:aEfeg....
- config.js中添加了token，bot白名单格式为：tg_whitelist: 't.me/username',
- 共享文件夹数量获取成功：curl 'YOUR_WEBSITE_URL/api/gdurl/count?fid=共享文件夹id'
- ssh中输入命令：curl -F "url=https://my-site-url/api/gdurl/tgbot" 'https://api.telegram.org/bot123...:aEfeg..../setWebhook'
返回消息：{"ok":true,"result":true,"description":"Webhook was set"}
- bot中输入命令“/help”无反应

**Comment by iwestlin** [comment]
tg_whitelist: 't.me/username'

这里不是让你照着填的，意思是改成自己的tg用户名，就是 t.me/后面那串字符

**Comment by iwestlin** [comment]
比如我的tg主页是 https://t.me/viegg
那么我的用户名就是 viegg

**Comment by fcki1984** [comment]
我就是改成了我的用户名，就是@后面的那个，比如t.me/ukg

**Comment by iwestlin** [comment]
我再确认下，你是填了 `ukg` 对吧，没填 `t.me/ukg`吧？

白名单不能注释掉的，否则接到tg的请求会报错。

可以命令行执行`pm2 logs`看实时日志，日志文件的位置在 `~/.pm2/log/`里，如果还不行请附上报错信息。tg联系也可

**Comment by iwestlin** [comment]
```
tg_whitelist: ['viegg']
```
要这样填，它是个数组，不是个字符串，可以支持多个用户名的，比如

['aaa', 'bbb']

**Comment by fcki1984** [comment]
解决了。之前的白名单写错了，修改config.js后，需要重启serve.js。

**Comment by iwestlin** [comment]
是的，修改代码后，执行`pm2 reload server`才能生效

**Comment by advpetc** [comment]
使用的一件脚本配置的tg，我也遇到了同样的问题。白名单的配置是正确的，也reload过server了，但是还是\help之后没有任何结果。有个小的问题不知道是不是导致无法工作原因，在运行脚本的时候遇到了：nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)这个问题

**Comment by iwestlin** [comment]
> 使用的一件脚本配置的tg，我也遇到了同样的问题。白名单的配置是正确的，也reload过server了，但是还是\help之后没有任何结果。有个小的问题不知道是不是导致无法工作原因，在运行脚本的时候遇到了：nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)这个问题

因为已经有程序占用了80端口，导致nginx配置没有生效。

**Comment by advpetc** [comment]
谢谢大佬，我用pm2看了一下是之前的server占用了80，但是我kill之后再relaunch还是\help没反应...大佬知道会是什么原因吗？

**Comment by iwestlin** [comment]
> 谢谢大佬，我用pm2看了一下是之前的server占用了80，但是我kill之后再relaunch还是\help没反应...大佬知道会是什么原因吗？

要停止 pm2守护的进程可以执行 pm2 stop server

如果要修改它占用的端口，改完后需要 pm2 reload server重启进程

你可以 pm2 logs 看看实时日志，如果tg的请求被转发到了程序监听的端口，是会有记录的。

如果没看到，说明流量没转发过来，再检查下nginx的配置

**Comment by advpetc** [comment]
感谢大佬，这是我的nginx配置：
```
server {
listen 80;
server_name bot.peterchen.xyz;
location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:23333/;
    }
}
```
用pm2 logs看实时日志貌似也没有任何流量，如果大佬有空能再帮小白一下吗

**Comment by advpetc** [comment]
修好了，原来是cf那边的问题。。。改成flexible就好了。。。具体见：https://community.cloudflare.com/t/community-tip-fixing-error-521-web-server-is-down/42461
