### ISSUE TITLE
关于重新开始任务

### ISSUE THREAD

**Issue by singleWan** [iwestlin/gd-utils#40]
如果我开始一个任务，发现目录数和文件数不全，怎么重新开始任务

**Comment by iwestlin** [comment]
@singleWan 

> 复制结束后，如果最后输出的消息里有 未读取完毕的目录ID，只需要在命令行执行上次同样的拷贝命令，选continue即可继续。

> 如果你成功复制完以后，统计新的文件夹链接发现文件数比源文件夹少，说明Google正在更新数据库，请给它一点时间。。一般等半小时再统计数据会比较完整。

看下readme吧
如果用的是最新代码，且剔除过无效的sa，基本是不会遇到不全的情况的。。
