### ISSUE TITLE
Trojan部署了伪装站点对百宝箱的影响

### ISSUE THREAD

**Issue by Floatingdream12** [iwestlin/gd-utils#43]
您好，我的vps上已经部署了Trojan，做了伪装站点，如果我想安装百宝箱，我看您的介绍说百宝箱也需要起一个web服务，会和Trojan的伪装站点冲突吗？如果可能会的话我需要怎么办，麻烦具体介绍一下

**Comment by iwestlin** [comment]
不了解Trojan
nginx本身可以多个server监听80端口
理论上它可以把流量转发给任意应用程序
