### ISSUE TITLE
复制失败，失败消息：创建目录失败，请检查您的帐号是否有相应的权限

### ISSUE THREAD

**Issue by yfnok** [iwestlin/gd-utils#44]
请问这个是什么错误
哪里可以看日志吗

**Comment by iwestlin** [comment]
pm2 logs看实时日志

或者命令行 ./copy folder-id -S 命令看看什么输出

**Comment by tommyxps** [comment]
我也有这个问题

看log 是目标团队盘超过文件数量limit 了，换了个团队盘，再把sa 添加为content manager ，问题解决

**Comment by iwestlin** [comment]
也有可能是文件数超了团队盘40万限制。

如果超了，最新代码会明确返回这个信息。同时解决了很多问题，建议更新下。
