### ISSUE TITLE
copy 文件夹未复制完就复制文件

### ISSUE THREAD

**Issue by SionInory** [iwestlin/gd-utils#45]
复制比较多的文件时，文件夹复制不全。  
Continue时无法复制文件夹。  
![Screenshot_2020-07-02-06-19-18-605_com termux_1593642106658](https://user-images.githubusercontent.com/45240105/86297063-f0a2b780-bc2c-11ea-86f4-70d0a3aa68cd.jpg)

**Comment by iwestlin** [comment]
因为源文件信息已经存在数据库中了，如果命令不加 `-u`就会从数据库中取，加了后就强制从线上获取了

**Comment by SionInory** [comment]
它为什么会有文件夹未创建完毕就开始复制文件？

**Comment by iwestlin** [comment]
> 它为什么会有文件夹未创建完毕就开始复制文件？

你之前执行过相同的命令吗，如果执行过，它监测到之前创建了文件夹就不会再创建了

**Comment by SionInory** [comment]
执行过，但是我查看gd发现目录结构缺损，缺损目录里的文件都到根目录下了。文件数量少的时候没有问题，一多了就出现问题。是不是也是内存不够？

**Comment by iwestlin** [comment]
> 执行过，但是我查看gd发现目录结构缺损，缺损目录里的文件都到根目录下了。文件数量少的时候没有问题，一多了就出现问题。是不是也是内存不够？

你有检查过sa的权限吗？ ./validate-sa.js -h 那个

如果用到了没有权限的sa，它没有权限创建新文件夹，然后后面复制的文件找不到文件夹默认就会复制到根目录了

**Comment by iwestlin** [comment]
十万级的文件我试过很多次都没问题的，百万级操作看看readme吧

**Comment by SionInory** [comment]
好的，谢谢。可能是我用android上的termux装的nodejs，系统环境比较极端，导致出现这种情况。
