### ISSUE TITLE
copy失败

### ISSUE THREAD

**Issue by mymoonyue** [iwestlin/gd-utils#46]
help成功了，然后copy返回401可能是什么原因呢。

**Comment by iwestlin** [comment]
没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下

具体报错日志什么样？

**Comment by mymoonyue** [comment]
> 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> 
> 具体报错日志什

**Comment by mymoonyue** [comment]
> 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> 
> 具体报错日志什么样？

多谢！将credentials.json文件加到sa文件夹就可以了。

**Comment by iwestlin** [comment]
> > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > 具体报错日志什么样？
> 
> 多谢！将credentials.json文件加到sa文件夹就可以了。

别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。

**Comment by mymoonyue** [comment]
> > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > 具体报错日志什么样？
> > 
> > 
> > 多谢！将credentials.json文件加到sa文件夹就可以了。
> 
> 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。

我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm

**Comment by huahanshou** [comment]
> > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > 具体报错日志什么样？
> > > 
> > > 
> > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > 
> > 
> > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> 
> 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm

我昨天也是一样的问题，原因是你追加的1000个sa.json他们都是相当于独立的账号，
你没有赋给这些账号拷贝到的目录的相应的读写权限。权限追加之后就OK了

**Comment by iwestlin** [comment]
> > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > 具体报错日志什么样？
> > > 
> > > 
> > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > 
> > 
> > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> 
> 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm

那是因为程序会一直试一直试直到选到能用的token为止。。

**Comment by mymoonyue** [comment]
> > > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > > 具体报错日志什么样？
> > > > 
> > > > 
> > > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > > 
> > > 
> > > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> > 
> > 
> > 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm
> 
> 我昨天也是一样的问题，原因是你追加的1000个sa.json他们都是相当于独立的账号，
> 你没有赋给这些账号拷贝到的目录的相应的读写权限。权限追加之后就OK了
> 
> 每个sa.json里都会有个邮箱，把他们放到一个group里也好，把邮箱账号都抽取出来追加权限也好都可以

您是说我的sa.json没有网盘的权限，还是说把sa.json加到sa文件夹后服务器上需要更新？我的sa加了群组的，有团队盘的权限。

**Comment by mymoonyue** [comment]
> > > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > > 具体报错日志什么样？
> > > > 
> > > > 
> > > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > > 
> > > 
> > > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> > 
> > 
> > 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm
> 
> 那是因为程序会一直试一直试直到选到能用的token为止。。

所以跟我后加的这个credentials.json有关系嘛。我之前加的sa.json都是有权限的呀，您让我加sa授权文件我以为指的是credentials.json，结果加了以后果然能正常使用了哈哈。

**Comment by iwestlin** [comment]
@mymoonyue gd-utils目录下有个 validate-sa.js，这个脚本是用来检查你的sa到底有没有权限的，
可以 ./validate-sa.js -h 看看使用说明

**Comment by huahanshou** [comment]
> > > > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > > > 具体报错日志什么样？
> > > > > 
> > > > > 
> > > > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > > > 
> > > > 
> > > > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> > > 
> > > 
> > > 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm
> > 
> > 
> > 我昨天也是一样的问题，原因是你追加的1000个sa.json他们都是相当于独立的账号，
> > 你没有赋给这些账号拷贝到的目录的相应的读写权限。权限追加之后就OK了
> > 每个sa.json里都会有个邮箱，把他们放到一个group里也好，把邮箱账号都抽取出来追加权限也好都可以
> 
> 您是说我的sa.json没有网盘的权限，还是说把sa.json加到sa文件夹后服务器上需要更新？我的sa加了群组的，有团队盘的权限。

是的，sa.json的账号，没有网盘的操作权限。
程序里有提供sa账号权限认证的功能。
'./validate-sa.js 写入的目录ID'
大佬的教程里也有写。可以好好参考下

**Comment by mymoonyue** [comment]
> @mymoonyue gd-utils目录下有个 validate-sa.js，这个脚本是用来检查你的sa到底有没有权限的，
> 可以 ./validate-sa.js -h 看看使用说明

好的多谢，我已经在查了

**Comment by mymoonyue** [comment]
> > > > > > > 没有相关权限。检查下sa目录下有SA授权文件吗，如果是新增的文件需要 pm2 reload server下
> > > > > > > 具体报错日志什么样？
> > > > > > 
> > > > > > 
> > > > > > 多谢！将credentials.json文件加到sa文件夹就可以了。
> > > > > 
> > > > > 
> > > > > 别这样操作啊，credentials.json是你的个人授权文件，sa目录下本意是放sa的授权文件的。。
> > > > 
> > > > 
> > > > 我之前已经加了1000个sa.json文件，然后count会提示信息获取失败，copy会提示复制失败，失败消息：Request failed with status code 401。刚才把credentials.json加进去就可以用了。emmmmm
> > > 
> > > 
> > > 我昨天也是一样的问题，原因是你追加的1000个sa.json他们都是相当于独立的账号，
> > > 你没有赋给这些账号拷贝到的目录的相应的读写权限。权限追加之后就OK了
> > > 每个sa.json里都会有个邮箱，把他们放到一个group里也好，把邮箱账号都抽取出来追加权限也好都可以
> > 
> > 
> > 您是说我的sa.json没有网盘的权限，还是说把sa.json加到sa文件夹后服务器上需要更新？我的sa加了群组的，有团队盘的权限。
> 
> 是的，sa.json的账号，没有网盘的操作权限。
> 程序里有提供sa账号权限check的功能。
> './validate-sa.js 写入的目录ID'
> 大佬的教程里也有写。可以好好参考下

谢谢谢谢
