### ISSUE TITLE
测试 curl 'xxxx/api/gdurl/count?fid=1LggSuwI1n40bcD5tQ13wS0M6wg' 输出错误

### ISSUE THREAD

**Issue by tommyxps** [iwestlin/gd-utils#48]
执行 倒数第二步 curl 'YOUR_WEBSITE_URL/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg' 后，出现以下提示，并没有对文件进行统计，请问什么原因？

<!doctype html><html lang="en"><head><meta http-equiv="content-type" content="text/html;charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"><title></title><script src="https://www.google.com/adsense/domains/caf.js" type="text/javascript"></script><noscript><style>#content-main{display:none}</style><div>For full functionality of this site it is necessary to enable JavaScript. Here are the <a target="_blank" href="https://www.enable-javascript.com/">instructions how to enable JavaScript in your web browser</a>.</div></noscript></head><body><div id="contentMain"></div><script type="text/javascript" src="https://d1hi41nc56pmug.cloudfront.net/static/js/main.314a8987.js"></script></body></h

**Comment by tommyxps** [comment]
把 web url 换成 curl 'http://127.0.0.1:23333/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg' 即可

**Comment by iwestlin** [comment]
你的请求根本没有到程序监听的端口啊，如果到了会返回 `gd-utils 成功启动`的消息

你用的nginx吗？检查下nginx的配置吧

**Comment by tommyxps** [comment]
> 你的请求根本没有到程序监听的端口啊，如果到了会返回 `gd-utils 成功启动`的消息
> 
> 你用的nginx吗？检查下nginx的配置吧

感谢，查看之前close 的 issue， 换成IP 就好了，显示 成功启动
