### ISSUE TITLE
大佬能不能做成colab可用的

### ISSUE THREAD

**Issue by orange2008** [iwestlin/gd-utils#50]
没有vps，我看autorclone和gclone都是colab上的，colab网速快，谷歌服务器，能不能做个colab可用的

**Comment by iwestlin** [comment]
我没用过colab的……你可以在标题里加个 help wanted的tag看看谁有时间搞吧。。

**Comment by iErics** [comment]
我试过在colab上部署，但是在colab上安装node.js出现问题，没有找到解决方法，不知道有没有大佬能解决。

**Comment by iErics** [comment]
Colab部署没有问题，运行一下代码。
`!curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
!sudo apt-get install -y nodejs
!git clone https://github.com/iwestlin/gd-utils && %cd /content/gd-utils
!npm install --unsafe-perm=true --allow-root`

**Comment by yaoxinghuo** [comment]
colab就能用一个小时，我觉得没啥意义

**Comment by iErics** [comment]
> colab就能用一个小时，我觉得没啥意义

谁说colab只能用一个小时了

**Comment by orange2008** [comment]
> Colab部署没有问题，运行一下代码。
> 
> !curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
> !sudo apt-get install -y nodejs
> !git clone https://github.com/iwestlin/gd-utils
> %cd /content/gd-utils
> !npm install --unsafe-perm=true --allow-root

帮你部署好了
https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq

**Comment by orange2008** [comment]
https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq
从nodejs部署到拷贝，完全可以使用的状态。

**Comment by iwestlin** [comment]
@orange2008 点进去需要权限？

**Comment by orange2008** [comment]
> @orange2008 点进去需要权限？

不用啊，不是colab的链接吗？
ipynb文件我发你邮箱了。

**Comment by orange2008** [comment]
> > @orange2008 点进去需要权限？
> 
> 不用啊，不是colab的链接吗？
> ipynb文件我发你邮箱了。



> @orange2008 点进去需要权限？

**Comment by iwestlin** [comment]
@orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
然后提示需要权限。。

我没用过colab，那个文件是直接部署上去就能用了吗？

**Comment by orange2008** [comment]
> @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> 然后提示需要权限。。
> 
> 我没用过colab，那个文件是直接部署上去就能用了吗？

把这个ipynb文件保存到你的谷歌盘里，然后进入https://colab.research.google.com/
打开这个文件就能用了。

**Comment by orange2008** [comment]
> @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> 然后提示需要权限。。
> 
> 我没用过colab，那个文件是直接部署上去就能用了吗？

这个是共享链接
https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq?usp=sharing

**Comment by iwestlin** [comment]
> > @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> > 然后提示需要权限。。
> > 我没用过colab，那个文件是直接部署上去就能用了吗？
> 
> 这个是共享链接
> https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq?usp=sharing

多谢，我把这个链接加到readme

**Comment by orange2008** [comment]
> @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> 然后提示需要权限。。
> 
> 我没用过colab，那个文件是直接部署上去就能用了吗？

在colab里每个代码框前面有个播放键之类的东西，点它就行。

**Comment by orange2008** [comment]
> > > @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> > > 然后提示需要权限。。
> > > 我没用过colab，那个文件是直接部署上去就能用了吗？
> > 
> > 
> > 这个是共享链接
> > https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq?usp=sharing
> 
> 多谢，我把这个链接加到readme

ok，最好是注明一下要保存到自己的云端硬盘，因为这个链接里的记录所有人都能看到。

**Comment by orange2008** [comment]
> > > @orange2008 我点进去会跳转到 https://drive.google.com/file/u/0/d/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq/edit
> > > 然后提示需要权限。。
> > > 我没用过colab，那个文件是直接部署上去就能用了吗？
> > 
> > 
> > 这个是共享链接
> > https://colab.research.google.com/drive/1i1W9nAzgiDtfA_rmTBcpMpwxVUhwgLsq?usp=sharing
> 
> 多谢，我把这个链接加到readme

保存到自己的就不会

**Comment by iwestlin** [comment]
好的

**Comment by orange2008** [comment]
> 好的

emm，好像少讲了一个东西，上面有nodejs的安装，这里也要安装nodejs，只是一个按钮的事。

**Comment by iwestlin** [comment]
。。我这就加上

**Comment by orange2008** [comment]
> 。。我这就加上

恩

**Comment by iwestlin** [comment]
@orange2008 似乎这里需要修改下？
```
from google.colab import drive
drive.mount("/content/drive")
!cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
```
我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

**Comment by orange2008** [comment]
> @orange2008 似乎这里需要修改下？
> 
> ```
> from google.colab import drive
> drive.mount("/content/drive")
> !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> ```
> 
> 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

好的，已修改。

**Comment by orange2008** [comment]
> @orange2008 似乎这里需要修改下？
> 
> ```
> from google.colab import drive
> drive.mount("/content/drive")
> !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> ```
> 
> 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

之前有想过这方面的问题，但是在colab里可能会卡住？现在我去试验以下。

**Comment by orange2008** [comment]
> @orange2008 似乎这里需要修改下？
> 
> ```
> from google.colab import drive
> drive.mount("/content/drive")
> !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> ```
> 
> 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

修改好了，只复制用户accounts文件夹下的的json文件，但是执行速度非常慢，目前未知原因。

**Comment by orange2008** [comment]
> @orange2008 似乎这里需要修改下？
> 
> ```
> from google.colab import drive
> drive.mount("/content/drive")
> !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> ```
> 
> 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

好了，我又优化了一下，然后加上了每一步是用来做什么的。刚刚是卡在连接代码执行器上了...

**Comment by orange2008** [comment]
> > @orange2008 似乎这里需要修改下？
> > ```
> > from google.colab import drive
> > drive.mount("/content/drive")
> > !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> > ```
> > 
> > 
> > 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的
> 
> 之前有想过这方面的问题，但是在colab里可能会卡住？现在我去试验以下。

是因为加了双引号，通配符识别不出来，只能先复制到临时的文件夹，然后用通配符把json文件筛选出来，复制到gd-utils的sa文件夹，然后删除临时的文件夹。

**Comment by orange2008** [comment]
> @orange2008 似乎这里需要修改下？
> 
> ```
> from google.colab import drive
> drive.mount("/content/drive")
> !cp -rf "/content/drive/My Drive/accounts/" /content/gd-utils/sa/
> ```
> 
> 我执行以后它把accounts文件夹整个复制到sa目录下了，而gd-utils只会读sa目录下的json文件，不会递归读子目录中的

总而言之现在已经可以用了，不过试了一下，你这个复制是真的快。colab从配置nodejs到开始拷贝中间半分钟到两分钟可以搞定。现在去重我搞不定，nodejs我不懂，colab不允许我们用方向键选择选项，所以去重我没有弄，也就从此告别断点续传.不过colab和你的工具这么快也不需要断点续传XD。

**Comment by iwestlin** [comment]
```
os.system("node --max-old-space-size=8192 /content/gd-utils/count " + fileid + " > stat.txt")
```
这里也需要改下，count命令没有加 -S

我等下把操作步骤录个屏

**Comment by orange2008** [comment]
> ```
> os.system("node --max-old-space-size=8192 /content/gd-utils/count " + fileid + " > stat.txt")
> ```
> 
> 这里也需要改下，count命令没有加 -S
> 
> 我等下把操作步骤录个屏

我去加。

**Comment by orange2008** [comment]
> ```
> os.system("node --max-old-space-size=8192 /content/gd-utils/count " + fileid + " > stat.txt")
> ```
> 
> 这里也需要改下，count命令没有加 -S
> 
> 我等下把操作步骤录个屏

本来想做让用户选择使不使用SA的，但是由于某些原因（我懒）我没做，有可能后面我会做。

**Comment by orange2008** [comment]
> ```
> os.system("node --max-old-space-size=8192 /content/gd-utils/count " + fileid + " > stat.txt")
> ```
> 
> 这里也需要改下，count命令没有加 -S
> 
> 我等下把操作步骤录个屏

嗯嗯，colab比较简单，即开即用。虽然只支持CLI，不支持tgbot之类的功能，但是对于有些没有vps的用户还是比较友好的。（无意冒犯？）

**Comment by iwestlin** [comment]
@orange2008 录好了，https://drive.google.com/drive/u/1/folders/19T37ARH7M1h67JGYanKp9LvORjJLEp_x
你要不要享受下频道发链接的乐趣？😄

**Comment by orange2008** [comment]
> @orange2008 录好了，https://drive.google.com/drive/folders/19T37ARH7M1h67JGYanKp9LvORjJLEp_x
> 你要不要享受下频道发链接的乐趣？😄

好啊😄

**Comment by haohaosteven** [comment]
可以先裝個rclone 然後用copy指令比較快
!curl https://rclone.org/install.sh | sudo bash
from google.colab import drive
drive.mount('/content/drive')
!rclone copy "/content/drive/My Drive/accounts/" "/content/gd-utils/sa/"

**Comment by orange2008** [comment]
> 可以先裝個rclone 然後用copy指令比較快
> !curl https://rclone.org/install.sh | sudo bash
> from google.colab import drive
> drive.mount('/content/drive')
> !rclone copy "/content/drive/My Drive/accounts/" "/content/gd-utils/sa/"

这样就无法满足只拷贝json文件了，如果拷贝到临时文件夹的话还不如直接copy😄

**Comment by orange2008** [comment]
> @orange2008 录好了，https://drive.google.com/drive/folders/19T37ARH7M1h67JGYanKp9LvORjJLEp_x
> 你要不要享受下频道发链接的乐趣？😄

我后来又更新了一下，如果colab闲置90分钟的话就会自动断开，所以我写了一段js来防止断开。

**Comment by orange2008** [comment]
```javascript
function ConnectButton(){
    console.log("Connection renewed."); 
    document.querySelector("#connect").click() 
}
setInterval(ConnectButton,60000);
```

**Comment by iErics** [comment]
可以看下我的这个[https://colab.research.google.com/github/iErics/gd-utils/blob/master/Colab_gd_utils.ipynb](url)

**Comment by iErics** [comment]
可以看下我的这个[https://colab.research.google.com/github/iErics/gd-utils/blob/master/Colab_gd_utils.ipynb](url)

**Comment by jason8303** [comment]
那个关于sa的权限错误 提示，在colab上要怎么操作哦，我小白，谢谢

**Comment by ITtest1** [comment]
能不能把colab改成可以用本身賬號複製,我要複製的文件是在別人跟我分享的共享網盤裡,而我無法在別人的網盤+入自己的SA.
