### ISSUE TITLE
关于专家设置

### ISSUE THREAD

**Issue by komosk** [iwestlin/gd-utils#52]
大大您好
请教专家设置中的const ROUTER_PASSKEY = 'your-custom-passkey',
要如何查询并获取passkey呢？
非常感谢

**Comment by iwestlin** [comment]
这个是你自己随便设置的，目的是为了防止别人调用你这个接口。

因为我观察到有很多人公开贴出了自己的接口地址。。所以把这个接口默认做成关闭了。

如果你需要使用这个接口，可以在config.js里设置这个值并导出

然后pm2 reload server 生效后，可以 /api/gdurl/count?fid=folder-id&passkey=你在config里设置的值
这样调用这个接口。

由于只有设置了这个值才能开启这个接口，而别人又不知道你设置的这个值，所以就算接口网址泄露也能保障不被别人调用
