### ISSUE TITLE
这个是我网络问题吗，还是并发请求设的大了，我有200个sa

### ISSUE THREAD

**Issue by markwhitey** [iwestlin/gd-utils#53]
ient network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | Client network socket disconnected before secure TLS connection was established
0|server  | 12:25:51 | 已复制文件数 610 | 网络请求 进行中100/排队103359

**Comment by iwestlin** [comment]
是你的并行请求太多了。
20已经足够满足大多数使用情况了。

因为之前有人反馈timeout的日志很烦人，我就去掉了timeout的报错，不然你会看到一片红。。

我详细解释下`PARALLEL_LIMIT`的含义。
假设它设为20，就表示，如果需要的话，会最多同时存在 20个正在进行的网络请求。
如果每个请求花半秒完成，那么每秒就有40个请求完成。

假设你要复制1万个文件，那么理想情况只需要 10000/40/60 分钟，四分多钟不愿意等等吗……
