### ISSUE TITLE
建议拷贝目标可设置少套一层母文件夹

### ISSUE THREAD

**Issue by cxumol** [iwestlin/gd-utils#55]
`gd-utils/copy`  的  `-n` , 可以类比于 AutoRclone  的  `-dp`, 都是设置目标文件夹名称｡  
但不同的是, 当 `gd-utils/copy` 未指定  `-n` 时, 默认用源文件夹本名, 而当 AutoRclone 未指定  `-dp` 时, 默认不套那一层母文件夹

缺失 "目的地少套一层母文件夹" 功能会造成一些困难, 比如,  
从 "团队盘 A" 同步到 " 团队盘 B",  
期望的结果是 "团队盘 A/文件夹 A" ==> "团队盘 B/文件夹 A",  
但实际效果为 "团队盘 A/文件夹 A" ==> "团队盘 B/Drive/文件夹 A" 

按照现有的拷贝逻辑, 结果应该是 "团队盘 B/团队盘 A/文件夹 A" , 但实际上,  "Drive" 确实是程序取得的 "团队盘 A" 根目录名字, 这到是另外一个问题了｡ 

希望  `gd-utils/copy` 可以实现 "团队盘 A/文件夹 A" ==> "团队盘 B/文件夹 A" 这样的效果
 (我是命令行用户, 暂未尝试 bot)

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/commit/cde2f39bff6b54e5cf876a2f534d293c2a72386b
已经实现，给 ./copy 加了个 -D 的选项

可以在项目文件夹下 git pull 更新最新代码
