### ISSUE TITLE
curl 'YOUR_WEBSITE_URL/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg' 返回的是html内容

### ISSUE THREAD

**Issue by cj1354421348** [iwestlin/gd-utils#6]
输入curl '我的ip/api/gdurl/count?fid=124pjM5LggSuwI1n40bcD5tQ13wS0M6wg' 返回了下面的内容
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
还有一个就是nginx的配置文件我要修改什么地方吗 就修改了ip
server {
  listen 80;
  server_name 我的ip;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:23333/;
  }
}
我没有使用域名 听其他人说需要htmls加证书才能使用
感谢作者

**Comment by iwestlin** [comment]
你在vps上执行下试试看？把`我的ip`换成 `http://127.0.0.1:23333`

**Comment by cj1354421348** [comment]
换了就可以了 能不能教下我要怎么改呢

**Comment by cj1354421348** [comment]
作者已经更新了
