### ISSUE TITLE
7月4日更新后，tg复制完成的提示没有了？

### ISSUE THREAD

**Issue by artxia** [iwestlin/gd-utils#60]
今天拉取更新后，复制几个文件，都没有提示。我一直以为复制失败，重新复制了好几次。。
这个提示还蛮重要的，作者将这个提示删除了？

**Comment by iwestlin** [comment]
没删除，只是换成完成后发送进度详情了。可能复制的太快，开始复制的消息还没来得及发，完成的消息就已经到了。。你可以换个文件多点的任务试试

**Comment by artxia** [comment]
> 没删除，只是换成完成后发送进度详情了。可能复制的太快，开始复制的消息还没来得及发，完成的消息就已经到了。。你可以换个文件多点的任务试试

明白了，回到了最初的提示样式 “任务状态：finished” 。是我疏忽大意了
