### ISSUE TITLE
请问这是什么资源不够，已经更新到了最新版本了

### ISSUE THREAD

**Issue by sztuxp** [iwestlin/gd-utils#61]
8:31:39 | 已创建目录数 689 | 网络请求 进行中7/排队203{"error":{"errors":[{"domain":"global","reason":"internalError","message":"Internal Error"}],"code":500,"message":"Internal Error"}}
创建目录重试中： 管理 重试次数： 1
19:15:04 | 已创建目录数 16697 | 网络请求 进行中7/排队1759{"error":{"errors":[{"domain":"global","reason":"internalError","message":"Internal Error"}],"code":500,"message":"Internal Error"}}
创建目录重试中： 利维尔和我 重试次数： 1
19:15:51 | 已创建目录数 16952 | 网络请求 进行中7/排队1504{"error":{"errors":[{"domain":"global","reason":"internalError","message":"Internal Error"}],"code":500,"message":"Internal Error"}}
创建目录重试中： 信任 重试次数： 1
19:53:14 | 已创建目录数 29761 | 网络请求 进行中1/排队0264
开始复制文件，总数： 258144

<--- Last few GCs --->

[526:0x43aa330]  5050915 ms: Mark-sweep 256.0 (257.5) -> 256.0 (257.8) MB, 652.5 / 0.0 ms  (average mu = 0.555, current mu = 0.001) allocation failure scavenge might not succeed
[526:0x43aa330]  5051566 ms: Mark-sweep 256.4 (257.8) -> 256.4 (257.8) MB, 650.5 / 0.0 ms  (average mu = 0.378, current mu = 0.001) allocation failure scavenge might not succeed

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
 1: 0xa0bb60 node::Abort() [node]
 2: 0xa0bf6c node::OnFatalError(char const*, char const*) [node]
 3: 0xb820fe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb82479 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2ee35  [node]
 6: 0xd5e14a v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xd65600 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [node]
 8: 0xd74a08 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 9: 0xd5744e v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
10: 0xd57714 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
11: 0xd4c9f5 v8::internal::ItemParallelJob::Task::RunInternal() [node]
12: 0xd4ce04 v8::internal::ItemParallelJob::Run() [node]
13: 0xd66ab7 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
14: 0xd76fe4 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
15: 0xd77bfa  [node]
16: 0xd7ce77 v8::internal::MarkCompactCollector::CollectGarbage() [node]
17: 0xd3b3a9 v8::internal::Heap::MarkCompact() [node]
18: 0xd3c0c3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
19: 0xd3cbf5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
20: 0xd3f6ac v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
21: 0xd0615b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
22: 0x1047d9e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
23: 0x13cce79  [node]
Aborted

**Comment by iwestlin** [comment]
是进程占用内存过大被node强行杀死了。
这里有相关讨论：https://github.com/nodejs/node/issues/10137

解决办法：  
- 复制大量文件时，用命令行操作，加上一个特殊的参数 `node --max-old-space-size=4096 ./count folder-id -S` 表示最多运行进程占用4G内存
- 或者，`pm2 delete server`后，在gd-utils目录下执行`pm2 start server.js --node-args="--max-old-space-size=4096"`，这样 pm2 守护的进程（tg机器人相关）也可以占用4G内存了

**Comment by sztuxp** [comment]
请问这个是虚拟内存还是真实内存？我的VPS内存为1G，已经算比较大的了，那是不是只能设置为512了？

**Comment by iwestlin** [comment]
虚拟的吧，25万文件512M应该也够用了

**Comment by jason8303** [comment]
设置成4096了，还是偶尔会出现这个错误

**Comment by iwestlin** [comment]
> 设置成4096了，还是偶尔会出现这个错误

不会吧。。4096超过了实际的可用内存吗？
实际上1024就足够绝大部分情况了（如果用的是最新代码）
前几天我执行了一个200万以上文件数的拷贝，内存限制设成1G，成功完成。

**Comment by jason8303** [comment]
虚拟机运行colab，虚拟机内存8G，任务管理器看到实际占用也就1g左右。大佬请问你的200w文件需要多久？我的40万大概需要7个小时。并行任务数量改大是不是能提高速度。请问大佬在哪里改

**Comment by jason8303** [comment]
> 情况

虚拟机运行colab，虚拟机内存8G，任务管理器看到实际占用也就1g左右。大佬请问你的200w文件需要多久？我的40万大概需要7个小时。并行任务数量改大是不是能提高速度。请问大佬在哪里改

**Comment by jason8303** [comment]
> > 设置成4096了，还是偶尔会出现这个错误
> 
> 不会吧。。4096超过了实际的可用内存吗？
> 实际上1024就足够绝大部分情况了（如果用的是最新代码）
> 前几天我执行了一个200万以上文件数的拷贝，内存限制设成1G，成功完成。
虚拟机运行colab，虚拟机内存8G，任务管理器看到实际占用也就1g左右。大佬请问你的200w文件需要多久？我的40万大概需要7个小时。并行任务数量改大是不是能提高速度。请问大佬在哪里改

**Comment by jason8303** [comment]
> > 设置成4096了，还是偶尔会出现这个错误
虚拟机运行colab，虚拟机内存8G，任务管理器看到实际占用也就1g左右。大佬请问你的200w文件需要多久？我的40万大概需要7个小时。并行任务数量改大是不是能提高速度。请问大佬在哪里改

**Comment by iwestlin** [comment]
我用的默认20并行，中间手动中断过几次，跑了两天多。
在这里改
https://github.com/iwestlin/gd-utils/blob/5e77fafd0dde6bb419279cfcb2cbfb78ba7b0ef8/config.js#L10

**Comment by jason8303** [comment]
> 我用的默认20并行，中间手动中断过几次，跑了两天多。
> 在这里改
> https://github.com/iwestlin/gd-utils/blob/5e77fafd0dde6bb419279cfcb2cbfb78ba7b0ef8/config.js#L10
那速度差不多，改大会改善速度么？

**Comment by iwestlin** [comment]
会的，但并不一定越大越好，因为如果并行数太多导致机器连接数不够的话，会使得大部分请求超时，反而降低速度。
所以建议一点点增加看效果。。

**Comment by jason8303** [comment]
> > 我用的默认20并行，中间手动中断过几次，跑了两天多。
> > 在这里改
> > https://github.com/iwestlin/gd-utils/blob/5e77fafd0dde6bb419279cfcb2cbfb78ba7b0ef8/config.js#L10
> > 
> > 那速度差不多，改大会改善速度么？

iErics colab 挂载的是他自己改过的gd utils，很久没更新了。orange2008的colab挂载的是你的gd utils，但是他的colab执行起来有些bug，比如 状态流 不显示，只能停止拷贝 才跳出来。我没有VPS，所以想在虚拟机下安装ubuntu挂载，能行么？windows下能运行这个程序么？应该不行吧

**Comment by iwestlin** [comment]
可以的，node本身是跨平台的

**Comment by jason8303** [comment]
> 可以的，node本身是跨平台的

ok。Connected to wss://colab.research.google.com/api/kernels/。。。
运行过程中出现上面的东西，状态提示忙碌，是啥情况，是有人连接到我的程序了么，是不是要设定client id？

**Comment by jason8303** [comment]
> 可以的，node本身是跨平台的

错误
无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。

**Comment by jason8303** [comment]
> > 可以的，node本身是跨平台的
> 
> ok。Connected to wss://colab.research.google.com/api/kernels/。。。
> 运行过程中出现上面的东西，状态提示忙碌，是啥情况，是有人连接到我的程序了么，是不是要设定client id？



> > 可以的，node本身是跨平台的
> 
> 错误
> 无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。

然后就出现上面的提示

**Comment by iwestlin** [comment]
你是clone的原始项目吗？gd-utils本身没有用到colab啊。。

gd-utils安装方法可以看readme https://github.com/iwestlin/gd-utils/blob/master/readme.md#%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE

**Comment by jason8303** [comment]
我是用的colab，出现的这些错误

**Comment by DsglSheng** [comment]
> > 可以的，node本身是跨平台的
> 
> 错误
> 无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。

您好，我也出现这个问题了，请问你解决了吗

**Comment by ZJWDJCZ** [comment]
> 

+1，我也遇到了，请问你解决了吗

**Comment by ZJWDJCZ** [comment]
> 



> > > 可以的，node本身是跨平台的
> > 
> > 
> > 错误
> > 无法加载显示输出内容所需的 JavaScript 文件。这可能是因为您的 Google 帐号登录权限已过期或您的浏览器不允许使用第三方 Cookie。请重新加载该页面。
> 
> 您好，我也出现这个问题了，请问你解决了吗
+1，我也遇到了，请问你解决了吗
