### ISSUE TITLE
用主帐户进行复制的问题

### ISSUE THREAD

**Issue by sztuxp** [iwestlin/gd-utils#62]
在config.js内已正确配置了，  client_id: ,   client_secret: ,   refresh_token: , 三个主账户授权的项，对于一个团队盘，主帐户有读权限，但复制的时候，读不到该团队的信息，是空的

**Comment by iwestlin** [comment]
我不确定能否复制只有读权限的团队盘。
你可以选个小点的文件夹试试，在命令行分别执行
```
./count folderID
./copy folderID
```
看看什么结果？

**Comment by iwestlin** [comment]
另外你用的不是机器人吧，机器人的操作都是使用sa授权的。

**Comment by sztuxp** [comment]
不是用机器人，./count folderID的结果是0，但是我在另外一个挂载到CF项目上(https://github.com/workerindex/gdir)用主用帐户的只读权限是可以读到相关文档并下载的。要是这个项目能做到只读权限复制就好了，现在autoclone，gclone同样情况下能复制，但必须先在VPS上挂载，然后还要严格按照路径顺序来（奇怪的目录名转义非常麻烦），不能使用路径ID。

**Comment by iwestlin** [comment]
那不应该啊，你有没有在命令后加一个 -u，表示强制从线上更新？

**Comment by iwestlin** [comment]
另外 执行 node check.js 能返回个人盘根目录的文件吗

**Comment by sztuxp** [comment]
node check.js可以能返回个人盘根目录的文件，命令加-u 和不加 -u都不行

**Comment by sztuxp** [comment]
非常感谢回答！我好像踩到一个坑，那个团队盘的隐藏的，如果变为正常，就可以复制了，非常感谢。另外，我想问一下，我手工修改refresh_token值 ，是不是可以实现几个主用帐户接力复制同一个路径下文件呢？

**Comment by iwestlin** [comment]
如果用的client_id/client_secret一致的话是可以的

**Comment by sztuxp** [comment]
明白，谢谢！

**Comment by sztuxp** [comment]
功能太好用了！简单实用，以前在gclone使用不方便的地方都解决了

**Comment by sztuxp** [comment]
再报一个错误，用主用帐户 ./count时，感觉是触发速率限制，这个怎么调整?
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
{"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}
读取目录未完成(部分读取), 参数: {
  includeItemsFromAllDrives: true,
  supportsAllDrives: true,
  q: "'13tt9GiGROZ2CRM6S91i1aggVzpLFIKK7' in parents and trashed = false",
  orderBy: 'folder,name desc',
  fields: 'nextPageToken, files(id, name, mimeType, size, md5Checksum)',
  pageSize: 1000
}

**Comment by JiangJiaWei520** [comment]
> 再报一个错误，用主用帐户 ./count时，感觉是触发速率限制，有部分目录没有统计到，这个怎么调整?
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> {"error":{"errors":[{"domain":"usageLimits","reason":"userRateLimitExceeded","message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982","extendedHelp":"https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}],"code":403,"message":"User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: [https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982"}}](https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=974167812982%22%7D%7D)
> 读取目录未完成(部分读取), 参数: {
> includeItemsFromAllDrives: true,
> supportsAllDrives: true,
> q: "'13tt9GiGROZ2CRM6S91i1aggVzpLFIKK7' in parents and trashed = false",
> orderBy: 'folder,name desc',
> fields: 'nextPageToken, files(id, name, mimeType, size, md5Checksum)',
> pageSize: 1000
> }

这个好像是refresh_token不是最新的引起的
