### ISSUE TITLE
使用dedupe命令去重失败

### ISSUE THREAD

**Issue by fyfy010** [iwestlin/gd-utils#63]
先是重复显示删除重试，然后重试次数到了，显示删除成功，其实还是没删除，重新使用dedupe命令还是一样，无法去重删除文件，权限是内容管理员，
{"error":{"errors":[{"domain":"global","reason":"insufficientFilePermissions","message":"The user does not have sufficient permissions for this file."}],"code":403,"message":"The user does not have sufficient permissions for this file."}}
删除重试中，重试次数 7
成功删除文件 xxx.jpg
求解决方法哎

**Comment by iwestlin** [comment]
你是用的最新代码吗，以前的代码是把文件直接删除，需要管理者权限。后来改成了移动到回收站，就只需要内容管理者权限了

**Comment by fyfy010** [comment]
> 你是用的最新代码吗，以前的代码是把文件直接删除，需要管理者权限。后来改成了移动到回收站，就只需要内容管理者权限了

删除失败 Request failed with status code 401
删除失败 Request failed with status code 401
删除失败 Request failed with status code 401
任务完成，共删除文件数： 0 目录数： 0
刚更新了一下，一样是不行的。。。。

**Comment by iwestlin** [comment]
你有没有给命令最后加 -S参数？加了才表示用sa授权操作，没加会用到个人授权

**Comment by fyfy010** [comment]
> 你有没有给命令最后加 -S参数？加了才表示用sa授权操作，没加会用到个人授权

恩，谢谢啊，确实这次忘了加-S，现在成功了，不过没升级那会儿我加-S是失败的
