### ISSUE TITLE
TG Bot无法进行复制操作

### ISSUE THREAD

**Issue by Rewrite0** [iwestlin/gd-utils#64]
tg机器人执行复制操作会提示 Request failed with status code 404 ，文件统计没有问题，在终端下加入-S进行拷贝也没有问题，求解

**Comment by Rewrite0** [comment]
- 
我天，不小心closed了，麻烦大佬看看问题
-

**Comment by iwestlin** [comment]
404一般是因为sa没有权限，你是新加的sa授权文件吗，如果是，需要执行 pm2 reload server才能生效的。

不行的话看看 pm2 logs输出什么

**Comment by Rewrite0** [comment]
reload过了，pm2 logs输出这段

**Comment by Rewrite0** [comment]
reload过了，pm2输出这段
PM2       | App [server:0] exited with code [1] via signal [SIGINT]
PM2       | App [server:0] starting in -fork mode-
PM2       | App [server:0] online
0|server  | http://127.0.0.1:23333
0|server  | Error: listen EADDRINUSE: address already in use 0.0.0.0:23333
0|server  |     at Server.setupListenHandle [as _listen2] (net.js:1313:16)
0|server  |     at listenInCluster (net.js:1361:12)
0|server  |     at doListen (net.js:1498:7)
0|server  |     at processTicksAndRejections (internal/process/task_queues.js:85:21) {
0|server  |   code: 'EADDRINUSE',
0|server  |   errno: 'EADDRINUSE',
0|server  |   syscall: 'listen',
0|server  |   address: '0.0.0.0',
0|server  |   port: 23333
0|server  | }

**Comment by iwestlin** [comment]
看上去有两个server在运行…… pm2 ls看看？

而且这个报错和code 404也没关系。。
`tail -100 ~/.pm2/logs/server-error.log`机器人复制失败后执行下这条看看

**Comment by iwestlin** [comment]
用的是最新代码吗

**Comment by Rewrite0** [comment]
bot操作
![image](https://user-images.githubusercontent.com/49576640/86529525-d47c7000-bee3-11ea-867a-5ff91c31bf6f.png)
pm2 ls执行结果
![image](https://user-images.githubusercontent.com/49576640/86529466-73ed3300-bee3-11ea-9443-f8490a0f0d68.png)
tail -100 ~/.pm2/logs/server-error.log 执行结果
![image](https://user-images.githubusercontent.com/49576640/86529512-c2023680-bee3-11ea-873c-5e33d36cded2.png)
用的是最新代码

**Comment by iwestlin** [comment]
这个错误消息是说23333端口被占用了，还是和404没啥关系……

netstat -tulpen | grep 23333 看看是哪个程序占用了23333端口？

**Comment by Rewrite0** [comment]
emmmm
![image](https://user-images.githubusercontent.com/49576640/86529634-aea39b00-bee4-11ea-95fb-7b8c21a28e4b.png)

**Comment by iwestlin** [comment]
。。
要不先删掉吧 pm2 delete server
然后再看看 23333端口有没有占用
没有的话 再在gd-utils目录下重新启动 `pm2 start server.js --node-args="--max-old-space-size=1024"`

接着pm2 logs看看还有没有提示端口占用

没有的话
> tail -100 ~/.pm2/logs/server-error.log机器人复制失败后执行下这条看看

**Comment by Rewrite0** [comment]
突然好了，我重启了vps，再重启了服务，bot成功执行了复制任务。。。
感谢大佬的耐心帮我！（笑哭）
