### ISSUE TITLE
能否实现增加文件ID查询和取消当前传输或者查询会话的功能

### ISSUE THREAD

**Issue by JiangJiaWei520** [iwestlin/gd-utils#66]
1、输入某个命令进行查询所有的盘符（个人云端硬盘、共享云端硬盘）
     A、点击盘符时显示：盘符名称、盘符ID、是否有编辑权限和他之下的所有目录和文件列表
     B、点击的为文件夹时显示：文件名称、文件ID、是否有编辑权限和他之下的所有目录和文件列表
     C、点击的为文件时显示：文件名称、文件ID、是否有编辑权限
2、取消当前传输或者查询
    A、选择取消当前会话，列出所有会话ID,选择性停止取消

**Comment by iwestlin** [comment]
😱你是要我吐血吗。。很多功能建议直接使用Google drive本身啊

> 取消当前传输或者查询

这个可以 pm2 reload server 实现，以后看好不好加吧
