### ISSUE TITLE
没有可用的SA帐

### ISSUE THREAD

**Issue by ZhaoqiangCn** [iwestlin/gd-utils#67]
你好，这个提示是指我的100个SA全都用完了吗? 是要明天继续了吗?

**Comment by iwestlin** [comment]
是的，每触发一次 rate limit，就会剔除掉对应的sa，直到没有sa可用就会发这个消息。

可以新上传一批sa后pm2 reload server，再继续任务

**Comment by iwestlin** [comment]
刚想起代码没加每天更新sa的可用状态。。现在加上了，可以 git pull && pm2 reload server 更新下
