### ISSUE TITLE
本地（个人使用的电脑上）命令行下进行复制操作丢失文件

### ISSUE THREAD

**Issue by April-BOY** [iwestlin/gd-utils#68]
复制过程中，报了一个错误：
复制文件失败，文件id: 1XYlOB9TJLPLjUixTkHnQVUj1YL8MYKkR
getaddrinfo ENOTFOUND www.googleapis.com
![报错-gdutils丢文件问题](https://user-images.githubusercontent.com/19245482/86565802-1c120300-bf9b-11ea-9191-99e22431b0a1.png)

检测了sa账号对目录文件夹的操作权限，没有问题
![gdutils丢文件问题-sa账号检测](https://user-images.githubusercontent.com/19245482/86565873-3a77fe80-bf9b-11ea-80de-d0d8d6df7ba3.png)

问题：
（1）对于上面的问题，我猜想是我节点不稳定导致的？
（2）对于丢文件的情况，是再重新执行一遍拷贝吗？还是怎样操作？如果是重新执行一遍拷贝，会自动跳过已经拷贝成功的文件吗？

**Comment by iwestlin** [comment]
`getaddrinfo ENOTFOUND`经常发生在proxy不稳或连接数不够的情况下，代理环境建议调小 `PARALLEL_LIMIT`的值。

可以重新执行相同的拷贝命令，如果检查到之前的记录，程序会暂停给你continue或restart的选项。选择continue的话就可以继续拷贝未拷贝的文件了
