### ISSUE TITLE
可否增加多盘同时转存

### ISSUE THREAD

**Issue by q409640976** [iwestlin/gd-utils#69]
现在的书签选择只能选其中一个
可否加一个选项:**复制到所有**

**Comment by iwestlin** [comment]
...你可以都点一遍啊，不过很不建议这么做，因为目前`PARALLEL_LIMIT`的限制是针对单次任务的，如果同时进行，很可能网络连接数不够

**Comment by q409640976** [comment]
谢谢，牛x的程序，牛x的人！

> ...你可以都点一遍啊，不过很不建议这么做，因为目前`PARALLEL_LIMIT`的限制是针对单次任务的，如果同时进行，很可能网络连接数不够
