### ISSUE TITLE
Google Colab运行报错

### ISSUE THREAD

**Issue by 68minv** [iwestlin/gd-utils#7]
运行`npm i`
`npm WARN gd-utils@1.0.0 No repository field.`

`added 185 packages from 96 contributors and audited 188 packages in 4.789s`

`5 packages are looking for funding`
  `run `npm fund` for details`

`found 0 vulnerabilities`

运行`node check.js -S`
`Error: Request failed with status code 401`
   `at createError (/content/gd-utils/node_modules/@viegg/axios/lib/core/createError.js:16:15)`
    `at settle (/content/gd-utils/node_modules/@viegg/axios/lib/core/settle.js:17:12)`
    `at IncomingMessage.handleStreamEnd (/content/gd-utils/node_modules/@viegg/axios/lib/adapters/http.js:183:11)`
    `at IncomingMessage.emit (events.js:327:22)`
    `at endReadableNT (_stream_readable.js:1221:12)`
    `at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by iwestlin** [comment]
401未授权，是不是 config.js里没有配置client_id/client_secret/refresh_token？

**Comment by 68minv** [comment]
是的，中间重置忘记配置了
