### ISSUE TITLE
[interrupt]被打断的任务怎么继续?

### ISSUE THREAD

**Issue by q409640976** [iwestlin/gd-utils#71]
看了下数据库,几个任务被中断了,怎么继续呢

**Comment by iwestlin** [comment]
直接执行和上次相同的命令就可以了。
在命令行检测到相同的记录，会提示你继续或重新开始。
机器人的话会直接继续上次的进度

**Comment by q409640976** [comment]
> 直接执行和上次相同的命令就可以了。
> 在命令行检测到相同的记录，会提示你继续或重新开始。
> 机器人的话会直接继续上次的进度

那有没有可能vps重启后，自动进行中断任务呢？

**Comment by iwestlin** [comment]
目前只能做到vps重启自动启动进程
pm2 save && pm2 startup
任务还是要手动输入
