### ISSUE TITLE
文件拷贝的时候报错

### ISSUE THREAD

**Issue by southcat** [iwestlin/gd-utils#72]
![image](https://user-images.githubusercontent.com/32999518/86593554-0a932000-bfc8-11ea-823c-57bc2a102a58.png)
mu'l目录都创建好了 但是拷贝文件的时候报错

**Comment by iwestlin** [comment]
这是内存占用太大被nodejs强制退出了。
如果是命令行操作，可以像这样执行命令`./count folder-id -S`
```
node --max-old-space-size=1024 ./count folder-id -S
```

如果是 pm2启动的，可以 pm2 delete server先删掉进程，然后 
```
pm2 start server.js --node-args="--max-old-space-size=1024"
```
表示允许进程最大占用1G内存

我自己试过最大拷贝文件数35万，内存占用不超过600M
