### ISSUE TITLE
userRateLimitExceeded，希望增加全局访问频率限制，内详

### ISSUE THREAD

**Issue by cecaa1030** [iwestlin/gd-utils#73]
Google Drive API限制100秒内访问上限10000次，单账号100秒内访问1000次
所以并发数10的情况下单账号或单SA每秒钟访问8次是比较安全的，如果并发数20，则每秒钟访问4次安全，5次峰值

持续超过访问频率限制一段时间后所有API就会报userRateLimitExceeded，很长一段时间都不会重置，所以非常影响效率

**Comment by iwestlin** [comment]
不是很需要吧，完全可以等一个任务完成了再进行下一个任务啊。
如果加上了，那么怎么安排两个任务的优先级？是前面的任务执行完再执行下一个任务，还是两个任务分别占用一半的并发请求？

目前代码依赖的 p-limit 没有实时调整并发数的方法，不过有个加强版的[p-queue](https://github.com/sindresorhus/p-queue/blob/9672a3d6be06fe52f2481460c6d12645343c7ae4/test/test.ts#L71)可以做到。
但是这样的话需要调整很多代码，所有暂时不打算做。

欢迎PR😎

**Comment by cecaa1030** [comment]
我们好像说的不是一个事，你说的是多命令之间的全局吗？比如多个copy同时运行？这种情况确实没必要考虑的。
我说的是单命令比如单copy命令内部的全局访问频率限制，如果你已经做了限制那是不是可能存在问题？我昨天跑了一个30多万文件的copy，没有其他命令同时运行，跑了一段时间后就访问频率超限了

**Comment by iwestlin** [comment]
确实有可能的，因为这个「并行请求」实际上限制的是几个特定函数的同时运行数，而函数内部会有失败重试等机制，所以并不能确保同时发出的http请求最多20个。

不过你触发的可能不是频率限制？每个sa每天有750G的搬运流量，你是不是触发的这个

**Comment by iwestlin** [comment]
你说的这个「全局访问频率限制」是不是`PARALLEL_LIMIT`啊？那个可以在这里设置的：

https://github.com/iwestlin/gd-utils/blob/d688d1fda006f5485c3f0d2dbc0ffb79b5eaf433/config.js#L10

**Comment by cecaa1030** [comment]
这个是设置并发访问数，谷歌限制的不是并发量，而是100秒内的访问总量，所以并发数怎么设置都是满足不了需求的

**Comment by iwestlin** [comment]
你想说加个计数器，计算100秒内的访问总量？超了就暂停停止访问吗？

我觉得你触发的大概率是750g的用户限制，你是用个人帐号还是sa授权进行的操作？如果用sa有没有在命令最后加个 `-S` 表示使用sa授权？

如果用的是默认的20并发请求，而且sa数量足够（20以上？），应该是不会遇到这个100秒内的访问总量限制。

<img width="361" alt="截屏2020-07-07 下午7 46 20" src="https://user-images.githubusercontent.com/6235509/86776355-b8ff9980-c08a-11ea-930f-aed110ed4271.png">

这里可以看到，单个sa平均每秒可以发10个请求，单个项目所有sa平均每秒最多100个请求。
而这个项目每次请求是随机取的sa，所以平均下来单个sa的并发请求只有1次，就算每次请求半秒完成，那也是1秒2次，远远没到达限制

**Comment by cecaa1030** [comment]
首先，我用的是SA账号，确实在命令后加了-S使用SA，我为每个gd-utils配置了300个SA，这里是没有问题的。

我觉得问题出在你计算每次请求完成的时间。

以我的案例来计算：我这里到梯子的ping是47ms，我选的Google API机房在香港，所以50ms以内可以完成一次请求。那这样单个SA在1秒钟内就是20次，我设置的是20并发，这样就是1秒钟400次，100秒就是40000次，就超了10000次的配额。

实际上我通过Google API配额统计界面显示，最高100秒内到过69000多次访问，所以考虑到一些tcp加速技术存在，可能完成一次请求实际在30ms左右。这样两边数据是能对上的。

**Comment by iwestlin** [comment]
没那么快的……Google drive API响应速度平均能有500ms就已经是过分乐观了。
事实上很多请求都是被超时丢弃了，只不过有人觉得超时错误很烦人就把它给隐藏了，我设置的最低超时时间7秒，你感受下……

不信你可以自己发一个请求试试，根据我在vps上日志的观察，google drive api的平均响应速度在1秒以上

**Comment by cecaa1030** [comment]
我理解你的说法，但这里确实挺奇怪的。
我这边确实报了userRateLimitExceeded错误，同时交替报了rateLimitExceeded，两个错误都显示是访问频率超限：https://developers.google.com/drive/api/v3/handle-errors
我这300个SA来自于同一个google账号下的三个项目，同一时间并没有其它程序在使用。同时报错的时候去API配额页面里面看，100秒访问次数确实是69000多。

我看到google文档里的一个说法，有没有可能是超时的请求很多，然后重试的时候没有使用所谓的exponential backoff策略，导致重试次数大大超过预期？

**Comment by iwestlin** [comment]
没有……重试只会越来越慢，最多7次
```
// 单次请求多少毫秒未响应以后超时（基准值，若连续超时则下次调整为上次的2倍）
const TIMEOUT_BASE = 7000
// 最大超时设置，比如某次请求，第一次7s超时，第二次14s，第三次28s，第四次56s，第五次不是112s而是60s，后续同理
const TIMEOUT_MAX = 60000
```
google 这个统计不一定准确，事实上它很多东西都是不靠谱的，特别是google drive相关。。
它搞的一个 [gtoken](https://www.npmjs.com/package/gtoken)居然默认返回缓存的access_token你敢信，缓存就缓存吧，它附带的expire_in还不更新。。
还有网页版的google drive，chrome一打开就cpu跑满，我都怀疑它拿用户电脑挖矿……

这种错误无视就好了。。还有经常出现的500错误，程序会剔除掉超限的sa并自动重试，不影响最终结果。

**Comment by cecaa1030** [comment]
话是这么说没错的。
但是现在对于大的（现在的例子是170T，36W文件）文件夹，我使用gd-utils拷贝的话，1个小时以内必定报错终止。使用gclone拷贝就没问题，当然，时间要长很多。
这就很尴尬了，以后难道大的文件夹用gclone，小的用gd-utils？这样发挥不出gd-utils的优势了呀

**Comment by cecaa1030** [comment]
对了，这个出问题的文件夹是
1rGDacpZ238aHOvaw7IkSEXG2yLO_niw_
要不你试试看？

**Comment by iwestlin** [comment]
> 话是这么说没错的。
> 但是现在对于大的（现在的例子是170T，36W文件）文件夹，我使用gd-utils拷贝的话，1个小时以内必定报错终止。使用gclone拷贝就没问题，当然，时间要长很多。
> 这就很尴尬了，以后难道大的文件夹用gclone，小的用gd-utils？这样发挥不出gd-utils的优势了呀

我昨天就搬了大包，它不是170T，是345.50 TB。。我的300sa流量都用完了，今天才搬完……

**Comment by iwestlin** [comment]
```
创建时间：2020-07-06 13:46:09
完成时间：2020-07-07 19:54:13
目录进度：22447/22447
文件进度：359485/359521
合计大小：345.50 TB
```

**Comment by cecaa1030** [comment]
哈哈，我分2批搬的，300个SA搬这个170多T的A库文件夹，另外300个SA搬剩下的

**Comment by iwestlin** [comment]
不，我是说这个A库就已经有345T了，别的我也没搬……

**Comment by cecaa1030** [comment]
晕，怪不得gclone到现在都没搬完，速度真的差很多，可惜我gd-utils就是报错呀，昨天试了好几次都不行

**Comment by iwestlin** [comment]
你要不换一批新的sa试试吧……

**Comment by cecaa1030** [comment]
嗯，也没其他办法了

**Comment by cecaa1030** [comment]
我用gd-utils接gclone拷贝到一半的文件夹，使用-S -u -D这三个选项覆盖，会自动跳过已经存在的文件吗？

**Comment by iwestlin** [comment]
不好意思啊，gd-utils没办法接上gclone的进度，因为它只会把拷贝记录存在本地数据库里，这样就不用向Google查询是否拷贝过了（这也是它比较快的本质原因）。

所以gd-utils只能接上它自己的拷贝进度，如果之前是用别的工具，那只能重新来了。

**Comment by cecaa1030** [comment]
哦哦，好的，晚上另外重开一个吧，感谢！

**Comment by cecaa1030** [comment]
如果有时间可以考虑加一个option，读取目标文件夹已有文件，构建状态数据库，这样子可能灵活一点应对各种情况。纯建议哈。
