### ISSUE TITLE
大佬,同于上个问题,我是哪里出了错

### ISSUE THREAD

**Issue by jing5460** [iwestlin/gd-utils#76]
![photo_2020-07-07_10-31-03](https://user-images.githubusercontent.com/38358681/86693901-b034a680-c03d-11ea-985e-33949dcbc1ec.jpg)

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/issues/57#issuecomment-653731114

按这个排查下吧，原因可能有很多

**Comment by iwestlin** [comment]
feel free to reopen
