### ISSUE TITLE
备份数据库文件好像不生效

### ISSUE THREAD

**Issue by iouAkira** [iwestlin/gd-utils#77]
备份了`gdurl.sqlite`文件 ,后面重新复制进去这个文件想不生效，任务和收藏夹也还是都没有了，还需要备份其他文件？

**Comment by iwestlin** [comment]
任务和收藏夹都是放在这个数据库的，你可以这样试试：
先 pm2 stop server停掉进程，然后备份老数据库

如果你不确定老数据库里是否包含完整记录，可以找个sqlite软件打开看看，任务和收藏夹分别在 task 和 bookmark 两张表

最后将新数据库移入gd-utils目录，再pm2 reload server重启进程

**Comment by iwestlin** [comment]
如果上面方法无效欢迎反馈啊，我也不确定能否完整移植，因为代码给sqlite开启了WAL模式。

无效的话我考虑加个备份数据库的脚本

**Comment by iwestlin** [comment]
刚加了个备份脚本：https://github.com/iwestlin/gd-utils/blob/master/backup-db.js

可以直接运行 `.backup-db.js` 就会把数据库备份到 backup目录了

**Comment by iouAkira** [comment]
我现在是把三个`sqllite`相关文件都备份了,docker容器删掉重新挂载进去好像没问题了,后面遇到问题再反馈

另外有个小小的建议🤭是不是可以考虑把配置相关文件`config.js` `sa`和数据`gdurl.sqlite` 这些文件单独放在一个目录,这样如果备份的备份那个目录就行, 如果是docker也可以直接挂载整整个目录,,不需要单个文件挂载了,另外感谢作者写了这么方便工具

**Comment by iwestlin** [comment]
一开始确实应该这么设计，但现在再改也不好改了。。
因为这些文件都写进.gitignore了，再提交修改的话可能和用户自己的修改冲突造成无法顺利git pull更新……

所以其实可以写两个脚本 backup.js 和 import.js
一个一键把用户内容备份到backup目录，一个一键将backup目录中的内容还原到对应的位置。
