### ISSUE TITLE
删了大量文件 仍然提示：复制失败，失败消息：您的团队盘文件数已超限，停止复制

### ISSUE THREAD

**Issue by ZhaoqiangCn** [iwestlin/gd-utils#78]
已经删除团队盘中的大量文件再次执行任务，还是报如下提示：
以下为log中的报错信息。
{"error":{"errors":[{"domain":"global","reason":"teamDriveFileLimitExceeded","message":"The file limit for this shared
 drive has been exceeded."}],"code":403,"message":"The file limit for this shared drive has been exceeded."}}

**Comment by iwestlin** [comment]
首先要记得清空回收站，回收站的文件也会占空间
然后这个限制也不是完全精确的，google也需要时间得出团队盘内的总文件数

建议把一些文件数比较多的目录移动到别的地方，这样比较快生效
