### ISSUE TITLE
执行 node check.js 出错

### ISSUE THREAD

**Issue by obview** [iwestlin/gd-utils#8]
执行 node check.js 出现很长一段代码，最后一段如下，求问哪里出了问题？

   _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: 'invalid_grant', error_description: 'Bad Request' }
  },
  isAxiosError: true,
  toJSON: [Function]

**Comment by iwestlin** [comment]
config.js没配置 client_id / client_secret / refresh_token吧？

**Comment by ukiyo99** [comment]
大佬，我这里是这样报错的，但是我都是新获取的呀……


/root/gd-utils/check.js:1
(function (exports, require, module, __filename, __dirname) { const { ls_folde
                                                                    ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by iwestlin** [comment]
> 大佬，我这里是这样报错的，但是我都是新获取的呀……
> 
> /root/gd-utils/check.js:1
> (function (exports, require, module, __filename, __dirname) { const { ls_folde
> ^
> SyntaxError: Unexpected token {
> at Module._compile (module.js:439:25)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Function.Module.runMain (module.js:497:10)
> at startup (node.js:119:16)
> at node.js:906:3

奇怪，你的check.js 长啥样？
```
const { ls_folder } = require('./src/gd')

ls_folder({ fid: 'root' }).then(console.log).catch(console.error)
```
不是这样的吗

**Comment by ukiyo99** [comment]
> > 大佬，我这里是这样报错的，但是我都是新获取的呀……
> > /root/gd-utils/check.js:1 
> > （函数（导出，需要，模块，__ filename，__ dirname））{const {ls_folde 
> > ^ 
> > SyntaxError：意外令牌{ 
> > 在Module._compile（module.js：439：25）
> > 在Object .Module._extensions..js（module.js：474：10）
> > 在Module.load（module.js：356：32）
> > 在Function.Module._load（module.js：312：12）
> > 在Function.Module.runMain （module.js：497：10）
> > 在启动时（node.js：119：16）
> > 在node.js：906：3
> 
> 奇怪，你的check.js长啥样？
> 
> ```
> const { ls_folder } = require('./src/gd')
> 
> ls_folder({ fid: 'root' }).then(console.log).catch(console.error)
> ```
> 
> 不是这样的吗

是这样的，但是一运行就出现上面的那一串，ID token啥的都是新获取的

**Comment by ukiyo99** [comment]
上面是在服务器上运行的，下面是在本地运行返回的结果：

internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'better-sqlite3'
Require stack:
- C:\Users\Administrator\Desktop\gd-utils\db.js
- C:\Users\Administrator\Desktop\gd-utils\src\gd.js
- C:\Users\Administrator\Desktop\gd-utils\check.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\gd-utils\db.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\Desktop\\gd-utils\\db.js',
    'C:\\Users\\Administrator\\Desktop\\gd-utils\\src\\gd.js',
    'C:\\Users\\Administrator\\Desktop\\gd-utils\\check.js'
  ]
}

**Comment by iwestlin** [comment]
@ukiyo99 
better-sqlite3 这个依赖没安装好

**Comment by ukiyo99** [comment]
> @ukiyo99
> better-sqlite3 这个依赖没安装好

好，我现在去安装下，谢谢大佬！

**Comment by JiangJiaWei520** [comment]
检查了好几遍都没发现问题所在，特来请教下
Error: Request failed with status code 401
    at createError (/root/gd-utils/node_modules/@viegg/axios/lib/core/createError.js:16:15)
    at settle (/root/gd-utils/node_modules/@viegg/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/gd-utils/node_modules/@viegg/axios/lib/adapters/http.js:183:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

检查权限：
正常/异常 97/0
检测进度 98/100
正常/异常 98/0
检测进度 99/100
正常/异常 99/0
已检测 100 个SA，未检测到无效帐号

**Comment by iwestlin** [comment]
node check.js 是用来检查个人授权的，如果用sa可以跳过这一步。

tg机器人的所有操作都是使用sa的权限。

命令行使用需要给命令后面加个 -S，表示使用sa授权

**Comment by JiangJiaWei520** [comment]
请教下这个大致原因是什么？





蒋家威&nbsp;&nbsp;
中国 吉林 长春 | 学生 - 吉林建筑工程学院





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"issue哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月4日(星期六) 晚上11:51
收件人:&nbsp;"iwestlin/gd-utils"<gd-utils@noreply.github.com&gt;;
抄送:&nbsp;"蒋家威"<2314857815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwestlin/gd-utils] 执行 node check.js 出错 (#8)





 
node check.js 是用来检查个人授权的，如果用sa可以跳过这一步。
 
tg机器人的所有操作都是使用sa的权限。
 
命令行使用需要给命令后面加个 -S，表示使用sa授权

**Comment by iwestlin** [comment]
> 请教下这个大致原因是什么？ 

client_id/client_secret/refresh_token没有填写对

**Comment by JiangJiaWei520** [comment]
这样不是代表client_id/client_secret/refresh_token配置没有问题吗？


我执行pm2 logs，看日志返回错误







蒋家威&nbsp;&nbsp;
中国 吉林 长春 | 学生 - 吉林建筑工程学院





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"issue哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 下午2:55
收件人:&nbsp;"iwestlin/gd-utils"<gd-utils@noreply.github.com&gt;;
抄送:&nbsp;"蒋家威"<2314857815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwestlin/gd-utils] 执行 node check.js 出错 (#8)





  
请教下这个大致原因是什么？
  
client_id/client_secret/refresh_token没有填写对

**Comment by iwestlin** [comment]
你是贴了图吗？我这里看不到图片。
我以为你问的`Error: Request failed with status code 401`这个问题

**Comment by JiangJiaWei520** [comment]
贴图了，好像是统计的文件太多？比较少的可以统计出来


蒋家威&nbsp;&nbsp;
中国 吉林 长春 | 学生 - 吉林建筑工程学院





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"issue哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 下午3:13
收件人:&nbsp;"iwestlin/gd-utils"<gd-utils@noreply.github.com&gt;;
抄送:&nbsp;"蒋家威"<2314857815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwestlin/gd-utils] 执行 node check.js 出错 (#8)





 
你是贴了图吗？我这里看不到图片。
 我以为你问的Error: Request failed with status code 401这个问题

**Comment by JiangJiaWei520** [comment]
贴图了，好像是统计的文件太多？比较少的可以统计出来


少的可以统计





蒋家威&nbsp; 
中国 吉林 长春 | 学生 - 吉林建筑工程学院





&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"issue哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 下午3:13
收件人:&nbsp;"iwestlin/gd-utils"<gd-utils@noreply.github.com&gt;;
抄送:&nbsp;"蒋家威"<2314857815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwestlin/gd-utils] 执行 node check.js 出错 (#8)





 
你是贴了图吗？我这里看不到图片。
 我以为你问的Error: Request failed with status code 401这个问题

**Comment by JiangJiaWei520** [comment]
贴图了，好像是统计的文件太多？比较少的可以统计出来


少的可以统计





第一次统计可以出来，不过会显示很多代码







蒋家威&nbsp; 
中国 吉林 长春 | 学生 - 吉林建筑工程学院





&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"issue哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 下午3:13
收件人:&nbsp;"iwestlin/gd-utils"<gd-utils@noreply.github.com&gt;;
抄送:&nbsp;"蒋家威"<2314857815@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [iwestlin/gd-utils] 执行 node check.js 出错 (#8)





 
你是贴了图吗？我这里看不到图片。
 我以为你问的Error: Request failed with status code 401这个问题

**Comment by iwestlin** [comment]
feel free to reopen
