### ISSUE TITLE
【bug】出现多次进度不到100%就finished的情况

### ISSUE THREAD

**Issue by q409640976** [iwestlin/gd-utils#84]
昨天升级后,出现多次进度不到100%就finished的情况
有时候进度23-30%就finished

**Comment by iwestlin** [comment]
有没有可以重现的链接？或者完成时pm2的日志？
日志查看方法 `tail -100 ~/.pm2/logs/server-error.log`
或者 pm2 logs看实时日志

**Comment by q409640976** [comment]
错误一大堆，让他标记error吧，别标记finished

没有可用sa账号，还有什么limit你懂的
