### ISSUE TITLE
【建议】隐藏两类报错信息，提升用户体验

### ISSUE THREAD

**Issue by April-BOY** [iwestlin/gd-utils#85]
希望能隐藏两类报错信息，对于项目执行影响应该不大，但是，在命令行下，如果多次输出，就会影响到其他信息的查看了，比如：
（1）文件夹创建失败的信息或者复制文件失败的信息
（2）复制完后执行count命令后与前面的文件信息进行比对时就要划很久的滚动条才能找到。

如果不能隐藏，则希望换成具体的简短的文字提示，也方便后续出现问题可以反馈给你排查。

第一类信息：
![一类信息](https://user-images.githubusercontent.com/19245482/87058495-ba6fc400-c23a-11ea-8e7d-abf688d13ee4.png)

第二类信息：
![二类信息](https://user-images.githubusercontent.com/19245482/87058545-cb203a00-c23a-11ea-9e9f-514d34e11e2d.png)

**Comment by iwestlin** [comment]
done: https://github.com/iwestlin/gd-utils/commit/71b16fa4bf6c8c159d76eb30420adf2a6beb0160
你这两个错误都是在获取sa的access token时发生的，看上去是代理不稳造成的。。

**Comment by April-BOY** [comment]
确实是代理不稳，晚上的时候，这两类报错出现的比较多
