### ISSUE TITLE
统计整个团队盘

### ISSUE THREAD

**Issue by viviov** [iwestlin/gd-utils#86]
`./count team-drive-id `显示结果为0B，使用该团队盘一个文件夹目录 `./count team-drive-folder-id`可以统计出结果但是整个大小不对，完全偏少了。

**Comment by iwestlin** [comment]
命令最后有加 `-S -u`吗？-S表示使用sa授权进行统计，不加的话用个人授权容易触发api限制。
-u表示强制线上更新

**Comment by viviov** [comment]
> 命令最后有加 `-S -u`吗？-S表示使用sa授权进行统计，不加的话用个人授权容易触发api限制。
> -u表示强制线上更新

试过了，`-S  -u`得到的结果和之前一样，

**Comment by iwestlin** [comment]
有检测过sa的权限吗 ./validate-sa.js 团队盘ID

**Comment by viviov** [comment]
> 有检测过sa的权限吗 ./validate-sa.js 团队盘ID

之前使用AutoRclone生成了大约1000个SA，但是只把90多个放到Group中，就是说只有90几个是有效的，sa中有很多无效账户。按照作者的提示将其移除已经恢复正常了，感谢。
