### ISSUE TITLE
并发的连接是否没有复用

### ISSUE THREAD

**Issue by lovitus** [iwestlin/gd-utils#87]
我使用代理连接到谷歌, 虽然主机的确只有40多个连接.  
但是代理那边一下子就**堆积上成千上万的未关闭连接**.  
不确定 是代理工具的原因,还是可以在工具箱代码里对可以对https的连接进行结束?
![image](https://user-images.githubusercontent.com/14361541/87115424-cfce0800-c2a5-11ea-9013-0c1396deed6b.png)

![Animation](https://user-images.githubusercontent.com/14361541/87114921-787b6800-c2a4-11ea-9af9-432b6a490020.gif)

**Comment by iwestlin** [comment]
看上去像是依赖的https-proxy-agent有问题：
https://github.com/TooTallNate/node-https-proxy-agent/pull/91

我等下换个依赖试试

**Comment by iwestlin** [comment]
我刚push了代码，把依赖换成了https://github.com/TooTallNate/node-proxy-agent

你可以git pull更新下试试，记得更新后安装下新的依赖 npm i proxy-agent
顺便帮我看下代理那边还会堆积连接吗

我自己本地代理环境试了下20个并行，对2622个对象数的链接成功完整拷贝。

**Comment by iwestlin** [comment]
😭我sb了，刚看了眼代码 https://github.com/TooTallNate/node-proxy-agent/blob/4af6f5e38a41680f97238639804014abb04910ec/index.js#L18
原来新的依赖用的还是老的依赖。。
我白做无用功了。。

**Comment by lovitus** [comment]
我加了4个代理用nginx进行了负载均衡后,没发现问题了.
现在单个节点activate数保持在10个左右了, 只有closed数在增加,看样子在及时释放连接.
也可能是有几个转存任务已经完成,现在只有一个任务进行中.
可能程序其实工作正常, 怀疑windows端的clash代理程序有些性能问题, 如果这个issus中有误会不要介意哈 :smile: 

![image](https://user-images.githubusercontent.com/14361541/87122391-5fc87d80-c2b7-11ea-9a1e-b281a76315ad.png)
