### ISSUE TITLE
sa配置问题

### ISSUE THREAD

**Issue by ch634421335** [iwestlin/gd-utils#88]
大佬你发的sa配置的链接打不开 552了 能更新一下吗
<a href="https://sm.ms/image/nVF87xwv9kHiqr3" target="_blank"><img src="https://i.loli.net/2020/07/10/nVF87xwv9kHiqr3.png" /></a>

**Comment by iwestlin** [comment]
更新了 https://github.com/iwestlin/gd-utils#service-account-%E9%85%8D%E7%BD%AE
