### ISSUE TITLE
TG机器人复制时报错

### ISSUE THREAD

**Issue by Cxry1216** [iwestlin/gd-utils#89]
![1](https://user-images.githubusercontent.com/49393426/87133854-7e843f80-c2ca-11ea-9577-e4290805ba33.png)
有人遇到过吗，折腾一天了，Linux下可以正常执行复制操作。

**Comment by iwestlin** [comment]
复制失败的时候，pm2 logs看看实时日志？
404大部分是由于sa没有权限造成的

**Comment by iwestlin** [comment]
可以在gd-utils目录下 执行 `./validate-sa.js 你设置的默认文件夹ID`检查下sa的权限

**Comment by Cxry1216** [comment]
![image](https://user-images.githubusercontent.com/49393426/87134494-5517e380-c2cb-11ea-8c5d-2a2a42d5ce82.png)
好像全都是异常，想请教一下如何修改sa的权限

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils#service-account-%E9%85%8D%E7%BD%AE
这里有两个链接可以看看

**Comment by Cxry1216** [comment]
已解决，感谢！
