### ISSUE TITLE
服务端会出现400 429等报错

### ISSUE THREAD

**Issue by Wilnk** [iwestlin/gd-utils#91]
使用的时候服务端会出现400 404 429等报错
![image](https://user-images.githubusercontent.com/46810638/87217153-09237800-c379-11ea-84ac-cdda8e199fa4.png)
![image](https://user-images.githubusercontent.com/46810638/87217195-4b4cb980-c379-11ea-9ec5-eec55206bed1.png)
![image](https://user-images.githubusercontent.com/46810638/87217333-b1860c00-c37a-11ea-8f5d-20dfc7eec41b.png)

400我猜估计是网络原因 404这个又是随机的搞不懂  那429呢？
这是什么原因？

**Comment by iwestlin** [comment]
429是请求太频繁了，可以调低点并行请求数。（也有可能是请求失败自动重试导致的过于频繁……

400和404大概率是由于sa异常造成的，当sa试图复制文件到它没有权限的文件夹中，就会报404错误。
由于程序每次请求是随机选的sa，所以会时不时出现。

解决方法：在gd-utils目录下执行 `./validate-sa.js 你的目标文件夹ID`，程序会依次检测`./sa`目录下所有sa文件是否有对`你的目标文件夹ID`的阅读权限。如果检测到异常，它最后会提供一个选项允许你将所有异常的sa文件移动到 `./sa/invalid`目录中

**Comment by Wilnk** [comment]
SA应该没有问题  我检测好几次 404都是随机性出现的   时不时突然出现然后过一段时间又没有了  这种会不会影响到文件的复制？
![image](https://user-images.githubusercontent.com/46810638/87220235-b952aa00-c394-11ea-803a-3be887e353cb.png)

**Comment by iwestlin** [comment]
我确认下啊，你检测的是目标目录的ID，也就是你自己的文件夹，不是源文件夹对吧？

如果不是sa的问题，那就是分享者取消了部分文件导致的。

另外每次请求会有7次重试的机会，只有8次连续失败才会导致这个文件复制失败。

**Comment by Wilnk** [comment]
我检测的是自己团队盘的盘ID，是自己的。并不是分享者的，你这样一说，我觉得很有可能是分享者那边的问题了。谢谢

**Comment by iwestlin** [comment]
那样的话可以在命令后面加一个 `-u`表示强制更新源文件夹的信息，不加的话默认会用到本地数据库的记录（如果有的话）

**Comment by Wilnk** [comment]
好的。如果任务被意外中断后，重新执行会有重复的文件嘛？

**Comment by iwestlin** [comment]
不会的，如果监测到之前的记录，程序会提供三个选项 继续/重来/退出，选择继续的话会接上之前的进度

**Comment by Wilnk** [comment]
好的  谢谢
