### ISSUE TITLE
大佬可不可以定时清理过期的数据库内容

### ISSUE THREAD

**Issue by 2595133804** [iwestlin/gd-utils#92]
我在vps跑了几天的机器人，占用了数G的硬盘容量，可以做一下优化吗

**Comment by iwestlin** [comment]
数G这么多吗。。
比较占空间的是日志文件还是数据库？
如果是日志的话可以 pm2 flush 清空。
而且日志这么大的话应该有很多报错，建议看看里面的内容（在 `~/.pm2/logs` 里）。

如果是数据库的话可以用sqlite数据库管理软件打开，清空里面的`gd`表。
或者也可以从 https://github.com/iwestlin/gd-utils/blob/master/gdurl.sqlite 下载空的数据库文件替换掉以前的，不过那样的话会丢失任务记录和bookmark记录

可以执行 ./backup-db.js 将数据库备份到 backup 目录先

**Comment by iwestlin** [comment]
7月21日更新添加了 clear-db.js

> 执行node clear-db.js就可以删除所有获取的文件信息（但会保留拷贝记录和bookmark）同时减小数据库文件大小了
