### ISSUE TITLE
【Docker版】Docker版上线

### ISSUE THREAD

**Issue by gdtool** [iwestlin/gd-utils#93]
尊敬的作者，docker版已经做好，望添加到readme.md

此docker版，涵盖了**webshell、文件管理器**，方便维护sa文件、config文件，以及重启服务

[https://github.com/gdtool/gd-utils-docker](https://github.com/gdtool/gd-utils-docker)

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/commit/2f261a68da5bd0b6607b994c24e0e7b8d8d36ce3
已添加，多谢贡献
