### ISSUE TITLE
用户友好性建议 命令行参数增加并行数选项

### ISSUE THREAD

**Issue by sztuxp** [iwestlin/gd-utils#96]
因为VPS运营商不能容忍某个用户长期占用资源，但突发一段时间是可以的，因此，在VPS上会有二种场景：1、大数据备份，时间长，需要一个低的并行数，2、小数据转存，时间短，这时，可以有一个高的并行数，这两个场景切换需要打开配置文件进行修改，稍微不方便，建议增加一个并行数的命令行参数，如果有，就取它，没有，就取配置文件，类似于目的路径

**Comment by iwestlin** [comment]
https://github.com/iwestlin/gd-utils/commit/80f57e2bda79d754eab862e5738cf5a55b23fbda
加了个命令行参数 `--limit`，简写 `-l`

可以这么用：
```
./count -l 15 folderID -S
```
同时对`./copy` `./dedupe`也适用

**Comment by sztuxp** [comment]
非常感谢！
