### ISSUE TITLE
树形导出类型错误

### ISSUE THREAD

**Issue by JiangJiaWei520** [iwestlin/gd-utils#99]
{"file_count":561,"folder_count":10,"total_size":"37.43 GB","details":[{"ext":"tif","count":282,"size":"37.11 GB","raw_size":39847232972},{"ext":"jpg","count":277,"size":"120.00 MB","raw_size":125828677},{"ext":"无扩展名","count":2,"size":"208.99 MB","raw_size":219147110},{"ext":"文件夹","count":10,"size":0,"raw_size":0}]}
请教下域名调用接口不返还统计信息，这个大致和那些设置有关

**Comment by iwestlin** [comment]
命令就是导出html的啊。。你可以加个 `-o tree.html`表示将结果存储在 tree.html里，然后浏览器直接打开这个 tree.html 就能看到了。
api设置可以看看
https://github.com/iwestlin/gd-utils#%E4%B8%93%E5%AE%B6%E8%AE%BE%E7%BD%AE
和
https://github.com/iwestlin/gd-utils/issues/52#issuecomment-653329832

**Comment by JiangJiaWei520** [comment]
> 命令就是导出html的啊。。你可以加个 `-o tree.html`表示将结果存储在 tree.html里，然后浏览器直接打开这个 tree.html 就能看到了。
> api设置可以看看
> https://github.com/iwestlin/gd-utils#%E4%B8%93%E5%AE%B6%E8%AE%BE%E7%BD%AE
> 和
> [#52 (comment)](https://github.com/iwestlin/gd-utils/issues/52#issuecomment-653329832)

这个值已经设置，并且导出到tree.html里面了我查看过了的确是对的，只是通过浏览器调用的时候&type=tree返回值是是上面发的那个而不是html的内容

**Comment by iwestlin** [comment]
我懂你意思了。。因为我没给 `/api/gdurl/count`加上这功能啊。。
https://github.com/iwestlin/gd-utils/blob/master/src/router.js#L24
一是因为基本没什么人用这接口。。二是因为生成树形数据比较吃性能，而存储这个数据需要在数据库加个字段比较麻烦我就没搞了……
